/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2026-05-24 09:01:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import work.dto.MemberDTO;
import work.dao.MemberDAO;
import java.util.ArrayList;

public final class admin_005fmember_005fedit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/navbar.jsp", Long.valueOf(1779373637269L));
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1779373637201L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("work.dao.MemberDAO");
    _jspx_imports_classes.add("work.dto.MemberDTO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

    // 서블릿에서 보낸 member 객체를 가져옴
    MemberDTO member = (MemberDTO)request.getAttribute("member");
    if (member == null) {
        response.sendRedirect("admin_member_list.jsp");
        return;
    }

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>직원 정보 수정 - AlbaPass</title>\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Pretendard:wght@400;600;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/style.css\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" href=\"");
      out.print(request.getContextPath());
      out.write("/jlogo.png\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write('\n');
      out.write('\n');

    // 1. 세션 변수 안전하게 가져오기
    String navUserId = (String)session.getAttribute("userId");
    String navUserName = (String)session.getAttribute("userName");
    String navUserRole = (String)session.getAttribute("userRole"); 
    String navUserStoreId = (String)session.getAttribute("userStoreId"); 

    // 2. 매장 목록 가져오기 (에러 방지를 위해 초기화)
    ArrayList<String[]> myStoreList = new ArrayList<>();
    
    // 로그인 상태일 때만 DB 조회
    if (navUserId != null) {
        try {
            MemberDAO navDao = new MemberDAO();
            myStoreList = navDao.getMyStoreList(navUserId);
        } catch (Exception e) {
            System.err.println("Navbar Store List Error: " + e.getMessage());
        }
    }

      out.write("\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark shadow-sm fixed-top\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <a class=\"navbar-brand d-flex align-items-center\" href=\"");
      out.print(request.getContextPath());
      out.write("/default.jsp\">\n");
      out.write("            <img src=\"");
      out.print(request.getContextPath());
      out.write("/Emblem.png\" alt=\"AlbaPass 로고\" style=\"height: 36px; object-fit: contain;\">\n");
      out.write("        </a>\n");
      out.write("        \n");
      out.write("        <div class=\"d-flex align-items-center\">\n");
      out.write("            ");
 if(navUserId == null) { 
      out.write("\n");
      out.write("                <a href=\"login.jsp\" class=\"btn btn-outline-light btn-sm me-2\">로그인</a>\n");
      out.write("                <a href=\"register.jsp\" class=\"btn btn-primary btn-sm\">회원가입</a>\n");
      out.write("            ");
 } else { 
      out.write("\n");
      out.write("                <div class=\"text-white me-3 d-none d-md-block small\">\n");
      out.write("                    <span class=\"badge ");

                        if ("SA".equals(navUserRole)) { 
      out.write("bg-danger");

                        } else if ("A".equals(navUserRole)) { 
      out.write("bg-primary");

                        } else { 
      out.write("bg-warning text-dark");
 } 
      out.write(" me-1\">\n");
      out.write("                        ");
 if ("SA".equals(navUserRole)) { 
      out.write("전체관리자");

                        } else if ("A".equals(navUserRole)) { 
      out.write('점');
      out.write('장');

                        } else { 
      out.write('직');
      out.write('원');
 } 
      out.write("\n");
      out.write("                    </span>\n");
      out.write("                    <strong>");
      out.print(navUserName);
      out.write("</strong>님\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                ");
 if (!"SA".equals(navUserRole)) { 
      out.write("\n");
      out.write("                ");
 if (navUserStoreId != null && !navUserStoreId.isEmpty()) { 
      out.write("\n");
      out.write("                <span class=\"text-white-50 small me-2 d-none d-md-block\">\n");
      out.write("                    <i class=\"fa-solid fa-store me-1\"></i>");
      out.print(navUserStoreId);
      out.write("\n");
      out.write("                </span>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("                <button class=\"btn btn-sm btn-outline-light me-2\" data-bs-toggle=\"modal\" data-bs-target=\"#changeStoreModal\">\n");
      out.write("                    <i class=\"fa-solid fa-rotate\"></i> 매장변경\n");
      out.write("                </button>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("                <form action=\"");
      out.print(request.getContextPath());
      out.write("/Logout\" method=\"post\" class=\"m-0\">\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-danger btn-sm\">로그아웃</button>\n");
      out.write("                </form>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("<div class=\"modal fade\" id=\"changeStoreModal\" tabindex=\"-1\" aria-hidden=\"true\">\n");
      out.write("    <div class=\"modal-dialog modal-sm modal-dialog-centered\">\n");
      out.write("        <div class=\"modal-content\">\n");
      out.write("            <div class=\"modal-header\">\n");
      out.write("                <h6 class=\"modal-title fw-bold\">접속 매장 선택</h6>\n");
      out.write("                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"></button>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"modal-body p-0\">\n");
      out.write("                <div class=\"list-group list-group-flush\">\n");
      out.write("                    ");
 if(myStoreList == null || myStoreList.isEmpty()) { 
      out.write("\n");
      out.write("                        <div class=\"p-4 text-center\">\n");
      out.write("                            <p class=\"text-muted small mb-2\">등록된 매장이 없습니다.</p>\n");
      out.write("                            <a href=\"MyPage\" class=\"btn btn-sm btn-primary\">매장 등록하기</a>\n");
      out.write("                        </div>\n");
      out.write("                    ");
 } else { 
                        for(String[] s : myStoreList) { 
                            boolean isCurrent = s[0].equals(navUserStoreId);
                    
      out.write("\n");
      out.write("                        <button type=\"button\" onclick=\"changeStore('");
      out.print(s[0]);
      out.write("')\" \n");
      out.write("                                class=\"list-group-item list-group-item-action d-flex justify-content-between align-items-center py-3 ");
      out.print( isCurrent ? "bg-light fw-bold" : "" );
      out.write("\">\n");
      out.write("                            <span>");
      out.print(s[1]);
      out.write(" <small class=\"text-muted\">(");
      out.print(s[0]);
      out.write(")</small></span>\n");
      out.write("                            ");
 if(isCurrent) { 
      out.write("<i class=\"fa-solid fa-check text-primary\"></i>");
 } 
      out.write("\n");
      out.write("                        </button>\n");
      out.write("                    ");
 } } 
      out.write("\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"modal-footer border-0\">\n");
      out.write("                <a href=\"MyPage\" class=\"btn btn-link btn-sm text-decoration-none text-muted mx-auto\">매장 추가/삭제 관리</a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("function changeStore(storeId) {\n");
      out.write("    if(!storeId) return;\n");
      out.write("    fetch('ChangeStore', {\n");
      out.write("        method: 'POST',\n");
      out.write("        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },\n");
      out.write("        body: 'storeId=' + encodeURIComponent(storeId)\n");
      out.write("    })\n");
      out.write("    .then(res => res.json())\n");
      out.write("    .then(data => {\n");
      out.write("        if(data.status === 'success') {\n");
      out.write("            showToast(data.message, data.status === 'success' ? 'success' : 'danger');\n");
      out.write("            location.reload(); \n");
      out.write("        } else {\n");
      out.write("            showToast(data.message, data.status === 'success' ? 'success' : 'danger');\n");
      out.write("        }\n");
      out.write("    })\n");
      out.write("    .catch(err => console.error('Error:', err));\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("    body { padding-top: 70px; }\n");
      out.write("    .list-group-item-action:active { background-color: #f8f9fc; color: inherit; }\n");
      out.write("</style>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container mt-5 mb-5\" style=\"max-width: 600px;\">\r\n");
      out.write("    <div class=\"d-flex justify-content-between align-items-center mb-4\">\r\n");
      out.write("        <h3 class=\"fw-bold text-dark mb-0\">\r\n");
      out.write("            <i class=\"fa-solid fa-user-pen me-2 text-primary\"></i>직원 정보 수정\r\n");
      out.write("        </h3>\r\n");
      out.write("        <a href=\"admin_member_list.jsp\" class=\"btn btn-outline-secondary btn-sm fw-bold px-3\">\r\n");
      out.write("            <i class=\"fa-solid fa-arrow-left me-1\"></i> 목록으로\r\n");
      out.write("        </a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"card custom-card p-4 shadow-sm border-0\">\r\n");
      out.write("        <div class=\"text-center mb-4\">\r\n");
      out.write("            <div class=\"icon-box bg-primary-subtle text-primary mx-auto mb-3\" style=\"width: 70px; height: 70px;\">\r\n");
      out.write("                <i class=\"fa-solid fa-user-check fa-2x\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("            <h5 class=\"fw-bold text-dark\">");
      out.print(member.getName());
      out.write(" 직원님</h5>\r\n");
      out.write("            <small class=\"text-muted\">직원의 기본 인적사항 및 시급을 수정합니다.</small>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <form action=\"AdminMemberUpdate\" method=\"post\">\r\n");
      out.write("            <input type=\"hidden\" name=\"id\" value=\"");
      out.print(member.getId());
      out.write("\">\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"row g-3\">\r\n");
      out.write("                <div class=\"col-md-6\">\r\n");
      out.write("                    <label class=\"form-label small fw-bold text-secondary\">이름</label>\r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                        <span class=\"input-group-text bg-light border-end-0\"><i class=\"fa-solid fa-signature text-muted\"></i></span>\r\n");
      out.write("                        <input type=\"text\" value=\"");
      out.print(member.getName());
      out.write("\" class=\"form-control bg-light\" readonly>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-md-6\">\r\n");
      out.write("                    <label class=\"form-label small fw-bold text-secondary\">전화번호</label>\r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                        <span class=\"input-group-text bg-light border-end-0\"><i class=\"fa-solid fa-phone text-muted\"></i></span>\r\n");
      out.write("                        <input type=\"text\" value=\"");
      out.print(member.getPhone());
      out.write("\" class=\"form-control bg-light\" readonly>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 mt-4\">\r\n");
      out.write("                    <label class=\"form-label small fw-bold text-primary\">시급 설정 (원)</label>\r\n");
      out.write("                    <div class=\"input-group input-group-lg\">\r\n");
      out.write("                        <span class=\"input-group-text bg-white border-end-0 text-primary\"><i class=\"fa-solid fa-won-sign\"></i></span>\r\n");
      out.write("                        <input type=\"number\" name=\"wage\" value=\"");
      out.print(member.getHourlyWage());
      out.write("\" class=\"form-control border-start-0 ps-0 fw-bold text-primary\" placeholder=\"숫자만 입력\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <p class=\"text-muted mt-2 small\">\r\n");
      out.write("                        <i class=\"fa-solid fa-circle-info me-1\"></i> 시급 변경 시, 이후 기록되는 급여 정산부터 반영됩니다.\r\n");
      out.write("                    </p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"mt-5 d-flex gap-2\">\r\n");
      out.write("                <a href=\"admin_member_list.jsp\" class=\"btn btn-light flex-fill py-3 fw-bold border\">취소</a>\r\n");
      out.write("                <button type=\"submit\" class=\"btn btn-primary flex-fill py-3 fw-bold shadow-sm\">수정 완료</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\n");
      out.write("<footer class=\"text-center py-5 text-muted bg-white mt-auto border-top no-print\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <p class=\"mb-1 fw-bold text-dark\">AlbaPass</p>\n");
      out.write("        <small>© 2026 AlbaPass Project. All rights reserved.</small>\n");
      out.write("    </div>\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"toast-container position-fixed bottom-0 end-0 p-3\" style=\"z-index: 9999;\">\n");
      out.write("    <div id=\"appToast\" class=\"toast align-items-center border-0 shadow\" role=\"alert\" aria-live=\"assertive\">\n");
      out.write("        <div class=\"d-flex\">\n");
      out.write("            <div class=\"toast-body fw-bold\" id=\"appToastMsg\">\n");
      out.write("                메시지\n");
      out.write("            </div>\n");
      out.write("            <button type=\"button\" class=\"btn-close btn-close-white me-2 m-auto\" data-bs-dismiss=\"toast\"></button>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("<script>\n");
      out.write("// 공통 토스트 함수\n");
      out.write("function showToast(message, type) {\n");
      out.write("    type = type || 'success'; // success, danger, warning, info\n");
      out.write("    const toast    = document.getElementById('appToast');\n");
      out.write("    const toastMsg = document.getElementById('appToastMsg');\n");
      out.write("\n");
      out.write("    // 색상 설정\n");
      out.write("    toast.className = 'toast align-items-center border-0 shadow text-white';\n");
      out.write("    if (type === 'success') toast.classList.add('bg-success');\n");
      out.write("    else if (type === 'danger')  toast.classList.add('bg-danger');\n");
      out.write("    else if (type === 'warning') toast.classList.add('bg-warning', 'text-dark');\n");
      out.write("    else if (type === 'info')    toast.classList.add('bg-primary');\n");
      out.write("\n");
      out.write("    toastMsg.innerText = message;\n");
      out.write("    const bsToast = new bootstrap.Toast(toast, { delay: 3000 });\n");
      out.write("    bsToast.show();\n");
      out.write("}\n");
      out.write("\n");
      out.write("// alert 대체 함수 (기존 코드와 호환)\n");
      out.write("function showAlert(message, type) {\n");
      out.write("    showToast(message, type || 'info');\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
