/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2026-05-25 06:47:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import work.dto.AttendanceDTO;
import work.dto.MemberDTO;
import java.util.*;
import java.text.SimpleDateFormat;
import work.dao.MemberDAO;
import java.util.ArrayList;

public final class admin_005fattendance_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/navbar.jsp", Long.valueOf(1779373637269L));
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1779373637201L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("work.dto.AttendanceDTO");
    _jspx_imports_classes.add("work.dao.MemberDAO");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("work.dto.MemberDTO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    // 세션 체크
    String _userId = (String) session.getAttribute("userId");
    String _role   = (String) session.getAttribute("userRole");
    if (_userId == null || !"A".equals(_role != null ? _role.trim() : "")) {
        response.sendRedirect("login.jsp");
        return;
    }

    // 1. 서블릿(AdminHistory)으로부터 데이터 수신
    ArrayList<AttendanceDTO> fullList   = (ArrayList<AttendanceDTO>) request.getAttribute("fullList");
    ArrayList<MemberDTO>     memberList = (ArrayList<MemberDTO>)     request.getAttribute("memberList");

    // 🚨 팩트체크: 만약 서블릿을 거치지 않고 직접 JSP에 접속했다면 서블릿으로 강제 이동시킵니다.
    if (fullList == null || memberList == null) {
        response.sendRedirect("AdminHistory");
        return;
    }

    // 서블릿이 다시 보내준 검색 파라미터 복구
    String startDate = (String)request.getAttribute("startDate");
    String endDate = (String)request.getAttribute("endDate");
    String searchMemId = (String)request.getAttribute("searchMemId");
    
    // 기본값 방어 코드
    if (startDate == null) startDate = "";
    if (endDate == null) endDate = "";
    if (searchMemId == null) searchMemId = "";

    // 2. 페이징 처리 (전달받은 fullList 기준)
    int currentPage = 1;
    String pageParam = request.getParameter("page");
    if (pageParam != null && !pageParam.isEmpty()) {
        currentPage = Integer.parseInt(pageParam);
    }
    int itemsPerPage = 10;
    int totalItems = fullList.size();
    int totalPages = (int)Math.ceil((double)totalItems / itemsPerPage);
    if (totalPages == 0) totalPages = 1;

    int startIndex = (currentPage - 1) * itemsPerPage;
    int endIndex = Math.min(startIndex + itemsPerPage, totalItems);
    List<AttendanceDTO> list = (totalItems > 0) ? fullList.subList(startIndex, endIndex) : new ArrayList<>();

    // 3. 급여 계산 로직 (기존 로직 유지하되 fullList 기반으로 작동)
    long totalMinutes = 0;      
    double basePay = 0;         
    double holidayPay = 0;      
    int hourlyWage = 0;
    String targetName = "";
    int totalEstimatedSalary = 0;
    
    if (!searchMemId.equals("") && fullList.size() > 0) {
        // 직원 정보는 이미 memberList에 있으므로 거기서 찾거나 필요시 전용 로직 수행
        for(MemberDTO m : memberList) {
            if(m.getId().equals(searchMemId)) {
                hourlyWage = m.getHourlyWage();
                targetName = m.getName();
                break;
            }
        }

        ArrayList<AttendanceDTO> calcList = new ArrayList<>(fullList);
        Collections.reverse(calcList); 

        SimpleDateFormat sdfFull = new SimpleDateFormat("yyyy-MM-dd HH:mm");
        Calendar cal = Calendar.getInstance();
        Map<String, Long> weeklyMap = new HashMap<>(); 
        Map<String, Date> lastInTimeMap = new HashMap<>(); 

        for (AttendanceDTO dto : calcList) {
            String storeKey = dto.getStoreName(); 
            try {
                if ("출근".equals(dto.getAttType())) {
                    lastInTimeMap.put(storeKey, sdfFull.parse(dto.getAttTime()));
                } 
                else if ("퇴근".equals(dto.getAttType())) {
                    if (lastInTimeMap.containsKey(storeKey)) {
                        Date inTime = lastInTimeMap.get(storeKey);
                        Date outTime = sdfFull.parse(dto.getAttTime());
                        long diff = outTime.getTime() - inTime.getTime();
                        totalMinutes += (diff / (1000 * 60));
                        cal.setTime(inTime);
                        String weekKey = cal.get(Calendar.YEAR) + "-" + cal.get(Calendar.WEEK_OF_YEAR);
                        weeklyMap.put(weekKey, weeklyMap.getOrDefault(weekKey, 0L) + (diff / (1000 * 60)));
                        lastInTimeMap.remove(storeKey); 
                    }
                }
            } catch(Exception e){}
        }
        double recognizedHours = (totalMinutes / 30) * 0.5;
        basePay = recognizedHours * hourlyWage;
        for (String key : weeklyMap.keySet()) {
            if (weeklyMap.get(key) >= 900) { 
                double weekHours = Math.min(weeklyMap.get(key)/60.0, 40);
                holidayPay += (weekHours / 40.0) * 8 * hourlyWage;
            }
        }
        totalEstimatedSalary = (int)(basePay + holidayPay);
    }

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>근태 관리 - AlbaPass</title>\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Pretendard:wght@400;600;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/style.css\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" href=\"");
      out.print(request.getContextPath());
      out.write("/jlogo.png\">\r\n");
      out.write("    <style>\r\n");
      out.write("        .form-check-input[type=\"radio\"] { display: none; }\r\n");
      out.write("        .form-check-input[type=\"radio\"]:checked + label.btn-outline-success { background-color: #198754 !important; color: white !important; }\r\n");
      out.write("        .form-check-input[type=\"radio\"]:checked + label.btn-outline-secondary { background-color: #6c757d !important; color: white !important; }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write('\n');
      out.write('\n');

    // 1. 세션 변수 안전하게 가져오기
    String navUserId = (String)session.getAttribute("userId");
    String navUserName = (String)session.getAttribute("userName");
    String navUserRole = (String)session.getAttribute("userRole"); 
    String navUserStoreId = (String)session.getAttribute("userStoreId"); 

    // 2. 매장 목록 가져오기 (에러 방지를 위해 초기화)
    ArrayList<String[]> myStoreList = new ArrayList<>();
    
    // 로그인 상태일 때만 DB 조회
    if (navUserId != null) {
        try {
            MemberDAO navDao = new MemberDAO();
            myStoreList = navDao.getMyStoreList(navUserId);
        } catch (Exception e) {
            System.err.println("Navbar Store List Error: " + e.getMessage());
        }
    }

      out.write("\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark shadow-sm fixed-top\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <a class=\"navbar-brand d-flex align-items-center\" href=\"");
      out.print(request.getContextPath());
      out.write("/default.jsp\">\n");
      out.write("            <img src=\"");
      out.print(request.getContextPath());
      out.write("/Emblem.png\" alt=\"AlbaPass 로고\" style=\"height: 36px; object-fit: contain;\">\n");
      out.write("        </a>\n");
      out.write("        \n");
      out.write("        <div class=\"d-flex align-items-center\">\n");
      out.write("            ");
 if(navUserId == null) { 
      out.write("\n");
      out.write("                <a href=\"login.jsp\" class=\"btn btn-outline-light btn-sm me-2\">로그인</a>\n");
      out.write("                <a href=\"register.jsp\" class=\"btn btn-primary btn-sm\">회원가입</a>\n");
      out.write("            ");
 } else { 
      out.write("\n");
      out.write("                <div class=\"text-white me-3 d-none d-md-block small\">\n");
      out.write("                    <span class=\"badge ");

                        if ("SA".equals(navUserRole)) { 
      out.write("bg-danger");

                        } else if ("A".equals(navUserRole)) { 
      out.write("bg-primary");

                        } else { 
      out.write("bg-warning text-dark");
 } 
      out.write(" me-1\">\n");
      out.write("                        ");
 if ("SA".equals(navUserRole)) { 
      out.write("전체관리자");

                        } else if ("A".equals(navUserRole)) { 
      out.write('점');
      out.write('장');

                        } else { 
      out.write('직');
      out.write('원');
 } 
      out.write("\n");
      out.write("                    </span>\n");
      out.write("                    <strong>");
      out.print(navUserName);
      out.write("</strong>님\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                ");
 if (!"SA".equals(navUserRole)) { 
      out.write("\n");
      out.write("                ");
 if (navUserStoreId != null && !navUserStoreId.isEmpty()) { 
      out.write("\n");
      out.write("                <span class=\"text-white-50 small me-2 d-none d-md-block\">\n");
      out.write("                    <i class=\"fa-solid fa-store me-1\"></i>");
      out.print(navUserStoreId);
      out.write("\n");
      out.write("                </span>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("                <button class=\"btn btn-sm btn-outline-light me-2\" data-bs-toggle=\"modal\" data-bs-target=\"#changeStoreModal\">\n");
      out.write("                    <i class=\"fa-solid fa-rotate\"></i> 매장변경\n");
      out.write("                </button>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("                <form action=\"");
      out.print(request.getContextPath());
      out.write("/Logout\" method=\"post\" class=\"m-0\">\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-danger btn-sm\">로그아웃</button>\n");
      out.write("                </form>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("<div class=\"modal fade\" id=\"changeStoreModal\" tabindex=\"-1\" aria-hidden=\"true\">\n");
      out.write("    <div class=\"modal-dialog modal-sm modal-dialog-centered\">\n");
      out.write("        <div class=\"modal-content\">\n");
      out.write("            <div class=\"modal-header\">\n");
      out.write("                <h6 class=\"modal-title fw-bold\">접속 매장 선택</h6>\n");
      out.write("                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"></button>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"modal-body p-0\">\n");
      out.write("                <div class=\"list-group list-group-flush\">\n");
      out.write("                    ");
 if(myStoreList == null || myStoreList.isEmpty()) { 
      out.write("\n");
      out.write("                        <div class=\"p-4 text-center\">\n");
      out.write("                            <p class=\"text-muted small mb-2\">등록된 매장이 없습니다.</p>\n");
      out.write("                            <a href=\"MyPage\" class=\"btn btn-sm btn-primary\">매장 등록하기</a>\n");
      out.write("                        </div>\n");
      out.write("                    ");
 } else { 
                        for(String[] s : myStoreList) { 
                            boolean isCurrent = s[0].equals(navUserStoreId);
                    
      out.write("\n");
      out.write("                        <button type=\"button\" onclick=\"changeStore('");
      out.print(s[0]);
      out.write("')\" \n");
      out.write("                                class=\"list-group-item list-group-item-action d-flex justify-content-between align-items-center py-3 ");
      out.print( isCurrent ? "bg-light fw-bold" : "" );
      out.write("\">\n");
      out.write("                            <span>");
      out.print(s[1]);
      out.write(" <small class=\"text-muted\">(");
      out.print(s[0]);
      out.write(")</small></span>\n");
      out.write("                            ");
 if(isCurrent) { 
      out.write("<i class=\"fa-solid fa-check text-primary\"></i>");
 } 
      out.write("\n");
      out.write("                        </button>\n");
      out.write("                    ");
 } } 
      out.write("\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"modal-footer border-0\">\n");
      out.write("                <a href=\"MyPage\" class=\"btn btn-link btn-sm text-decoration-none text-muted mx-auto\">매장 추가/삭제 관리</a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("function changeStore(storeId) {\n");
      out.write("    if(!storeId) return;\n");
      out.write("    fetch('ChangeStore', {\n");
      out.write("        method: 'POST',\n");
      out.write("        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },\n");
      out.write("        body: 'storeId=' + encodeURIComponent(storeId)\n");
      out.write("    })\n");
      out.write("    .then(res => res.json())\n");
      out.write("    .then(data => {\n");
      out.write("        if(data.status === 'success') {\n");
      out.write("            showToast(data.message, data.status === 'success' ? 'success' : 'danger');\n");
      out.write("            location.reload(); \n");
      out.write("        } else {\n");
      out.write("            showToast(data.message, data.status === 'success' ? 'success' : 'danger');\n");
      out.write("        }\n");
      out.write("    })\n");
      out.write("    .catch(err => console.error('Error:', err));\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("    body { padding-top: 70px; }\n");
      out.write("    .list-group-item-action:active { background-color: #f8f9fc; color: inherit; }\n");
      out.write("</style>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container mt-5 mb-5\">\r\n");
      out.write("    <div class=\"d-flex justify-content-between align-items-center mb-4\">\r\n");
      out.write("        <h3 class=\"fw-bold text-dark mb-0\"><i class=\"fa-solid fa-clock-rotate-left me-2 text-primary\"></i>근태 관리 및 정산</h3>\r\n");
      out.write("        <a href=\"default.jsp\" class=\"btn btn-outline-secondary btn-sm fw-bold px-3\">\r\n");
      out.write("            <i class=\"fa-solid fa-arrow-left me-1\"></i> 대시보드\r\n");
      out.write("        </a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"row g-4\">\r\n");
      out.write("        <div class=\"col-lg-4\">\r\n");
      out.write("            <div class=\"card custom-card p-4 mb-4 border-top border-4 border-primary shadow-sm\">\r\n");
      out.write("                <h6 class=\"fw-bold mb-3\"><i class=\"fa-solid fa-filter me-2 text-primary\"></i>조회 필터</h6>\r\n");
      out.write("                <form action=\"AdminHistory\" method=\"get\">\r\n");
      out.write("                    <div class=\"mb-2\">\r\n");
      out.write("                        <label class=\"form-label small fw-bold text-secondary\">시작일</label>\r\n");
      out.write("                        <input type=\"date\" name=\"startDate\" value=\"");
      out.print(startDate);
      out.write("\" class=\"form-control form-control-sm\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"mb-3\">\r\n");
      out.write("                        <label class=\"form-label small fw-bold text-secondary\">종료일</label>\r\n");
      out.write("                        <input type=\"date\" name=\"endDate\" value=\"");
      out.print(endDate);
      out.write("\" class=\"form-control form-control-sm\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"mb-4\">\r\n");
      out.write("                        <label class=\"form-label small fw-bold text-secondary\">직원 선택</label>\r\n");
      out.write("                        <select name=\"searchMemId\" class=\"form-select form-select-sm\">\r\n");
      out.write("                            <option value=\"\">전체 직원</option>\r\n");
      out.write("                            ");
 for(MemberDTO m : memberList) { 
      out.write("\r\n");
      out.write("                                <option value=\"");
      out.print(m.getId());
      out.write('"');
      out.write(' ');
      out.print(m.getId().equals(searchMemId)?"selected":"");
      out.write('>');
      out.print(m.getName());
      out.write("</option>\r\n");
      out.write("                            ");
 } 
      out.write("\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-primary w-100 fw-bold mb-2\">\r\n");
      out.write("                        <i class=\"fa-solid fa-search me-1\"></i>조회하기\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-success w-100 fw-bold\" onclick=\"openAddModal()\">\r\n");
      out.write("                        <i class=\"fa-solid fa-plus me-1\"></i> 기록 수동 추가\r\n");
      out.write("                    </button>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("            ");
 if (!searchMemId.equals("") && fullList.size() > 0) { 
      out.write("\r\n");
      out.write("                <div class=\"card custom-card p-4 text-white border-0 shadow-lg\" style=\"background: linear-gradient(135deg, #4e73df 0%, #224abe 100%);\">\r\n");
      out.write("                    <small class=\"opacity-75\">");
      out.print(targetName);
      out.write("님 예상 급여</small>\r\n");
      out.write("                    <h2 class=\"fw-bold mb-3\">￦ ");
      out.print(String.format("%,d", totalEstimatedSalary));
      out.write("</h2>\r\n");
      out.write("                    <hr class=\"opacity-25\">\r\n");
      out.write("                    <div class=\"d-flex justify-content-between small\"><span>기본급</span><span>￦");
      out.print(String.format("%,d", (int)basePay));
      out.write("</span></div>\r\n");
      out.write("                    <div class=\"d-flex justify-content-between small mt-1\"><span>주휴수당</span><span>￦");
      out.print(String.format("%,d", (int)holidayPay));
      out.write("</span></div>\r\n");
      out.write("                </div>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-lg-8\">\r\n");
      out.write("            <div class=\"card custom-card p-0 overflow-hidden shadow-sm\">\r\n");
      out.write("                <div class=\"table-responsive\">\r\n");
      out.write("                    <table class=\"table custom-table mb-0 align-middle\">\r\n");
      out.write("                        <thead class=\"table-light\">\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th class=\"ps-4\">직원명</th>\r\n");
      out.write("                                <th>날짜 / 시간</th>\r\n");
      out.write("                                <th class=\"text-center\">상태</th>\r\n");
      out.write("                                <th class=\"text-center d-none d-md-table-cell\">관리</th>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </thead>\r\n");
      out.write("                        <tbody>\r\n");
      out.write("                            ");
 if(list.isEmpty()) { 
      out.write("\r\n");
      out.write("                                <tr><td colspan=\"4\" class=\"text-center py-5 text-muted\">기록이 없습니다.</td></tr>\r\n");
      out.write("                            ");
 } 
      out.write("\r\n");
      out.write("                            ");
 for(AttendanceDTO dto : list) {
                                String fullDate = dto.getAttTime();
                                String dDate = fullDate.substring(0, 10);
                                String dTime = fullDate.substring(11, 16);
                                boolean isIn = "출근".equals(dto.getAttType());
                            
      out.write("\r\n");
      out.write("                            <tr class=\"");
      out.print(isIn ? "" : "");
      out.write("\">\r\n");
      out.write("                                <td class=\"ps-4\">\r\n");
      out.write("                                    <span class=\"fw-bold text-dark\">");
      out.print(dto.getMemberId());
      out.write("</span>\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <div class=\"fw-bold text-dark\">");
      out.print(dDate);
      out.write("</div>\r\n");
      out.write("                                    <small class=\"text-muted\">");
      out.print(dTime);
      out.write("</small>\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td class=\"text-center\">\r\n");
      out.write("                                    ");
if (isIn) {
      out.write("\r\n");
      out.write("                                        <span class=\"badge bg-success-subtle text-success px-3 py-2 rounded-pill fw-bold\">\r\n");
      out.write("                                            <i class=\"fa-solid fa-arrow-right-to-bracket me-1\"></i>출근\r\n");
      out.write("                                        </span>\r\n");
      out.write("                                    ");
} else {
      out.write("\r\n");
      out.write("                                        <span class=\"badge bg-secondary-subtle text-secondary px-3 py-2 rounded-pill fw-bold\">\r\n");
      out.write("                                            <i class=\"fa-solid fa-arrow-right-from-bracket me-1\"></i>퇴근\r\n");
      out.write("                                        </span>\r\n");
      out.write("                                    ");
}
      out.write("\r\n");
      out.write("                                    ");
      out.write("\r\n");
      out.write("                                    <div class=\"d-md-none mt-1\">\r\n");
      out.write("                                        <button class=\"btn btn-xs btn-outline-warning border-0 me-1\" onclick=\"openEditModal('");
      out.print(dto.getIdx());
      out.write("', '");
      out.print(dDate);
      out.write("', '");
      out.print(dTime);
      out.write("', '");
      out.print(dto.getAttType());
      out.write("', '");
      out.print(dto.getMemberId());
      out.write("')\">✏️</button>\r\n");
      out.write("                                        <button class=\"btn btn-xs btn-outline-danger border-0\" onclick=\"deleteRecord('");
      out.print(dto.getIdx());
      out.write("')\">🗑️</button>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td class=\"text-center d-none d-md-table-cell\">\r\n");
      out.write("                                    <button class=\"btn btn-sm btn-outline-warning border-0 me-1\" onclick=\"openEditModal('");
      out.print(dto.getIdx());
      out.write("', '");
      out.print(dDate);
      out.write("', '");
      out.print(dTime);
      out.write("', '");
      out.print(dto.getAttType());
      out.write("', '");
      out.print(dto.getMemberId());
      out.write("')\">✏️</button>\r\n");
      out.write("                                    <button class=\"btn btn-sm btn-outline-danger border-0\" onclick=\"deleteRecord('");
      out.print(dto.getIdx());
      out.write("')\">🗑️</button>\r\n");
      out.write("                                </td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            ");
 } 
      out.write("\r\n");
      out.write("                        </tbody>\r\n");
      out.write("                    </table>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"card-footer bg-white py-3 border-0\">\r\n");
      out.write("                    <nav>\r\n");
      out.write("                        <ul class=\"pagination pagination-sm justify-content-center mb-0\">\r\n");
      out.write("                            <li class=\"page-item ");
      out.print( (currentPage == 1) ? "disabled" : "" );
      out.write("\">\r\n");
      out.write("                                <a class=\"page-link\" href=\"AdminHistory?startDate=");
      out.print(startDate);
      out.write("&endDate=");
      out.print(endDate);
      out.write("&searchMemId=");
      out.print(searchMemId);
      out.write("&page=");
      out.print(currentPage-1);
      out.write("\">이전</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            ");
 for(int i=1; i<=totalPages; i++) { 
      out.write("\r\n");
      out.write("                                <li class=\"page-item ");
      out.print( (i == currentPage) ? "active" : "" );
      out.write("\">\r\n");
      out.write("                                    <a class=\"page-link\" href=\"AdminHistory?startDate=");
      out.print(startDate);
      out.write("&endDate=");
      out.print(endDate);
      out.write("&searchMemId=");
      out.print(searchMemId);
      out.write("&page=");
      out.print(i);
      out.write('"');
      out.write('>');
      out.print(i);
      out.write("</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            ");
 } 
      out.write("\r\n");
      out.write("                            <li class=\"page-item ");
      out.print( (currentPage == totalPages) ? "disabled" : "" );
      out.write("\">\r\n");
      out.write("                                <a class=\"page-link\" href=\"AdminHistory?startDate=");
      out.print(startDate);
      out.write("&endDate=");
      out.print(endDate);
      out.write("&searchMemId=");
      out.print(searchMemId);
      out.write("&page=");
      out.print(currentPage+1);
      out.write("\">다음</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </nav>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"modal fade\" id=\"attModal\" tabindex=\"-1\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog modal-dialog-centered\">\r\n");
      out.write("        <div class=\"modal-content border-0 shadow\">\r\n");
      out.write("            <div class=\"modal-header border-0 pb-0\">\r\n");
      out.write("                <h5 class=\"modal-title fw-bold\" id=\"modalTitle\">\r\n");
      out.write("                    <i class=\"fa-solid fa-clock-rotate-left me-2 text-primary\"></i>근태 기록 추가\r\n");
      out.write("                </h5>\r\n");
      out.write("                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"></button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <form action=\"AdminAttendanceAction\" method=\"post\">\r\n");
      out.write("                <div class=\"modal-body pt-3\">\r\n");
      out.write("                    <input type=\"hidden\" name=\"mode\" id=\"modalMode\" value=\"add\">\r\n");
      out.write("                    <input type=\"hidden\" name=\"idx\" id=\"modalIdx\">\r\n");
      out.write("                    <input type=\"hidden\" name=\"returnStartDate\" value=\"");
      out.print(startDate);
      out.write("\">\r\n");
      out.write("                    <input type=\"hidden\" name=\"returnEndDate\" value=\"");
      out.print(endDate);
      out.write("\">\r\n");
      out.write("                    <input type=\"hidden\" name=\"returnSearchMemId\" value=\"");
      out.print(searchMemId);
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("                    ");
      out.write("\r\n");
      out.write("                    <div class=\"mb-3\">\r\n");
      out.write("                        <label class=\"form-label small fw-bold text-secondary\">직원 선택</label>\r\n");
      out.write("                        <select name=\"memId\" id=\"modalMemId\" class=\"form-select\" required>\r\n");
      out.write("                            ");
 for(MemberDTO m : memberList) { 
      out.write("\r\n");
      out.write("                                <option value=\"");
      out.print(m.getId());
      out.write('"');
      out.write('>');
      out.print(m.getName());
      out.write(' ');
      out.write('(');
      out.print(m.getId());
      out.write(")</option>\r\n");
      out.write("                            ");
 } 
      out.write("\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    ");
      out.write("\r\n");
      out.write("                    <div class=\"mb-3\">\r\n");
      out.write("                        <label class=\"form-label small fw-bold text-secondary\">구분</label>\r\n");
      out.write("                        <div class=\"d-flex gap-2\">\r\n");
      out.write("                            <div class=\"form-check form-check-inline flex-fill\">\r\n");
      out.write("                                <input class=\"form-check-input\" type=\"radio\" name=\"type\" id=\"typeIn\" value=\"출근\" checked>\r\n");
      out.write("                                <label class=\"form-check-label btn btn-outline-success w-100 fw-bold\" for=\"typeIn\">\r\n");
      out.write("                                    <i class=\"fa-solid fa-arrow-right-to-bracket me-1\"></i>출근\r\n");
      out.write("                                </label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-check form-check-inline flex-fill\">\r\n");
      out.write("                                <input class=\"form-check-input\" type=\"radio\" name=\"type\" id=\"typeOut\" value=\"퇴근\">\r\n");
      out.write("                                <label class=\"form-check-label btn btn-outline-secondary w-100 fw-bold\" for=\"typeOut\">\r\n");
      out.write("                                    <i class=\"fa-solid fa-arrow-right-from-bracket me-1\"></i>퇴근\r\n");
      out.write("                                </label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    ");
      out.write("\r\n");
      out.write("                    <div class=\"mb-3\">\r\n");
      out.write("                        <label class=\"form-label small fw-bold text-secondary\">날짜 및 시간</label>\r\n");
      out.write("                        <div class=\"input-group\">\r\n");
      out.write("                            <input type=\"date\" name=\"date\" id=\"modalDate\" class=\"form-control\" required>\r\n");
      out.write("                            <input type=\"time\" name=\"time\" id=\"modalTime\" class=\"form-control\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <small class=\"text-muted\">날짜와 시간을 함께 선택하세요.</small>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-footer border-0 pt-0\">\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-light fw-bold px-4\" data-bs-dismiss=\"modal\">취소</button>\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-primary fw-bold px-4\">\r\n");
      out.write("                        <i class=\"fa-solid fa-check me-1\"></i>저장하기\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<form id=\"deleteForm\" action=\"AdminAttendanceAction\" method=\"post\" style=\"display:none;\">\r\n");
      out.write("    <input type=\"hidden\" name=\"mode\" value=\"delete\">\r\n");
      out.write("    <input type=\"hidden\" name=\"idx\" id=\"deleteIdx\">\r\n");
      out.write("    <input type=\"hidden\" name=\"returnStartDate\" value=\"");
      out.print(startDate);
      out.write("\">\r\n");
      out.write("    <input type=\"hidden\" name=\"returnEndDate\" value=\"");
      out.print(endDate);
      out.write("\">\r\n");
      out.write("    <input type=\"hidden\" name=\"returnSearchMemId\" value=\"");
      out.print(searchMemId);
      out.write("\">\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\n");
      out.write("<footer class=\"text-center py-5 text-muted bg-white mt-auto border-top no-print\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <p class=\"mb-1 fw-bold text-dark\">AlbaPass</p>\n");
      out.write("        <small>© 2026 AlbaPass Project. All rights reserved.</small>\n");
      out.write("    </div>\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"toast-container position-fixed bottom-0 end-0 p-3\" style=\"z-index: 9999;\">\n");
      out.write("    <div id=\"appToast\" class=\"toast align-items-center border-0 shadow\" role=\"alert\" aria-live=\"assertive\">\n");
      out.write("        <div class=\"d-flex\">\n");
      out.write("            <div class=\"toast-body fw-bold\" id=\"appToastMsg\">\n");
      out.write("                메시지\n");
      out.write("            </div>\n");
      out.write("            <button type=\"button\" class=\"btn-close btn-close-white me-2 m-auto\" data-bs-dismiss=\"toast\"></button>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("<script>\n");
      out.write("// 공통 토스트 함수\n");
      out.write("function showToast(message, type) {\n");
      out.write("    type = type || 'success'; // success, danger, warning, info\n");
      out.write("    const toast    = document.getElementById('appToast');\n");
      out.write("    const toastMsg = document.getElementById('appToastMsg');\n");
      out.write("\n");
      out.write("    // 색상 설정\n");
      out.write("    toast.className = 'toast align-items-center border-0 shadow text-white';\n");
      out.write("    if (type === 'success') toast.classList.add('bg-success');\n");
      out.write("    else if (type === 'danger')  toast.classList.add('bg-danger');\n");
      out.write("    else if (type === 'warning') toast.classList.add('bg-warning', 'text-dark');\n");
      out.write("    else if (type === 'info')    toast.classList.add('bg-primary');\n");
      out.write("\n");
      out.write("    toastMsg.innerText = message;\n");
      out.write("    const bsToast = new bootstrap.Toast(toast, { delay: 3000 });\n");
      out.write("    bsToast.show();\n");
      out.write("}\n");
      out.write("\n");
      out.write("// alert 대체 함수 (기존 코드와 호환)\n");
      out.write("function showAlert(message, type) {\n");
      out.write("    showToast(message, type || 'info');\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    const attModal = new bootstrap.Modal(document.getElementById('attModal'));\r\n");
      out.write("\r\n");
      out.write("    function openAddModal() {\r\n");
      out.write("        document.getElementById('modalTitle').innerText = \"기록 수동 추가\";\r\n");
      out.write("        document.getElementById('modalMode').value = \"add\";\r\n");
      out.write("        document.getElementById('modalIdx').value = \"\";\r\n");
      out.write("        document.getElementById('modalMemId').disabled = false;\r\n");
      out.write("        attModal.show();\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function openEditModal(idx, date, time, type, memId) {\r\n");
      out.write("        document.getElementById('modalTitle').innerText = \"기록 수정\";\r\n");
      out.write("        document.getElementById('modalMode').value = \"update\";\r\n");
      out.write("        document.getElementById('modalIdx').value = idx;\r\n");
      out.write("        document.getElementById('modalDate').value = date;\r\n");
      out.write("        document.getElementById('modalTime').value = time;\r\n");
      out.write("        document.getElementById('modalType').value = type;\r\n");
      out.write("        document.getElementById('modalMemId').value = memId;\r\n");
      out.write("        document.getElementById('modalMemId').disabled = true; \r\n");
      out.write("        attModal.show();\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function deleteRecord(idx) {\r\n");
      out.write("        if(confirm(\"정말 이 근태 기록을 삭제하시겠습니까?\")) {\r\n");
      out.write("            document.getElementById('deleteIdx').value = idx;\r\n");
      out.write("            document.getElementById('deleteForm').submit();\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
