/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2026-05-20 12:36:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import work.dto.MemberDTO;
import java.util.ArrayList;
import work.dao.MemberDAO;
import java.util.ArrayList;

public final class admin_005fmember_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/navbar.jsp", Long.valueOf(1778926184206L));
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1774437392000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("work.dao.MemberDAO");
    _jspx_imports_classes.add("work.dto.MemberDTO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    // 세션에서 로그인한 내 아이디 가져오기
    String loggedInId = (String)session.getAttribute("userId");

    // 서블릿에서 넘겨준 리스트 데이터 수신
    ArrayList<MemberDTO> list = (ArrayList<MemberDTO>)request.getAttribute("memberList");
    if (list == null) {
        response.sendRedirect("AdminMemberList");
        return;
    }

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>직원 관리 - AlbaPass</title>\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Pretendard:wght@400;600;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/style.css\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" href=\"");
      out.print(request.getContextPath());
      out.write("/jlogo.png\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    // 1. 세션 변수 안전하게 가져오기
    String navUserId = (String)session.getAttribute("userId");
    String navUserName = (String)session.getAttribute("userName");
    String navUserRole = (String)session.getAttribute("userRole"); 
    String navUserStoreId = (String)session.getAttribute("userStoreId"); 

    // 2. 매장 목록 가져오기 (에러 방지를 위해 초기화)
    ArrayList<String[]> myStoreList = new ArrayList<>();
    
    // 로그인 상태일 때만 DB 조회
    if (navUserId != null) {
        try {
            MemberDAO navDao = new MemberDAO();
            myStoreList = navDao.getMyStoreList(navUserId);
        } catch (Exception e) {
            System.err.println("Navbar Store List Error: " + e.getMessage());
        }
    }

      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark shadow-sm fixed-top\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <a class=\"navbar-brand d-flex align-items-center\" href=\"");
      out.print(request.getContextPath());
      out.write("/default.jsp\">\r\n");
      out.write("            <img src=\"");
      out.print(request.getContextPath());
      out.write("/Emblem.png\" alt=\"AlbaPass 로고\" style=\"height: 36px; object-fit: contain;\">\r\n");
      out.write("        </a>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"d-flex align-items-center\">\r\n");
      out.write("            ");
 if(navUserId == null) { 
      out.write("\r\n");
      out.write("                <a href=\"login.jsp\" class=\"btn btn-outline-light btn-sm me-2\">로그인</a>\r\n");
      out.write("                <a href=\"register.jsp\" class=\"btn btn-primary btn-sm\">회원가입</a>\r\n");
      out.write("            ");
 } else { 
      out.write("\r\n");
      out.write("                <div class=\"text-white me-3 d-none d-md-block small\">\r\n");
      out.write("                    <span class=\"badge ");

                        if ("SA".equals(navUserRole)) { 
      out.write("bg-danger");

                        } else if ("A".equals(navUserRole)) { 
      out.write("bg-primary");

                        } else { 
      out.write("bg-warning text-dark");
 } 
      out.write(" me-1\">\r\n");
      out.write("                        ");
 if ("SA".equals(navUserRole)) { 
      out.write("전체관리자");

                        } else if ("A".equals(navUserRole)) { 
      out.write('점');
      out.write('장');

                        } else { 
      out.write('직');
      out.write('원');
 } 
      out.write("\r\n");
      out.write("                    </span>\r\n");
      out.write("                    <strong>");
      out.print(navUserName);
      out.write("</strong>님\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                ");
 if (!"SA".equals(navUserRole)) { 
      out.write("\r\n");
      out.write("                <button class=\"btn btn-sm btn-outline-light me-2\" data-bs-toggle=\"modal\" data-bs-target=\"#changeStoreModal\">\r\n");
      out.write("                    <i class=\"fa-solid fa-rotate\"></i> 매장변경\r\n");
      out.write("                </button>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <form action=\"");
      out.print(request.getContextPath());
      out.write("/Logout\" method=\"post\" class=\"m-0\">\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-danger btn-sm\">로그아웃</button>\r\n");
      out.write("                </form>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<div class=\"modal fade\" id=\"changeStoreModal\" tabindex=\"-1\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog modal-sm modal-dialog-centered\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("                <h6 class=\"modal-title fw-bold\">접속 매장 선택</h6>\r\n");
      out.write("                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"></button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-body p-0\">\r\n");
      out.write("                <div class=\"list-group list-group-flush\">\r\n");
      out.write("                    ");
 if(myStoreList == null || myStoreList.isEmpty()) { 
      out.write("\r\n");
      out.write("                        <div class=\"p-4 text-center\">\r\n");
      out.write("                            <p class=\"text-muted small mb-2\">등록된 매장이 없습니다.</p>\r\n");
      out.write("                            <a href=\"MyPage\" class=\"btn btn-sm btn-primary\">매장 등록하기</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    ");
 } else { 
                        for(String[] s : myStoreList) { 
                            boolean isCurrent = s[0].equals(navUserStoreId);
                    
      out.write("\r\n");
      out.write("                        <button type=\"button\" onclick=\"changeStore('");
      out.print(s[0]);
      out.write("')\" \r\n");
      out.write("                                class=\"list-group-item list-group-item-action d-flex justify-content-between align-items-center py-3 ");
      out.print( isCurrent ? "bg-light fw-bold" : "" );
      out.write("\">\r\n");
      out.write("                            <span>");
      out.print(s[1]);
      out.write(" <small class=\"text-muted\">(");
      out.print(s[0]);
      out.write(")</small></span>\r\n");
      out.write("                            ");
 if(isCurrent) { 
      out.write("<i class=\"fa-solid fa-check text-primary\"></i>");
 } 
      out.write("\r\n");
      out.write("                        </button>\r\n");
      out.write("                    ");
 } } 
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-footer border-0\">\r\n");
      out.write("                <a href=\"MyPage\" class=\"btn btn-link btn-sm text-decoration-none text-muted mx-auto\">매장 추가/삭제 관리</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function changeStore(storeId) {\r\n");
      out.write("    if(!storeId) return;\r\n");
      out.write("    fetch('ChangeStore', {\r\n");
      out.write("        method: 'POST',\r\n");
      out.write("        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },\r\n");
      out.write("        body: 'storeId=' + encodeURIComponent(storeId)\r\n");
      out.write("    })\r\n");
      out.write("    .then(res => res.json())\r\n");
      out.write("    .then(data => {\r\n");
      out.write("        if(data.status === 'success') {\r\n");
      out.write("            alert(data.message);\r\n");
      out.write("            location.reload(); \r\n");
      out.write("        } else {\r\n");
      out.write("            alert(data.message);\r\n");
      out.write("        }\r\n");
      out.write("    })\r\n");
      out.write("    .catch(err => console.error('Error:', err));\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    body { padding-top: 70px; }\r\n");
      out.write("    .list-group-item-action:active { background-color: #f8f9fc; color: inherit; }\r\n");
      out.write("</style>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container mt-5 mb-5\">\r\n");
      out.write("    <div class=\"d-flex justify-content-between align-items-center mb-4\">\r\n");
      out.write("        <h3 class=\"fw-bold text-dark mb-0\"><i class=\"fa-solid fa-user-gear me-2 text-info\"></i>직원 관리</h3>\r\n");
      out.write("        <a href=\"default.jsp\" class=\"btn btn-outline-secondary btn-sm fw-bold px-3\">\r\n");
      out.write("            <i class=\"fa-solid fa-arrow-left me-1\"></i> 대시보드로 돌아가기\r\n");
      out.write("        </a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"card custom-card p-4 mb-4 shadow-sm border-0\">\r\n");
      out.write("        <div class=\"input-group\">\r\n");
      out.write("            <span class=\"input-group-text bg-white border-end-0\"><i class=\"fa-solid fa-magnifying-glass text-muted\"></i></span>\r\n");
      out.write("            <input type=\"text\" id=\"searchInput\" class=\"form-control border-start-0 ps-0\" placeholder=\"이름이나 전화번호로 직원을 검색하세요...\" oninput=\"filterTable()\">\r\n");
      out.write("            <button class=\"btn btn-primary px-4 fw-bold\" type=\"button\" onclick=\"filterTable()\">\r\n");
      out.write("                <i class=\"fa-solid fa-magnifying-glass me-1\"></i> 검색\r\n");
      out.write("            </button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"card custom-card p-0 overflow-hidden shadow-sm border-0\">\r\n");
      out.write("        <div class=\"table-responsive\">\r\n");
      out.write("            <table class=\"table custom-table mb-0 align-middle\" id=\"memberTable\">\r\n");
      out.write("                <thead class=\"table-light\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th class=\"ps-4\">이름</th>\r\n");
      out.write("                        <th>전화번호</th>\r\n");
      out.write("                        <th>역할 / 시급</th>\r\n");
      out.write("                        <th>근무 요일</th>\r\n");
      out.write("                        <th class=\"text-center\">관리</th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("                <tbody>\r\n");
      out.write("                    ");
 if (list.isEmpty()) { 
      out.write("\r\n");
      out.write("                        <tr><td colspan='5' class='text-center text-muted py-5'>현재 등록된 직원이 없습니다.</td></tr>\r\n");
      out.write("                    ");
 } else {
                        for (MemberDTO m : list) { 
                            boolean isSelf = m.getId().equals(loggedInId);
                            boolean isAdmin = "A".equals(m.getRole());
                    
      out.write("\r\n");
      out.write("                        <tr ");
      out.print( isSelf ? "class='table-info-subtle'" : "" );
      out.write(">\r\n");
      out.write("                            <td class=\"ps-4\">\r\n");
      out.write("                                <span class=\"fw-bold text-dark\">");
      out.print(m.getName());
      out.write("</span>\r\n");
      out.write("                                ");
 if (isAdmin) { 
      out.write("\r\n");
      out.write("								    <span class=\"badge bg-primary ms-1\" style=\"font-size: 0.7rem;\">점장</span>\r\n");
      out.write("								");
 } else { 
      out.write("\r\n");
      out.write("								    <span class=\"badge bg-warning text-dark ms-1\" style=\"font-size: 0.7rem;\">직원</span>\r\n");
      out.write("								");
 } 
      out.write("\r\n");
      out.write("                                ");
 if (isSelf) { 
      out.write("\r\n");
      out.write("                                    <span class=\"badge bg-dark text-white ms-1\" style=\"font-size: 0.7rem;\">나</span>\r\n");
      out.write("                                ");
 } 
      out.write("\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td class=\"text-muted\">");
      out.print(m.getPhone());
      out.write("</td>\r\n");
      out.write("                            <td style=\"min-width:200px;\">\r\n");
      out.write("                                <div class=\"d-flex align-items-center gap-2\">\r\n");
      out.write("                                    <select class=\"form-select form-select-sm role-select\"\r\n");
      out.write("                                        id=\"roleSelect-");
      out.print(m.getId());
      out.write("\"\r\n");
      out.write("                                        onchange=\"assignRole('");
      out.print(m.getId());
      out.write("', this)\"\r\n");
      out.write("                                        data-current=\"");
      out.print(m.getRoleId());
      out.write("\"\r\n");
      out.write("                                        style=\"max-width:160px;\">\r\n");
      out.write("                                        <option value=\"0\">-- 역할 미지정 --</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                    <small class=\"text-primary fw-bold text-nowrap\" id=\"wage-");
      out.print(m.getId());
      out.write("\">\r\n");
      out.write("                                        ");
      out.print(m.getHourlyWage() > 0 ? String.format("%,d", m.getHourlyWage()) + "원" : "-");
      out.write("\r\n");
      out.write("                                    </small>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td>\r\n");
      out.write("                                ");
 if (m.getWorkDays() != null && !m.getWorkDays().isEmpty()) {
                                    String[] days = m.getWorkDays().split(",");
                                    for (String day : days) { 
      out.write("\r\n");
      out.write("                                        <span class=\"badge bg-primary me-1\">");
      out.print(day.trim());
      out.write("</span>\r\n");
      out.write("                                    ");
 } 
      out.write("\r\n");
      out.write("                                ");
 } else { 
      out.write("\r\n");
      out.write("                                    <span class=\"text-muted small\">미정</span>\r\n");
      out.write("                                ");
 } 
      out.write("\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td class=\"text-center\">\r\n");
      out.write("                                <a href=\"AdminMemberUpdate?id=");
      out.print(m.getId());
      out.write("\" class=\"btn btn-sm btn-warning text-white fw-bold me-1\">\r\n");
      out.write("                                    <i class=\"fa-solid fa-pen\"></i> 수정\r\n");
      out.write("                                </a>\r\n");
      out.write("                                ");
      out.write("\r\n");
      out.write("                                ");
 if (!isSelf) { 
      out.write("\r\n");
      out.write("                                    <a href=\"javascript:void(0);\" onclick=\"removeStaff('");
      out.print(m.getId());
      out.write("', '");
      out.print(m.getName());
      out.write("')\" class=\"btn btn-sm btn-danger fw-bold\">\r\n");
      out.write("                                        <i class=\"fa-solid fa-user-minus\"></i> 제외\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                ");
 } else { 
      out.write("\r\n");
      out.write("                                    <button class=\"btn btn-sm btn-secondary fw-bold\" disabled>\r\n");
      out.write("                                        <i class=\"fa-solid fa-lock\"></i> 고정\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                ");
 } 
      out.write("\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    ");
  }
                       } 
      out.write("\r\n");
      out.write("                </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("// 페이지 로드 시 역할 목록 로드\r\n");
      out.write("document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("    loadRoleOptions();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("// 현재 매장의 역할 목록 로드 후 모든 드롭다운에 적용\r\n");
      out.write("async function loadRoleOptions() {\r\n");
      out.write("    try {\r\n");
      out.write("        const storeId = '");
      out.print((String)session.getAttribute("userStoreId"));
      out.write("';\r\n");
      out.write("        const res  = await fetch('GetRoles?storeId=' + encodeURIComponent(storeId));\r\n");
      out.write("        const data = await res.json();\r\n");
      out.write("\r\n");
      out.write("        if (data.status === 'success') {\r\n");
      out.write("            document.querySelectorAll('.role-select').forEach(function(select) {\r\n");
      out.write("                // 기존 옵션 유지하고 역할 추가\r\n");
      out.write("                const currentVal = select.dataset.current || '0';\r\n");
      out.write("                data.list.forEach(role => {\r\n");
      out.write("                    const opt = document.createElement('option');\r\n");
      out.write("                    opt.value = role.roleId;\r\n");
      out.write("                    opt.text  = role.roleName;\r\n");
      out.write("                    opt.dataset.wage = role.wage;\r\n");
      out.write("                    if (String(role.roleId) === String(currentVal)) opt.selected = true;\r\n");
      out.write("                    select.appendChild(opt);\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("    } catch (e) { console.error(e); }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// 역할 지정\r\n");
      out.write("async function assignRole(memId, select) {\r\n");
      out.write("    const roleId = select.value;\r\n");
      out.write("    const roleName = select.options[select.selectedIndex].text;\r\n");
      out.write("\r\n");
      out.write("    if (!confirm('\"' + roleName + '\" 역할을 지정하시겠습니까?')) {\r\n");
      out.write("        // 취소 시 원래 값으로 복원\r\n");
      out.write("        select.value = select.dataset.current || '0';\r\n");
      out.write("        return;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    const params = new URLSearchParams();\r\n");
      out.write("    params.append('memId', memId);\r\n");
      out.write("    params.append('roleId', roleId);\r\n");
      out.write("\r\n");
      out.write("    try {\r\n");
      out.write("        const res  = await fetch('RoleAssign', { method: 'POST', body: params });\r\n");
      out.write("        const data = await res.json();\r\n");
      out.write("\r\n");
      out.write("        if (data.status === 'success') {\r\n");
      out.write("            select.dataset.current = roleId;\r\n");
      out.write("            // 시급 업데이트\r\n");
      out.write("            const wageEl = document.getElementById('wage-' + memId);\r\n");
      out.write("            if (wageEl) {\r\n");
      out.write("                wageEl.innerText = data.wage > 0 ? data.wage.toLocaleString() + '원' : '-';\r\n");
      out.write("            }\r\n");
      out.write("            // 성공 토스트 (alert 대신 조용히)\r\n");
      out.write("            const badge = document.createElement('span');\r\n");
      out.write("            badge.className = 'badge bg-success ms-1';\r\n");
      out.write("            badge.innerText = '저장됨';\r\n");
      out.write("            wageEl.after(badge);\r\n");
      out.write("            setTimeout(() => badge.remove(), 2000);\r\n");
      out.write("        } else {\r\n");
      out.write("            alert(data.message);\r\n");
      out.write("            select.value = select.dataset.current || '0';\r\n");
      out.write("        }\r\n");
      out.write("    } catch (e) {\r\n");
      out.write("        alert('통신 오류가 발생했습니다.');\r\n");
      out.write("        select.value = select.dataset.current || '0';\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("    function filterTable() {\r\n");
      out.write("        let input = document.getElementById(\"searchInput\");\r\n");
      out.write("        let filter = input.value.toUpperCase();\r\n");
      out.write("        let table = document.getElementById(\"memberTable\");\r\n");
      out.write("        let tr = table.getElementsByTagName(\"tr\");\r\n");
      out.write("\r\n");
      out.write("        for (let i = 1; i < tr.length; i++) {\r\n");
      out.write("            let tdName = tr[i].getElementsByTagName(\"td\")[0]; \r\n");
      out.write("            let tdPhone = tr[i].getElementsByTagName(\"td\")[1]; \r\n");
      out.write("            \r\n");
      out.write("            if (tdName && tdPhone) {\r\n");
      out.write("                let name = tdName.textContent || tdName.innerText;\r\n");
      out.write("                let phone = tdPhone.textContent || tdPhone.innerText;\r\n");
      out.write("                \r\n");
      out.write("                tr[i].style.display = (name.toUpperCase().includes(filter) || phone.toUpperCase().includes(filter)) ? \"\" : \"none\";\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function removeStaff(id, name) {\r\n");
      out.write("        // 🚨 영구 삭제가 아닌 '매장 제외'임을 안내\r\n");
      out.write("        if (confirm(\"정말 '\" + name + \"' 직원을 현재 매장에서 제외하시겠습니까?\\n이 직원의 계정은 유지되지만, 현재 매장 리스트에서는 사라집니다.\")) {\r\n");
      out.write("            location.href = 'AdminMemberDelete?id=' + id;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<footer class=\"text-center py-5 text-muted bg-white mt-auto border-top no-print\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <p class=\"mb-1 fw-bold text-dark\">AlbaPass</p>\r\n");
      out.write("        <small>© 2026 AlbaPass Project. All rights reserved.</small>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
