/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2026-05-16 10:03:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import work.dao.MemberDAO;
import java.util.ArrayList;

public final class board_005fwrite_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/navbar.jsp", Long.valueOf(1777387128000L));
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1774437392000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("work.dao.MemberDAO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

    // 1. 보안 체크 (세션 확인 로직만 남깁니다)
    String userId = (String)session.getAttribute("userId");
    String userStoreId = (String)session.getAttribute("userStoreId");

    if(userId == null) {
        out.println("<script>alert('로그인이 필요합니다.'); location.href='login.jsp';</script>");
        return;
    }

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>글 쓰기 - AlbaPass</title>\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    \r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Pretendard:wght@400;600;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" href=\"");
      out.print(request.getContextPath());
      out.write("/jlogo.png\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    // 1. 세션 변수 안전하게 가져오기
    String navUserId = (String)session.getAttribute("userId");
    String navUserName = (String)session.getAttribute("userName");
    String navUserRole = (String)session.getAttribute("userRole"); 
    String navUserStoreId = (String)session.getAttribute("userStoreId"); 

    // 2. 매장 목록 가져오기 (에러 방지를 위해 초기화)
    ArrayList<String[]> myStoreList = new ArrayList<>();
    
    // 로그인 상태일 때만 DB 조회
    if (navUserId != null) {
        try {
            MemberDAO navDao = new MemberDAO();
            myStoreList = navDao.getMyStoreList(navUserId);
        } catch (Exception e) {
            System.err.println("Navbar Store List Error: " + e.getMessage());
        }
    }

      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark shadow-sm fixed-top\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <a class=\"navbar-brand d-flex align-items-center\" href=\"");
      out.print(request.getContextPath());
      out.write("/default.jsp\">\r\n");
      out.write("            <img src=\"");
      out.print(request.getContextPath());
      out.write("/Emblem.png\" alt=\"AlbaPass 로고\" style=\"height: 36px; object-fit: contain;\">\r\n");
      out.write("        </a>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"d-flex align-items-center\">\r\n");
      out.write("            ");
 if(navUserId == null) { 
      out.write("\r\n");
      out.write("                <a href=\"login.jsp\" class=\"btn btn-outline-light btn-sm me-2\">로그인</a>\r\n");
      out.write("                <a href=\"register.jsp\" class=\"btn btn-primary btn-sm\">회원가입</a>\r\n");
      out.write("            ");
 } else { 
      out.write("\r\n");
      out.write("                <div class=\"text-white me-3 d-none d-md-block small\">\r\n");
      out.write("                    <span class=\"badge ");

                        if ("SA".equals(navUserRole)) { 
      out.write("bg-danger");

                        } else if ("A".equals(navUserRole)) { 
      out.write("bg-primary");

                        } else { 
      out.write("bg-warning text-dark");
 } 
      out.write(" me-1\">\r\n");
      out.write("                        ");
 if ("SA".equals(navUserRole)) { 
      out.write("전체관리자");

                        } else if ("A".equals(navUserRole)) { 
      out.write('점');
      out.write('장');

                        } else { 
      out.write('직');
      out.write('원');
 } 
      out.write("\r\n");
      out.write("                    </span>\r\n");
      out.write("                    <strong>");
      out.print(navUserName);
      out.write("</strong>님\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <button class=\"btn btn-sm btn-outline-light me-2\" data-bs-toggle=\"modal\" data-bs-target=\"#changeStoreModal\">\r\n");
      out.write("                    <i class=\"fa-solid fa-rotate\"></i> 매장변경\r\n");
      out.write("                </button>\r\n");
      out.write("\r\n");
      out.write("                <form action=\"");
      out.print(request.getContextPath());
      out.write("/Logout\" method=\"post\" class=\"m-0\">\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-danger btn-sm\">로그아웃</button>\r\n");
      out.write("                </form>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<div class=\"modal fade\" id=\"changeStoreModal\" tabindex=\"-1\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog modal-sm modal-dialog-centered\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("                <h6 class=\"modal-title fw-bold\">접속 매장 선택</h6>\r\n");
      out.write("                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"></button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-body p-0\">\r\n");
      out.write("                <div class=\"list-group list-group-flush\">\r\n");
      out.write("                    ");
 if(myStoreList == null || myStoreList.isEmpty()) { 
      out.write("\r\n");
      out.write("                        <div class=\"p-4 text-center\">\r\n");
      out.write("                            <p class=\"text-muted small mb-2\">등록된 매장이 없습니다.</p>\r\n");
      out.write("                            <a href=\"MyPage\" class=\"btn btn-sm btn-primary\">매장 등록하기</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    ");
 } else { 
                        for(String[] s : myStoreList) { 
                            boolean isCurrent = s[0].equals(navUserStoreId);
                    
      out.write("\r\n");
      out.write("                        <button type=\"button\" onclick=\"changeStore('");
      out.print(s[0]);
      out.write("')\" \r\n");
      out.write("                                class=\"list-group-item list-group-item-action d-flex justify-content-between align-items-center py-3 ");
      out.print( isCurrent ? "bg-light fw-bold" : "" );
      out.write("\">\r\n");
      out.write("                            <span>");
      out.print(s[1]);
      out.write(" <small class=\"text-muted\">(");
      out.print(s[0]);
      out.write(")</small></span>\r\n");
      out.write("                            ");
 if(isCurrent) { 
      out.write("<i class=\"fa-solid fa-check text-primary\"></i>");
 } 
      out.write("\r\n");
      out.write("                        </button>\r\n");
      out.write("                    ");
 } } 
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-footer border-0\">\r\n");
      out.write("                <a href=\"MyPage\" class=\"btn btn-link btn-sm text-decoration-none text-muted mx-auto\">매장 추가/삭제 관리</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function changeStore(storeId) {\r\n");
      out.write("    if(!storeId) return;\r\n");
      out.write("    fetch('ChangeStore', {\r\n");
      out.write("        method: 'POST',\r\n");
      out.write("        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },\r\n");
      out.write("        body: 'storeId=' + encodeURIComponent(storeId)\r\n");
      out.write("    })\r\n");
      out.write("    .then(res => res.json())\r\n");
      out.write("    .then(data => {\r\n");
      out.write("        if(data.status === 'success') {\r\n");
      out.write("            alert(data.message);\r\n");
      out.write("            location.reload(); \r\n");
      out.write("        } else {\r\n");
      out.write("            alert(data.message);\r\n");
      out.write("        }\r\n");
      out.write("    })\r\n");
      out.write("    .catch(err => console.error('Error:', err));\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    body { padding-top: 70px; }\r\n");
      out.write("    .list-group-item-action:active { background-color: #f8f9fc; color: inherit; }\r\n");
      out.write("</style>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container my-5\" style=\"max-width: 700px;\">\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"text-center mb-5\">\r\n");
      out.write("        <h3 class=\"fw-bold text-dark mb-1\">\r\n");
      out.write("            <i class=\"fa-solid fa-pen-nib text-primary me-2\"></i>게시글 작성\r\n");
      out.write("        </h3>\r\n");
      out.write("        <p class=\"text-muted small\">매장 동료들과 공유할 소중한 의견을 남겨주세요.</p>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"card custom-card border-0 shadow-sm p-4 p-md-5\">\r\n");
      out.write("        <form id=\"writeForm\">\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"mb-4\">\r\n");
      out.write("                <label class=\"form-label fw-bold text-secondary small\">제목</label>\r\n");
      out.write("                <input type=\"text\" name=\"title\" class=\"form-control form-control-lg border-2 shadow-none\" \r\n");
      out.write("                       placeholder=\"게시글 제목을 입력하세요\" required \r\n");
      out.write("                       style=\"border-radius: 12px; font-size: 1.1rem;\">\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"mb-4\">\r\n");
      out.write("                <label class=\"form-label fw-bold text-secondary small\">내용</label>\r\n");
      out.write("                <textarea name=\"content\" class=\"form-control border-2 shadow-none\" \r\n");
      out.write("                          placeholder=\"매장 동료들과 나누고 싶은 내용을 입력해 주세요.\" required \r\n");
      out.write("                          style=\"height: 300px; border-radius: 12px; resize: none;\"></textarea>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"mb-5\">\r\n");
      out.write("                <label class=\"form-label fw-bold text-secondary small\">파일 첨부 (이미지, PDF, ZIP 등)</label>\r\n");
      out.write("                <div class=\"input-group\">\r\n");
      out.write("                    <input type=\"file\" name=\"file\" class=\"form-control border-2\" id=\"inputFile\" style=\"border-radius: 12px;\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <p class=\"text-muted mt-2 small\">\r\n");
      out.write("                    <i class=\"fa-solid fa-circle-info me-1\"></i> 최대 100MB까지 업로드 가능합니다.\r\n");
      out.write("                </p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"d-flex gap-2\">\r\n");
      out.write("                <button type=\"button\" onclick=\"history.back()\" class=\"btn btn-light flex-fill py-3 fw-bold border\">\r\n");
      out.write("                    <i class=\"fa-solid fa-xmark me-1\"></i> 취소\r\n");
      out.write("                </button>\r\n");
      out.write("                <button type=\"submit\" class=\"btn btn-primary flex-fill py-3 fw-bold shadow-sm\" id=\"submitBtn\">\r\n");
      out.write("                    <i class=\"fa-solid fa-check me-1\"></i> 등록 완료\r\n");
      out.write("                </button>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<footer class=\"text-center py-5 text-muted bg-white mt-auto border-top no-print\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <p class=\"mb-1 fw-bold text-dark\">AlbaPass</p>\r\n");
      out.write("        <small>© 2026 AlbaPass Project. All rights reserved.</small>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("    const writeForm = document.getElementById('writeForm');\r\n");
      out.write("    const submitBtn = document.getElementById('submitBtn');\r\n");
      out.write("\r\n");
      out.write("    writeForm.addEventListener('submit', async function(e) {\r\n");
      out.write("        // 브라우저의 기본 제출(새로고침) 기능을 막습니다.\r\n");
      out.write("        e.preventDefault(); \r\n");
      out.write("\r\n");
      out.write("        // 🚨 다중 클릭 방지 UI: 버튼을 스피너로 바꾸고 클릭을 막습니다.\r\n");
      out.write("        const originalBtnHtml = submitBtn.innerHTML;\r\n");
      out.write("        submitBtn.innerHTML = '<span class=\"spinner-border spinner-border-sm me-2\" role=\"status\" aria-hidden=\"true\"></span>등록 중...';\r\n");
      out.write("        submitBtn.disabled = true;\r\n");
      out.write("\r\n");
      out.write("        try {\r\n");
      out.write("            // 🚨 핵심 수정 2: FormData를 사용하여 텍스트와 첨부파일을 한 덩어리로 묶습니다.\r\n");
      out.write("            const formData = new FormData(writeForm);\r\n");
      out.write("\r\n");
      out.write("            // 세션에 있는 아이디와 매장 정보를 백엔드(BoardWrite)로 같이 넘겨줍니다.\r\n");
      out.write("            formData.append('writerId', '");
      out.print(userId);
      out.write("');\r\n");
      out.write("            formData.append('storeId', '");
      out.print(userStoreId);
      out.write("');\r\n");
      out.write("\r\n");
      out.write("            // 🚨 핵심 수정 3: 새로 만든 자바 서블릿으로 통신을 쏩니다.\r\n");
      out.write("            const response = await fetch('BoardWrite', {\r\n");
      out.write("                method: 'POST',\r\n");
      out.write("                body: formData\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            const result = await response.json();\r\n");
      out.write("\r\n");
      out.write("            if (result.status === 'success') {\r\n");
      out.write("                alert('게시글이 성공적으로 등록되었습니다.');\r\n");
      out.write("                location.href = 'board_list.jsp?storeId=");
      out.print(userStoreId);
      out.write("';\r\n");
      out.write("            } else {\r\n");
      out.write("                alert('등록 실패: ' + result.message);\r\n");
      out.write("            }\r\n");
      out.write("        } catch (error) {\r\n");
      out.write("            console.error('Error:', error);\r\n");
      out.write("            alert('서버 통신 중 오류가 발생했습니다.');\r\n");
      out.write("        } finally {\r\n");
      out.write("            // 통신이 끝나면 버튼 상태를 원래대로 복구합니다.\r\n");
      out.write("            submitBtn.innerHTML = originalBtnHtml;\r\n");
      out.write("            submitBtn.disabled = false;\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
