/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2026-05-25 06:29:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import work.dao.MemberDAO;
import java.util.ArrayList;

public final class board_005fview_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/navbar.jsp", Long.valueOf(1779373637269L));
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1779373637201L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("work.dao.MemberDAO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');

    // 파라미터 체크 및 현재 세션 정보 가져오기
    String id = request.getParameter("id");
    if (id == null) {
        response.sendRedirect("board_list.jsp");
        return;
    }
    
    String currentUserId = (String)session.getAttribute("userId");
    
    // 세션에서 사용자의 소속 매장 ID 가져오기 (세션 만료 대비 파라미터 백업)
    String userStoreId = (String)session.getAttribute("userStoreId");
    if (userStoreId == null) userStoreId = request.getParameter("storeId"); 

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>게시글 보기 - AlbaPass</title>\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    \n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Pretendard:wght@400;600;700&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" href=\"");
      out.print(request.getContextPath());
      out.write("/jlogo.png\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/style.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write('\n');
      out.write('\n');

    // 1. 세션 변수 안전하게 가져오기
    String navUserId = (String)session.getAttribute("userId");
    String navUserName = (String)session.getAttribute("userName");
    String navUserRole = (String)session.getAttribute("userRole"); 
    String navUserStoreId = (String)session.getAttribute("userStoreId"); 

    // 2. 매장 목록 가져오기 (에러 방지를 위해 초기화)
    ArrayList<String[]> myStoreList = new ArrayList<>();
    
    // 로그인 상태일 때만 DB 조회
    if (navUserId != null) {
        try {
            MemberDAO navDao = new MemberDAO();
            myStoreList = navDao.getMyStoreList(navUserId);
        } catch (Exception e) {
            System.err.println("Navbar Store List Error: " + e.getMessage());
        }
    }

      out.write("\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark shadow-sm fixed-top\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <a class=\"navbar-brand d-flex align-items-center\" href=\"");
      out.print(request.getContextPath());
      out.write("/default.jsp\">\n");
      out.write("            <img src=\"");
      out.print(request.getContextPath());
      out.write("/Emblem.png\" alt=\"AlbaPass 로고\" style=\"height: 36px; object-fit: contain;\">\n");
      out.write("        </a>\n");
      out.write("        \n");
      out.write("        <div class=\"d-flex align-items-center\">\n");
      out.write("            ");
 if(navUserId == null) { 
      out.write("\n");
      out.write("                <a href=\"login.jsp\" class=\"btn btn-outline-light btn-sm me-2\">로그인</a>\n");
      out.write("                <a href=\"register.jsp\" class=\"btn btn-primary btn-sm\">회원가입</a>\n");
      out.write("            ");
 } else { 
      out.write("\n");
      out.write("                <div class=\"text-white me-3 d-none d-md-block small\">\n");
      out.write("                    <span class=\"badge ");

                        if ("SA".equals(navUserRole)) { 
      out.write("bg-danger");

                        } else if ("A".equals(navUserRole)) { 
      out.write("bg-primary");

                        } else { 
      out.write("bg-warning text-dark");
 } 
      out.write(" me-1\">\n");
      out.write("                        ");
 if ("SA".equals(navUserRole)) { 
      out.write("전체관리자");

                        } else if ("A".equals(navUserRole)) { 
      out.write('점');
      out.write('장');

                        } else { 
      out.write('직');
      out.write('원');
 } 
      out.write("\n");
      out.write("                    </span>\n");
      out.write("                    <strong>");
      out.print(navUserName);
      out.write("</strong>님\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                ");
 if (!"SA".equals(navUserRole)) { 
      out.write("\n");
      out.write("                ");
 if (navUserStoreId != null && !navUserStoreId.isEmpty()) { 
      out.write("\n");
      out.write("                <span class=\"text-white-50 small me-2 d-none d-md-block\">\n");
      out.write("                    <i class=\"fa-solid fa-store me-1\"></i>");
      out.print(navUserStoreId);
      out.write("\n");
      out.write("                </span>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("                <button class=\"btn btn-sm btn-outline-light me-2\" data-bs-toggle=\"modal\" data-bs-target=\"#changeStoreModal\">\n");
      out.write("                    <i class=\"fa-solid fa-rotate\"></i> 매장변경\n");
      out.write("                </button>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("                <form action=\"");
      out.print(request.getContextPath());
      out.write("/Logout\" method=\"post\" class=\"m-0\">\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-danger btn-sm\">로그아웃</button>\n");
      out.write("                </form>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("<div class=\"modal fade\" id=\"changeStoreModal\" tabindex=\"-1\" aria-hidden=\"true\">\n");
      out.write("    <div class=\"modal-dialog modal-sm modal-dialog-centered\">\n");
      out.write("        <div class=\"modal-content\">\n");
      out.write("            <div class=\"modal-header\">\n");
      out.write("                <h6 class=\"modal-title fw-bold\">접속 매장 선택</h6>\n");
      out.write("                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"></button>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"modal-body p-0\">\n");
      out.write("                <div class=\"list-group list-group-flush\">\n");
      out.write("                    ");
 if(myStoreList == null || myStoreList.isEmpty()) { 
      out.write("\n");
      out.write("                        <div class=\"p-4 text-center\">\n");
      out.write("                            <p class=\"text-muted small mb-2\">등록된 매장이 없습니다.</p>\n");
      out.write("                            <a href=\"MyPage\" class=\"btn btn-sm btn-primary\">매장 등록하기</a>\n");
      out.write("                        </div>\n");
      out.write("                    ");
 } else { 
                        for(String[] s : myStoreList) { 
                            boolean isCurrent = s[0].equals(navUserStoreId);
                    
      out.write("\n");
      out.write("                        <button type=\"button\" onclick=\"changeStore('");
      out.print(s[0]);
      out.write("')\" \n");
      out.write("                                class=\"list-group-item list-group-item-action d-flex justify-content-between align-items-center py-3 ");
      out.print( isCurrent ? "bg-light fw-bold" : "" );
      out.write("\">\n");
      out.write("                            <span>");
      out.print(s[1]);
      out.write(" <small class=\"text-muted\">(");
      out.print(s[0]);
      out.write(")</small></span>\n");
      out.write("                            ");
 if(isCurrent) { 
      out.write("<i class=\"fa-solid fa-check text-primary\"></i>");
 } 
      out.write("\n");
      out.write("                        </button>\n");
      out.write("                    ");
 } } 
      out.write("\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"modal-footer border-0\">\n");
      out.write("                <a href=\"MyPage\" class=\"btn btn-link btn-sm text-decoration-none text-muted mx-auto\">매장 추가/삭제 관리</a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("function changeStore(storeId) {\n");
      out.write("    if(!storeId) return;\n");
      out.write("    fetch('ChangeStore', {\n");
      out.write("        method: 'POST',\n");
      out.write("        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },\n");
      out.write("        body: 'storeId=' + encodeURIComponent(storeId)\n");
      out.write("    })\n");
      out.write("    .then(res => res.json())\n");
      out.write("    .then(data => {\n");
      out.write("        if(data.status === 'success') {\n");
      out.write("            showToast(data.message, data.status === 'success' ? 'success' : 'danger');\n");
      out.write("            location.reload(); \n");
      out.write("        } else {\n");
      out.write("            showToast(data.message, data.status === 'success' ? 'success' : 'danger');\n");
      out.write("        }\n");
      out.write("    })\n");
      out.write("    .catch(err => console.error('Error:', err));\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("    body { padding-top: 70px; }\n");
      out.write("    .list-group-item-action:active { background-color: #f8f9fc; color: inherit; }\n");
      out.write("</style>");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"container my-5\" style=\"max-width: 900px;\">\n");
      out.write("    \n");
      out.write("    <div class=\"d-flex justify-content-between align-items-center mb-4\">\n");
      out.write("        <nav aria-label=\"breadcrumb\">\n");
      out.write("            <ol class=\"breadcrumb mb-0\">\n");
      out.write("                <li class=\"breadcrumb-item\"><a href=\"default.jsp\" class=\"text-primary\">홈</a></li>\n");
      out.write("                <li class=\"breadcrumb-item\"><a href=\"board_list.jsp?storeId=");
      out.print(userStoreId);
      out.write("\" class=\"text-primary\">소통 게시판</a></li>\n");
      out.write("                <li class=\"breadcrumb-item active\">상세 보기</li>\n");
      out.write("            </ol>\n");
      out.write("        </nav>\n");
      out.write("        <a href=\"board_list.jsp?storeId=");
      out.print(userStoreId);
      out.write("\" class=\"btn btn-outline-secondary btn-sm px-3 fw-bold\">\n");
      out.write("            <i class=\"fa-solid fa-list me-1\"></i> 목록으로\n");
      out.write("        </a>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div id=\"boardDetailContainer\" class=\"card custom-card border-0 shadow-sm overflow-hidden\">\n");
      out.write("        <div class=\"p-5 text-center text-muted\">\n");
      out.write("            <div class=\"spinner-border text-primary mb-3\" role=\"status\"></div>\n");
      out.write("            <p>게시글을 불러오는 중입니다...</p>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("<footer class=\"text-center py-5 text-muted bg-white mt-auto border-top no-print\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <p class=\"mb-1 fw-bold text-dark\">AlbaPass</p>\n");
      out.write("        <small>© 2026 AlbaPass Project. All rights reserved.</small>\n");
      out.write("    </div>\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"toast-container position-fixed bottom-0 end-0 p-3\" style=\"z-index: 9999;\">\n");
      out.write("    <div id=\"appToast\" class=\"toast align-items-center border-0 shadow\" role=\"alert\" aria-live=\"assertive\">\n");
      out.write("        <div class=\"d-flex\">\n");
      out.write("            <div class=\"toast-body fw-bold\" id=\"appToastMsg\">\n");
      out.write("                메시지\n");
      out.write("            </div>\n");
      out.write("            <button type=\"button\" class=\"btn-close btn-close-white me-2 m-auto\" data-bs-dismiss=\"toast\"></button>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("<script>\n");
      out.write("// 공통 토스트 함수\n");
      out.write("function showToast(message, type) {\n");
      out.write("    type = type || 'success'; // success, danger, warning, info\n");
      out.write("    const toast    = document.getElementById('appToast');\n");
      out.write("    const toastMsg = document.getElementById('appToastMsg');\n");
      out.write("\n");
      out.write("    // 색상 설정\n");
      out.write("    toast.className = 'toast align-items-center border-0 shadow text-white';\n");
      out.write("    if (type === 'success') toast.classList.add('bg-success');\n");
      out.write("    else if (type === 'danger')  toast.classList.add('bg-danger');\n");
      out.write("    else if (type === 'warning') toast.classList.add('bg-warning', 'text-dark');\n");
      out.write("    else if (type === 'info')    toast.classList.add('bg-primary');\n");
      out.write("\n");
      out.write("    toastMsg.innerText = message;\n");
      out.write("    const bsToast = new bootstrap.Toast(toast, { delay: 3000 });\n");
      out.write("    bsToast.show();\n");
      out.write("}\n");
      out.write("\n");
      out.write("// alert 대체 함수 (기존 코드와 호환)\n");
      out.write("function showAlert(message, type) {\n");
      out.write("    showToast(message, type || 'info');\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("document.addEventListener('DOMContentLoaded', function() {\n");
      out.write("    loadBoardDetail();\n");
      out.write("});\n");
      out.write("\n");
      out.write("async function loadBoardDetail() {\n");
      out.write("    const urlParams = new URLSearchParams(window.location.search);\n");
      out.write("    const postId = urlParams.get('id');\n");
      out.write("\n");
      out.write("    if (!postId) {\n");
      out.write("        showToast('게시글 번호를 찾을 수 없습니다.', 'warning');\n");
      out.write("        location.href = 'board_list.jsp';\n");
      out.write("        return;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    const currentUserId = '");
      out.print(currentUserId != null ? currentUserId : "");
      out.write("';\n");
      out.write("    const userStoreId = '");
      out.print(userStoreId != null ? userStoreId : "");
      out.write("'; \n");
      out.write("    const container = document.getElementById('boardDetailContainer');\n");
      out.write("\n");
      out.write("    try {\n");
      out.write("        // 🚨 핵심 설계 1: API 요청 주소를 자바 파일(@WebServlet(\"/BoardView\"))로 변경\n");
      out.write("        // 🚨 핵심 설계 2: 브라우저 캐시를 무시하기 위해 무작위 시간값(_nocache)을 지속 전달\n");
      out.write("        const response = await fetch(\"BoardView?id=\" + postId + \"&_nocache=\" + new Date().getTime());\n");
      out.write("        const result = await response.json();\n");
      out.write("\n");
      out.write("        if (result.status === 'success') {\n");
      out.write("            const data = result.data;\n");
      out.write("            \n");
      out.write("            // 🚨 핵심 설계 3: 톰캣 EL 태그 충돌 에러 방지를 위해 백틱(`)을 제거하고 순수 문자열 결합(+) 사용\n");
      out.write("            let htmlTemplate = \n");
      out.write("                '<div class=\"card-header bg-white border-bottom-0 p-4 p-md-5 pb-0\">' +\n");
      out.write("                    '<h2 class=\"fw-bold text-dark mb-3\">' + data.title + '</h2>' +\n");
      out.write("                    '<div class=\"d-flex justify-content-between align-items-center text-muted small border-bottom pb-4\">' +\n");
      out.write("                        '<div class=\"d-flex gap-3\">' +\n");
      out.write("                            '<span><i class=\"fa-solid fa-user-circle me-1\"></i>작성자: <strong>' + data.writer + '</strong></span>' +\n");
      out.write("                            '<span><i class=\"fa-regular fa-clock me-1\"></i>' + data.date + '</span>' +\n");
      out.write("                        '</div>' +\n");
      out.write("                    '</div>' +\n");
      out.write("                '</div>' +\n");
      out.write("                '<div class=\"card-body p-4 p-md-5 py-4\">' +\n");
      out.write("                    '<div class=\"post-content mb-5\" style=\"min-height: 250px; line-height: 1.8; white-space: pre-wrap; font-size: 1.05rem;\">' +\n");
      out.write("                        data.content +\n");
      out.write("                    '</div>';\n");
      out.write("\n");
      out.write("            if (data.fileName && data.fileName.trim() !== \"\") {\n");
      out.write("                htmlTemplate += \n");
      out.write("                    '<div class=\"bg-light rounded-4 p-4 border mt-5\">' +\n");
      out.write("                        '<h6 class=\"fw-bold text-dark mb-3\"><i class=\"fa-solid fa-paperclip me-2 text-primary\"></i>첨부파일</h6>' +\n");
      out.write("                        '<div class=\"d-flex align-items-center flex-wrap gap-3\">' +\n");
      out.write("                            '<a href=\"upload/' + data.fileName + '\" download=\"' + data.orgName + '\" class=\"btn btn-success fw-bold shadow-sm px-4 py-2 rounded-pill\">' +\n");
      out.write("                                '<i class=\"fa-solid fa-file-arrow-down me-2\"></i>' + data.orgName + ' 내려받기' +\n");
      out.write("                            '</a>' +\n");
      out.write("                        '</div>';\n");
      out.write("\n");
      out.write("                const ext = data.fileName.split('.').pop().toLowerCase();\n");
      out.write("                if (['jpg', 'jpeg', 'png', 'gif'].includes(ext)) {\n");
      out.write("                    htmlTemplate += \n");
      out.write("                        '<div class=\"mt-4 pt-4 border-top\">' +\n");
      out.write("                            '<p class=\"small text-muted mb-3\"><i class=\"fa-regular fa-image me-1\"></i>이미지 미리보기</p>' +\n");
      out.write("                            '<img src=\"upload/' + data.fileName + '\" class=\"img-fluid rounded-3 shadow-sm border\" alt=\"첨부 이미지\" style=\"max-height: 600px;\">' +\n");
      out.write("                        '</div>';\n");
      out.write("                }\n");
      out.write("                htmlTemplate += '</div>'; \n");
      out.write("            }\n");
      out.write("            htmlTemplate += '</div>'; \n");
      out.write("\n");
      out.write("            htmlTemplate += \n");
      out.write("                '<div class=\"card-footer bg-light border-top-0 p-4 text-center d-flex justify-content-center gap-2\">';\n");
      out.write("            \n");
      out.write("            if (currentUserId === data.writer) {\n");
      out.write("                htmlTemplate += \n");
      out.write("                    '<a href=\"BoardEdit?id=' + postId + '&storeId=' + userStoreId + '\" class=\"btn btn-outline-primary px-4 fw-bold\">수정하기</a>' +\n");
      out.write("                    '<a href=\"BoardDelete?id=' + postId + '&storeId=' + userStoreId + '\" class=\"btn btn-outline-danger px-4 fw-bold\" onclick=\"return confirm(\\'정말로 삭제하시겠습니까?\\');\">삭제하기</a>';\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            htmlTemplate += \n");
      out.write("                    '<a href=\"board_list.jsp?storeId=' + userStoreId + '\" class=\"btn btn-secondary px-4 fw-bold\">목록</a>' +\n");
      out.write("                '</div>';\n");
      out.write("\n");
      out.write("            container.innerHTML = htmlTemplate;\n");
      out.write("\n");
      out.write("        } else {\n");
      out.write("            container.innerHTML = \"<div class='p-5 text-center'><h3>글을 찾을 수 없습니다.</h3><p class='text-danger mt-3'>에러: \" + result.message + \"</p><a href='board_list.jsp?storeId=\" + userStoreId + \"' class='btn btn-primary mt-4'>목록으로</a></div>\";\n");
      out.write("        }\n");
      out.write("    } catch (error) {\n");
      out.write("        container.innerHTML = \"<div class='p-5 text-center text-danger'><h4>서버 통신 중 오류가 발생했습니다.</h4><p>\" + error.message + \"</p></div>\";\n");
      out.write("    }\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
