/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2026-05-30 05:13:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import work.dao.MemberDAO;
import work.dao.MemberDAO;
import java.util.ArrayList;

public final class qr_005fcheck_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/navbar.jsp", Long.valueOf(1780109437587L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("work.dao.MemberDAO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

    String userId = (String)session.getAttribute("userId");
    String userStoreId = (String)session.getAttribute("userStoreId");

    if (userId == null) {
        response.sendRedirect("login.jsp");
        return;
    }

    // 소속 매장 목록 조회
    MemberDAO qrDao = new MemberDAO();
    ArrayList<String[]> myStores = qrDao.getMyStoreList(userId);
    // 매장이 1개면 자동 선택
    if (myStores.size() == 1 && (userStoreId == null || userStoreId.isEmpty())) {
        userStoreId = myStores.get(0)[0];
        session.setAttribute("userStoreId", userStoreId);
    }
    boolean multiStore = myStores.size() > 1;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>QR 출퇴근 시뮬레이션 - AlbaPass</title>\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    \r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Pretendard:wght@400;600;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/style.css\">\r\n");
      out.write("	<link rel=\"icon\" type=\"image/png\" href=\"");
      out.print(request.getContextPath());
      out.write("/jlogo.png\">\r\n");
      out.write("    <style>\r\n");
      out.write("        body { background-color: #f8f9fc; font-family: 'Pretendard', sans-serif; }\r\n");
      out.write("        .qr-container { max-width: 500px; margin: 80px auto; }\r\n");
      out.write("        .scanner-box { \r\n");
      out.write("            border: 2px dashed #4e73df; \r\n");
      out.write("            border-radius: 20px; \r\n");
      out.write("            background-color: #fff;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("        .qr-input {\r\n");
      out.write("            font-size: 2rem;\r\n");
      out.write("            font-weight: 800;\r\n");
      out.write("            letter-spacing: 5px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-bottom: 3px solid #eaecf4;\r\n");
      out.write("            border-radius: 0;\r\n");
      out.write("            color: #4e73df;\r\n");
      out.write("            text-transform: uppercase; /* 소문자로 입력해도 대문자로 보이게 설정 */\r\n");
      out.write("        }\r\n");
      out.write("        .qr-input:focus {\r\n");
      out.write("            box-shadow: none;\r\n");
      out.write("            border-bottom-color: #4e73df;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write('\n');
      out.write('\n');

    // 1. 세션 변수 안전하게 가져오기
    String navUserId = (String)session.getAttribute("userId");
    String navUserName = (String)session.getAttribute("userName");
    String navUserRole = (String)session.getAttribute("userRole"); 
    String navUserStoreId = (String)session.getAttribute("userStoreId"); 

    // 2. 매장 목록 가져오기 (에러 방지를 위해 초기화)
    ArrayList<String[]> myStoreList = new ArrayList<>();
    
    // 로그인 상태일 때만 DB 조회
    if (navUserId != null) {
        try {
            MemberDAO navDao = new MemberDAO();
            myStoreList = navDao.getMyStoreList(navUserId);
        } catch (Exception e) {
            System.err.println("Navbar Store List Error: " + e.getMessage());
        }
    }

      out.write("\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark shadow-sm fixed-top\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <a class=\"navbar-brand d-flex align-items-center\" href=\"");
      out.print(request.getContextPath());
      out.write("/default.jsp\">\n");
      out.write("            <img src=\"");
      out.print(request.getContextPath());
      out.write("/Emblem.png\" alt=\"AlbaPass 로고\" style=\"height: 36px; object-fit: contain;\">\n");
      out.write("        </a>\n");
      out.write("        \n");
      out.write("        <div class=\"d-flex align-items-center\">\n");
      out.write("            ");
 if(navUserId == null) { 
      out.write("\n");
      out.write("                <a href=\"login.jsp\" class=\"btn btn-outline-light btn-sm me-2\">로그인</a>\n");
      out.write("                <a href=\"register.jsp\" class=\"btn btn-primary btn-sm\">회원가입</a>\n");
      out.write("            ");
 } else { 
      out.write("\n");
      out.write("                <div class=\"text-white me-3 d-none d-md-block small\">\n");
      out.write("                    <span class=\"badge ");

                        if ("SA".equals(navUserRole)) { 
      out.write("bg-danger");

                        } else if ("A".equals(navUserRole)) { 
      out.write("bg-primary");

                        } else { 
      out.write("bg-warning text-dark");
 } 
      out.write(" me-1\">\n");
      out.write("                        ");
 if ("SA".equals(navUserRole)) { 
      out.write("전체관리자");

                        } else if ("A".equals(navUserRole)) { 
      out.write('점');
      out.write('장');

                        } else { 
      out.write('직');
      out.write('원');
 } 
      out.write("\n");
      out.write("                    </span>\n");
      out.write("                    <strong>");
      out.print(navUserName);
      out.write("</strong>님\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                ");
 if (!"SA".equals(navUserRole)) { 
      out.write("\n");
      out.write("                ");
 if (navUserStoreId != null && !navUserStoreId.isEmpty()) { 
      out.write("\n");
      out.write("                <span class=\"text-white-50 small me-2 d-none d-md-block\">\n");
      out.write("                    <i class=\"fa-solid fa-store me-1\"></i>");
      out.print(navUserStoreId);
      out.write("\n");
      out.write("                </span>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("                <button class=\"btn btn-sm btn-outline-light me-2\" data-bs-toggle=\"modal\" data-bs-target=\"#changeStoreModal\">\n");
      out.write("                    <i class=\"fa-solid fa-rotate\"></i> 매장변경\n");
      out.write("                </button>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("                <form action=\"");
      out.print(request.getContextPath());
      out.write("/Logout\" method=\"post\" class=\"m-0\">\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-danger btn-sm\">로그아웃</button>\n");
      out.write("                </form>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("<div class=\"modal fade\" id=\"changeStoreModal\" tabindex=\"-1\" aria-hidden=\"true\">\n");
      out.write("    <div class=\"modal-dialog modal-sm modal-dialog-centered\">\n");
      out.write("        <div class=\"modal-content\">\n");
      out.write("            <div class=\"modal-header\">\n");
      out.write("                <h6 class=\"modal-title fw-bold\">접속 매장 선택</h6>\n");
      out.write("                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"></button>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"modal-body p-0\">\n");
      out.write("                <div class=\"list-group list-group-flush\">\n");
      out.write("                    ");
 if(myStoreList == null || myStoreList.isEmpty()) { 
      out.write("\n");
      out.write("                        <div class=\"p-4 text-center\">\n");
      out.write("                            <p class=\"text-muted small mb-2\">등록된 매장이 없습니다.</p>\n");
      out.write("                            <a href=\"MyPage\" class=\"btn btn-sm btn-primary\">매장 등록하기</a>\n");
      out.write("                        </div>\n");
      out.write("                    ");
 } else { 
                        for(String[] s : myStoreList) { 
                            boolean isCurrent = s[0].equals(navUserStoreId);
                    
      out.write("\n");
      out.write("                        <button type=\"button\" onclick=\"changeStore('");
      out.print(s[0]);
      out.write("')\" \n");
      out.write("                                class=\"list-group-item list-group-item-action d-flex justify-content-between align-items-center py-3 ");
      out.print( isCurrent ? "bg-light fw-bold" : "" );
      out.write("\">\n");
      out.write("                            <span>");
      out.print(s[1]);
      out.write(" <small class=\"text-muted\">(");
      out.print(s[0]);
      out.write(")</small></span>\n");
      out.write("                            ");
 if(isCurrent) { 
      out.write("<i class=\"fa-solid fa-check text-primary\"></i>");
 } 
      out.write("\n");
      out.write("                        </button>\n");
      out.write("                    ");
 } } 
      out.write("\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"modal-footer border-0\">\n");
      out.write("                <a href=\"StoreManage\" class=\"btn btn-link btn-sm text-decoration-none text-muted mx-auto\">매장 추가/삭제 관리</a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("function changeStore(storeId) {\n");
      out.write("    if(!storeId) return;\n");
      out.write("    fetch('ChangeStore', {\n");
      out.write("        method: 'POST',\n");
      out.write("        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },\n");
      out.write("        body: 'storeId=' + encodeURIComponent(storeId)\n");
      out.write("    })\n");
      out.write("    .then(res => res.json())\n");
      out.write("    .then(data => {\n");
      out.write("        if(data.status === 'success') {\n");
      out.write("            showToast(data.message, data.status === 'success' ? 'success' : 'danger');\n");
      out.write("            location.reload(); \n");
      out.write("        } else {\n");
      out.write("            showToast(data.message, data.status === 'success' ? 'success' : 'danger');\n");
      out.write("        }\n");
      out.write("    })\n");
      out.write("    .catch(err => console.error('Error:', err));\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("    body { padding-top: 70px; }\n");
      out.write("    .list-group-item-action:active { background-color: #f8f9fc; color: inherit; }\n");
      out.write("</style>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container qr-container\">\r\n");
      out.write("    <div class=\"card border-0 shadow-sm p-4 text-center\">\r\n");
      out.write("        <div class=\"mb-4\">\r\n");
      out.write("            <div class=\"icon-box bg-primary-subtle text-primary mx-auto mb-3\" style=\"width: 70px; height: 70px; border-radius: 50%; display: flex; align-items: center; justify-content: center;\">\r\n");
      out.write("                <i class=\"fa-solid fa-camera fa-2x\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("            <h4 class=\"fw-bold text-dark\">QR 출퇴근 인증</h4>\r\n");
      out.write("            <p class=\"text-muted small\">현재 접속한 매장 코드가 자동으로 입력되어 있습니다.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"scanner-box p-4 mb-4\">\r\n");
      out.write("            ");
 if (myStores.isEmpty()) { 
      out.write("\r\n");
      out.write("                <div class=\"text-center text-muted py-3\">\r\n");
      out.write("                    <i class=\"fa-solid fa-store-slash fa-2x mb-2 d-block\"></i>\r\n");
      out.write("                    <p class=\"mb-0 small\">소속된 매장이 없습니다.</p>\r\n");
      out.write("                    <a href=\"StoreManage\" class=\"btn btn-sm btn-primary mt-2\">매장 신청하기</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            ");
 } else { 
      out.write("\r\n");
      out.write("                ");
 if (multiStore) { 
      out.write("\r\n");
      out.write("                ");
      out.write("\r\n");
      out.write("                <div class=\"mb-4\">\r\n");
      out.write("                    <label class=\"form-label small fw-bold text-secondary\">근무 매장 선택</label>\r\n");
      out.write("                    <select id=\"qrInput\" class=\"form-select form-select-lg fw-bold text-primary text-center\">\r\n");
      out.write("                        ");
 for (String[] s : myStores) {
                            boolean sel = s[0].equals(userStoreId); 
      out.write("\r\n");
      out.write("                        <option value=\"");
      out.print(s[0]);
      out.write('"');
      out.write(' ');
      out.print(sel?"selected":"");
      out.write('>');
      out.print(s[1]);
      out.write(' ');
      out.write('(');
      out.print(s[0]);
      out.write(")</option>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    </select>\r\n");
      out.write("                </div>\r\n");
      out.write("                ");
 } else { 
      out.write("\r\n");
      out.write("                ");
      out.write("\r\n");
      out.write("                <input type=\"hidden\" id=\"qrInput\" value=\"");
      out.print(userStoreId != null ? userStoreId : "");
      out.write("\">\r\n");
      out.write("                <div class=\"mb-4 p-3 bg-light rounded-3 text-center\">\r\n");
      out.write("                    <div class=\"small text-muted mb-1\">근무 매장</div>\r\n");
      out.write("                    <div class=\"fw-bold text-primary fs-5\">\r\n");
      out.write("                        <i class=\"fa-solid fa-store me-2\"></i>\r\n");
      out.write("                        ");
      out.print(myStores.isEmpty() ? userStoreId : myStores.get(0)[1]);
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <div class=\"d-grid gap-2\">\r\n");
      out.write("                    <button onclick=\"processQr('IN')\" class=\"btn btn-primary py-3 fw-bold\">\r\n");
      out.write("                        <i class=\"fa-solid fa-right-to-bracket me-2\"></i>출근 처리하기\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <button onclick=\"processQr('OUT')\" class=\"btn btn-danger py-3 fw-bold\">\r\n");
      out.write("                        <i class=\"fa-solid fa-right-from-bracket me-2\"></i>퇴근 처리하기\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <a href=\"default.jsp\" class=\"btn btn-link text-decoration-none text-muted mt-3\">\r\n");
      out.write("            <i class=\"fa-solid fa-house me-1\"></i> 메인으로 돌아가기\r\n");
      out.write("        </a>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    async function processQr(type) {\r\n");
      out.write("        const storeId = document.getElementById(\"qrInput\").value.trim();\r\n");
      out.write("        \r\n");
      out.write("        if(!storeId) {\r\n");
      out.write("            alert(\"매장 코드를 입력해주세요.\");\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        const params = new URLSearchParams();\r\n");
      out.write("        params.append('storeId', storeId);\r\n");
      out.write("        params.append('type', type);\r\n");
      out.write("\r\n");
      out.write("        try {\r\n");
      out.write("            const response = await fetch('QrCheck', {\r\n");
      out.write("                method: 'POST',\r\n");
      out.write("                headers: { 'Content-Type': 'application/x-www-form-urlencoded' },\r\n");
      out.write("                body: params\r\n");
      out.write("            });\r\n");
      out.write("            \r\n");
      out.write("            const result = await response.json();\r\n");
      out.write("\r\n");
      out.write("            if(result.status === 'success') {\r\n");
      out.write("                alert(result.message);\r\n");
      out.write("                location.href = 'default.jsp';\r\n");
      out.write("            } else {\r\n");
      out.write("                alert(\"인증 실패: \" + result.message);\r\n");
      out.write("            }\r\n");
      out.write("        } catch (error) {\r\n");
      out.write("            alert(\"서버 통신 중 오류가 발생했습니다.\");\r\n");
      out.write("            console.error(error);\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
