/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2026-05-27 12:18:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>회원가입 - AlbaPass</title>\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    \n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Pretendard:wght@400;600;700&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/style.css\">\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" href=\"");
      out.print(request.getContextPath());
      out.write("/jlogo.png\">\n");
      out.write("    <style>\n");
      out.write("        body { \n");
      out.write("            background-color: #f8f9fc; \n");
      out.write("            font-family: 'Pretendard', sans-serif; \n");
      out.write("            min-height: 100vh; \n");
      out.write("            display: flex; \n");
      out.write("            flex-direction: column; \n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        main {\n");
      out.write("            flex: 1;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            padding: 40px 0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .register-card { \n");
      out.write("            max-width: 500px; \n");
      out.write("            margin: 0 auto; \n");
      out.write("            border: none; \n");
      out.write("            border-radius: 20px; \n");
      out.write("            box-shadow: 0 10px 30px rgba(0,0,0,0.08); \n");
      out.write("            background: white;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .form-label { font-size: 0.85rem; font-weight: 700; color: #4e73df; }\n");
      out.write("        .required-mark { color: #e74a3b; }\n");
      out.write("        .role-selector .btn-check:checked + .btn { background-color: #4e73df; color: white; border-color: #4e73df; }\n");
      out.write("        #adminCodeArea { display: none; transition: all 0.3s ease-in-out; }\n");
      out.write("        #adminNotice { display: none; }\n");
      out.write("        .hint-text { font-size: 11px; margin-top: 4px; display: block; }\n");
      out.write("        \n");
      out.write("        .logo-wrapper {\n");
      out.write("            display: inline-block;\n");
      out.write("            overflow: hidden;\n");
      out.write("            width: 240px;\n");
      out.write("            height: 100px;\n");
      out.write("            border-radius: 12px;\n");
      out.write("            background-color: #fff;\n");
      out.write("            transition: transform 0.3s ease;\n");
      out.write("        }\n");
      out.write("        .logo-wrapper:hover { transform: scale(1.02); }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "navbar.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("<main>\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"card register-card p-4 p-md-5\">\n");
      out.write("            <div class=\"text-center mb-4\">\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath());
      out.write("/default.jsp\" class=\"logo-wrapper mb-2\">\n");
      out.write("                    <img src=\"");
      out.print(request.getContextPath());
      out.write("/logo.png\" alt=\"AlbaPass 로고\" \n");
      out.write("                         style=\"width: 100%; height: 100%; object-fit: contain; transform: scale(1); transform-origin: center;\">\n");
      out.write("                </a>\n");
      out.write("                <h3 class=\"fw-bold text-dark mt-2\">회원가입</h3>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <form id=\"regForm\">\n");
      out.write("                <div class=\"mb-4 text-center\">\n");
      out.write("                    <div class=\"btn-group role-selector w-100\" role=\"group\">\n");
      out.write("                        <input type=\"radio\" class=\"btn-check\" name=\"role\" id=\"roleStaff\" value=\"S\" checked onclick=\"handleRoleChange('S')\">\n");
      out.write("                        <label class=\"btn btn-outline-primary py-2\" for=\"roleStaff\"><i class=\"fa-solid fa-user me-2\"></i>직원</label>\n");
      out.write("                        \n");
      out.write("                        <input type=\"radio\" class=\"btn-check\" name=\"role\" id=\"roleAdmin\" value=\"A\" onclick=\"handleRoleChange('A')\">\n");
      out.write("                        <label class=\"btn btn-outline-primary py-2\" for=\"roleAdmin\"><i class=\"fa-solid fa-user-tie me-2\"></i>관리자</label>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div id=\"adminNotice\" class=\"mb-3 p-3 bg-warning-subtle rounded-3\">\n");
      out.write("                    <i class=\"fa-solid fa-circle-info me-2 text-warning\"></i>\n");
      out.write("                    <small class=\"text-dark fw-bold\">점장 가입 신청 후 전체관리자 승인이 완료되면 로그인 가능합니다.</small>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"mb-3\">\n");
      out.write("                    <label class=\"form-label\">아이디 <span class=\"required-mark\">*</span></label>\n");
      out.write("                    <div class=\"input-group\">\n");
      out.write("                        <input type=\"text\" name=\"id\" id=\"inputId\" class=\"form-control\" placeholder=\"아이디 입력\" required\n");
      out.write("                            oninput=\"resetIdCheck()\">\n");
      out.write("                        <button type=\"button\" class=\"btn btn-outline-secondary fw-bold\" onclick=\"checkDuplicateId()\">\n");
      out.write("                            중복확인\n");
      out.write("                        </button>\n");
      out.write("                    </div>\n");
      out.write("                    <small id=\"idCheckMsg\" class=\"hint-text\"></small>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"row g-3 mb-3\">\n");
      out.write("                    <div class=\"col-6\">\n");
      out.write("                        <label class=\"form-label\">비밀번호 <span class=\"required-mark\">*</span></label>\n");
      out.write("                        <input type=\"password\" id=\"pw\" name=\"pw\" class=\"form-control\" placeholder=\"입력\" required onkeyup=\"checkPwMatch()\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-6\">\n");
      out.write("                        <label class=\"form-label\">비밀번호 확인 <span class=\"required-mark\">*</span></label>\n");
      out.write("                        <input type=\"password\" id=\"pwCheck\" class=\"form-control\" placeholder=\"재입력\" required onkeyup=\"checkPwMatch()\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-12 mt-1\">\n");
      out.write("                        <small id=\"pwMsg\" style=\"font-size: 11px;\"></small>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"row g-3 mb-3\">\n");
      out.write("                    <div class=\"col-6\">\n");
      out.write("                        <label class=\"form-label\">이름 <span class=\"required-mark\">*</span></label>\n");
      out.write("                        <input type=\"text\" name=\"name\" class=\"form-control\" placeholder=\"실명\" required>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-6\">\n");
      out.write("                        <label class=\"form-label\">전화번호 <span class=\"required-mark\">*</span></label>\n");
      out.write("                        <input type=\"text\" name=\"phone\" class=\"form-control\" placeholder=\"010-0000-0000\"\n");
      out.write("                            maxlength=\"13\" oninput=\"autoHyphen(this)\" required>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"mb-3\">\n");
      out.write("                    <label class=\"form-label\">생년월일 <span class=\"required-mark\">*</span></label>\n");
      out.write("                    <input type=\"date\" name=\"birth\" id=\"birth\" class=\"form-control\" required>\n");
      out.write("                    <small class=\"text-muted hint-text\">실제 생년월일을 입력해주세요.</small>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"mb-4\" id=\"storeWrap\">\n");
      out.write("                    <label class=\"form-label\" id=\"storeLabel\">소속 매장 <span class=\"text-muted\">(선택, 여러 개 가능)</span></label>\n");
      out.write("\n");
      out.write("                    ");
      out.write("\n");
      out.write("                    <div id=\"selectedStoreTags\" class=\"d-flex flex-wrap gap-2 mb-2\" style=\"min-height:32px;\"></div>\n");
      out.write("\n");
      out.write("                    <div class=\"input-group\">\n");
      out.write("                        <input type=\"text\" id=\"storeSearchInput\" class=\"form-control bg-white\"\n");
      out.write("                            placeholder=\"매장을 검색해서 선택하세요\" readonly>\n");
      out.write("                        <button class=\"btn btn-outline-primary fw-bold\" type=\"button\"\n");
      out.write("                            data-bs-toggle=\"modal\" data-bs-target=\"#storeSearchModal\">\n");
      out.write("                            <i class=\"fa-solid fa-magnifying-glass me-1\"></i>검색\n");
      out.write("                        </button>\n");
      out.write("                    </div>\n");
      out.write("                    <input type=\"hidden\" name=\"storeIds\" id=\"storeIdsHidden\">\n");
      out.write("                    <small id=\"storeHint\" class=\"text-muted hint-text\">없으면 나중에 매장 관리에서 신청 가능합니다.</small>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                ");
      out.write("\n");
      out.write("                <div id=\"storeWorkDaysContainer\" class=\"mb-4\"></div>\n");
      out.write("                <input type=\"hidden\" name=\"workDays\" id=\"workDaysHidden\">\n");
      out.write("                <input type=\"hidden\" name=\"storeWorkDays\" id=\"storeWorkDaysHidden\">\n");
      out.write("\n");
      out.write("                <button type=\"submit\" class=\"btn btn-primary w-100 py-3 fw-bold shadow-sm mb-3\">가입하기</button>\n");
      out.write("            </form>\n");
      out.write("\n");
      out.write("            <div class=\"text-center\">\n");
      out.write("                <a href=\"login.jsp\" class=\"small text-decoration-none text-muted\">이미 계정이 있으신가요? <strong>로그인</strong></a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</main>\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"modal fade\" id=\"storeSearchModal\" tabindex=\"-1\" aria-hidden=\"true\">\n");
      out.write("    <div class=\"modal-dialog modal-dialog-centered modal-md\">\n");
      out.write("        <div class=\"modal-content border-0 shadow\">\n");
      out.write("            <div class=\"modal-header border-0 pb-0\">\n");
      out.write("                <h5 class=\"modal-title fw-bold\">\n");
      out.write("                    <i class=\"fa-solid fa-store me-2 text-primary\"></i>매장 검색\n");
      out.write("                </h5>\n");
      out.write("                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"></button>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"modal-body\">\n");
      out.write("                <div class=\"input-group mb-3\">\n");
      out.write("                    <input type=\"text\" id=\"modalStoreKeyword\" class=\"form-control\"\n");
      out.write("                        placeholder=\"매장 이름 또는 코드 입력\"\n");
      out.write("                        oninput=\"searchStoreModal(this.value)\">\n");
      out.write("                    <button class=\"btn btn-primary fw-bold\" type=\"button\"\n");
      out.write("                        onclick=\"searchStoreModal(document.getElementById('modalStoreKeyword').value)\">\n");
      out.write("                        <i class=\"fa-solid fa-magnifying-glass\"></i>\n");
      out.write("                    </button>\n");
      out.write("                </div>\n");
      out.write("                <div id=\"modalStoreResult\">\n");
      out.write("                    <div class=\"text-center text-muted py-4 small\">\n");
      out.write("                        <i class=\"fa-solid fa-magnifying-glass fa-2x mb-2 d-block\"></i>\n");
      out.write("                        매장 이름이나 코드를 입력해서 검색하세요.\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("    // 생년월일 기본값: 오늘 날짜\n");
      out.write("    window.addEventListener('DOMContentLoaded', function() {\n");
      out.write("        var today = new Date();\n");
      out.write("        var yyyy = today.getFullYear();\n");
      out.write("        var mm = String(today.getMonth() + 1).padStart(2, '0');\n");
      out.write("        var dd = String(today.getDate()).padStart(2, '0');\n");
      out.write("        document.getElementById('birth').value = yyyy + '-' + mm + '-' + dd;\n");
      out.write("    });\n");
      out.write("\n");
      out.write("    function handleRoleChange(role) {\n");
      out.write("        var adminNotice = document.getElementById(\"adminNotice\");\n");
      out.write("        var storeLabel  = document.getElementById(\"storeLabel\");\n");
      out.write("        var storeWrap   = document.getElementById(\"storeWrap\");\n");
      out.write("        var storeHint   = document.getElementById(\"storeHint\");\n");
      out.write("\n");
      out.write("        if (role === 'A') {\n");
      out.write("            adminNotice.style.display = \"block\";\n");
      out.write("            storeWrap.style.display   = \"none\";\n");
      out.write("            selectedStores = [];\n");
      out.write("            document.getElementById('storeIdsHidden').value = \"\";\n");
      out.write("            document.getElementById('selectedStoreTags').innerHTML = \"\";\n");
      out.write("            document.getElementById('storeWorkDaysContainer').innerHTML = \"\";\n");
      out.write("            document.getElementById('storeWorkDaysHidden').value = \"\";\n");
      out.write("            document.getElementById('workDaysHidden').value = \"\";\n");
      out.write("        } else {\n");
      out.write("            adminNotice.style.display = \"none\";\n");
      out.write("            storeWrap.style.display   = \"block\";\n");
      out.write("            storeLabel.innerHTML      = '소속 매장 <span class=\"text-muted\">(선택)</span>';\n");
      out.write("            storeHint.innerText       = \"없으면 나중에 매장 관리에서 신청 가능합니다.\";\n");
      out.write("            storeHint.className       = \"text-muted hint-text\";\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function autoHyphen(input) {\n");
      out.write("        var val = input.value.replace(/[^0-9]/g, '');\n");
      out.write("        if (val.length <= 3) {\n");
      out.write("            input.value = val;\n");
      out.write("        } else if (val.length <= 7) {\n");
      out.write("            input.value = val.slice(0, 3) + '-' + val.slice(3);\n");
      out.write("        } else {\n");
      out.write("            input.value = val.slice(0, 3) + '-' + val.slice(3, 7) + '-' + val.slice(7, 11);\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    var idChecked = false;\n");
      out.write("\n");
      out.write("    async function checkDuplicateId() {\n");
      out.write("        var id = document.getElementById('inputId').value.trim();\n");
      out.write("        var msgEl = document.getElementById('idCheckMsg');\n");
      out.write("\n");
      out.write("        if (!id) {\n");
      out.write("            msgEl.className = 'hint-text text-danger';\n");
      out.write("            msgEl.innerText = '아이디를 입력해주세요.';\n");
      out.write("            return;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        try {\n");
      out.write("            var res  = await fetch('CheckId?id=' + encodeURIComponent(id));\n");
      out.write("            var data = await res.json();\n");
      out.write("\n");
      out.write("            if (data.status === 'available') {\n");
      out.write("                msgEl.className = 'hint-text text-success fw-bold';\n");
      out.write("                msgEl.innerText = '✓ ' + data.message;\n");
      out.write("                idChecked = true;\n");
      out.write("            } else {\n");
      out.write("                msgEl.className = 'hint-text text-danger fw-bold';\n");
      out.write("                msgEl.innerText = '✗ ' + data.message;\n");
      out.write("                idChecked = false;\n");
      out.write("            }\n");
      out.write("        } catch (e) {\n");
      out.write("            msgEl.className = 'hint-text text-danger';\n");
      out.write("            msgEl.innerText = '서버 오류가 발생했습니다.';\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function resetIdCheck() {\n");
      out.write("        idChecked = false;\n");
      out.write("        var msgEl = document.getElementById('idCheckMsg');\n");
      out.write("        msgEl.innerText = '';\n");
      out.write("        msgEl.className = 'hint-text';\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    var regSearchTimer = null;\n");
      out.write("\n");
      out.write("    async function searchStoreModal(keyword) {\n");
      out.write("        clearTimeout(regSearchTimer);\n");
      out.write("        var resultBox = document.getElementById('modalStoreResult');\n");
      out.write("\n");
      out.write("        if (!keyword || keyword.trim().length < 1) {\n");
      out.write("            resultBox.innerHTML = '<div class=\"text-center text-muted py-4 small\"><i class=\"fa-solid fa-magnifying-glass fa-2x mb-2 d-block\"></i>매장 이름이나 코드를 입력해서 검색하세요.</div>';\n");
      out.write("            return;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        regSearchTimer = setTimeout(async function() {\n");
      out.write("            try {\n");
      out.write("                var res  = await fetch('SearchStore?keyword=' + encodeURIComponent(keyword.trim()));\n");
      out.write("                var data = await res.json();\n");
      out.write("                resultBox.innerHTML = '';\n");
      out.write("\n");
      out.write("                if (data.status === 'success' && data.list.length > 0) {\n");
      out.write("                    var table = document.createElement('table');\n");
      out.write("                    table.className = 'table table-hover align-middle mb-0';\n");
      out.write("                    table.innerHTML = '<thead class=\"table-light\"><tr><th>매장 이름</th><th>매장 코드</th><th></th></tr></thead>';\n");
      out.write("                    var tbody = document.createElement('tbody');\n");
      out.write("\n");
      out.write("                    data.list.forEach(function(store) {\n");
      out.write("                        var tr = document.createElement('tr');\n");
      out.write("                        tr.style.cursor = 'pointer';\n");
      out.write("                        tr.innerHTML =\n");
      out.write("                            '<td class=\"fw-bold\">' + store.name + '</td>' +\n");
      out.write("                            '<td class=\"text-muted\">' + store.id + '</td>' +\n");
      out.write("                            '<td class=\"text-end\"><button type=\"button\" class=\"btn btn-sm btn-primary fw-bold\">선택</button></td>';\n");
      out.write("                        tr.onclick = function() { selectStoreReg(store.id, store.name); };\n");
      out.write("                        tbody.appendChild(tr);\n");
      out.write("                    });\n");
      out.write("\n");
      out.write("                    table.appendChild(tbody);\n");
      out.write("                    resultBox.appendChild(table);\n");
      out.write("                } else {\n");
      out.write("                    resultBox.innerHTML = '<div class=\"text-center text-muted py-4 small\"><i class=\"fa-solid fa-circle-xmark fa-2x mb-2 d-block text-danger\"></i>검색 결과가 없습니다.</div>';\n");
      out.write("                }\n");
      out.write("            } catch (e) {\n");
      out.write("                resultBox.innerHTML = '<div class=\"text-center text-muted py-3 small\">검색 중 오류가 발생했습니다.</div>';\n");
      out.write("            }\n");
      out.write("        }, 300);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    var selectedStores = [];\n");
      out.write("\n");
      out.write("    function selectStoreReg(id, name) {\n");
      out.write("        if (selectedStores.find(function(s) { return s.id === id; })) {\n");
      out.write("            showToast('이미 선택된 매장입니다.', 'warning');\n");
      out.write("            return;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        selectedStores.push({id: id, name: name});\n");
      out.write("        renderStoreTags();\n");
      out.write("\n");
      out.write("        var modal = bootstrap.Modal.getInstance(document.getElementById('storeSearchModal'));\n");
      out.write("        if (modal) modal.hide();\n");
      out.write("        document.getElementById('modalStoreKeyword').value = '';\n");
      out.write("        document.getElementById('modalStoreResult').innerHTML = '<div class=\"text-center text-muted py-4 small\"><i class=\"fa-solid fa-magnifying-glass fa-2x mb-2 d-block\"></i>매장 이름이나 코드를 입력해서 검색하세요.</div>';\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    // 선택된 매장 태그 + 요일 렌더링\n");
      out.write("    // ※ JSP EL 충돌 방지: 백틱(template literal) 대신 문자열 연결(+) 사용\n");
      out.write("    function renderStoreTags() {\n");
      out.write("        var tagContainer  = document.getElementById('selectedStoreTags');\n");
      out.write("        var daysContainer = document.getElementById('storeWorkDaysContainer');\n");
      out.write("        tagContainer.innerHTML  = '';\n");
      out.write("        daysContainer.innerHTML = '';\n");
      out.write("\n");
      out.write("        var allDays = ['월','화','수','목','금','토','일'];\n");
      out.write("\n");
      out.write("        selectedStores.forEach(function(store) {\n");
      out.write("            // 매장 태그\n");
      out.write("            var tag = document.createElement('span');\n");
      out.write("            tag.className = 'badge bg-primary d-flex align-items-center gap-1 px-3 py-2';\n");
      out.write("            tag.style.fontSize = '13px';\n");
      out.write("            tag.innerHTML = store.name + ' (' + store.id + ')' +\n");
      out.write("                '<button type=\"button\" class=\"btn-close btn-close-white ms-1\" ' +\n");
      out.write("                'style=\"font-size:10px;\" onclick=\"removeStore(\\'' + store.id + '\\')\"></button>';\n");
      out.write("            tagContainer.appendChild(tag);\n");
      out.write("\n");
      out.write("            // 요일 선택 섹션\n");
      out.write("            var section = document.createElement('div');\n");
      out.write("            section.className = 'p-3 bg-light rounded-3 mb-2';\n");
      out.write("            section.id = 'days-section-' + store.id;\n");
      out.write("\n");
      out.write("            // 요일 버튼 HTML (문자열 연결로 생성 - JSP EL 충돌 방지)\n");
      out.write("            var btnHtml = '';\n");
      out.write("            allDays.forEach(function(day) {\n");
      out.write("                var inputId = 'day-' + store.id + '-' + day;\n");
      out.write("                btnHtml +=\n");
      out.write("                    '<div class=\"m-0\">' +\n");
      out.write("                        '<input class=\"d-none store-day-check\" type=\"checkbox\"' +\n");
      out.write("                            ' id=\"' + inputId + '\"' +\n");
      out.write("                            ' value=\"' + day + '\"' +\n");
      out.write("                            ' data-store=\"' + store.id + '\"' +\n");
      out.write("                            ' onchange=\"updateStoreWorkDays()\">' +\n");
      out.write("                        '<label class=\"btn btn-sm btn-outline-primary fw-bold\"' +\n");
      out.write("                            ' style=\"width:38px;padding:6px 0;text-align:center;\"' +\n");
      out.write("                            ' for=\"' + inputId + '\">' + day + '</label>' +\n");
      out.write("                    '</div>';\n");
      out.write("            });\n");
      out.write("\n");
      out.write("            section.innerHTML =\n");
      out.write("                '<div class=\"d-flex align-items-center justify-content-between mb-2\">' +\n");
      out.write("                    '<small class=\"fw-bold text-dark\">' +\n");
      out.write("                        '<i class=\"fa-solid fa-store me-1 text-primary\"></i>' +\n");
      out.write("                        store.name + ' 근무 요일' +\n");
      out.write("                    '</small>' +\n");
      out.write("                    '<small class=\"text-muted\">선택 안 하면 협의 후 결정</small>' +\n");
      out.write("                '</div>' +\n");
      out.write("                '<div class=\"d-flex flex-nowrap gap-1\">' + btnHtml + '</div>';\n");
      out.write("\n");
      out.write("            daysContainer.appendChild(section);\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        if (selectedStores.length === 0) {\n");
      out.write("            daysContainer.innerHTML = '';\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        document.getElementById('storeIdsHidden').value = selectedStores.map(function(s) { return s.id; }).join(',');\n");
      out.write("        updateStoreWorkDays();\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    // 매장별 요일 → hidden input 업데이트\n");
      out.write("    // 형식: store01:월,화,수|store02:목,금\n");
      out.write("    function updateStoreWorkDays() {\n");
      out.write("        var result = selectedStores.map(function(store) {\n");
      out.write("            var checked = Array.from(\n");
      out.write("                document.querySelectorAll('.store-day-check[data-store=\"' + store.id + '\"]:checked')\n");
      out.write("            ).map(function(c) { return c.value; });\n");
      out.write("            return store.id + ':' + checked.join(',');\n");
      out.write("        }).join('|');\n");
      out.write("\n");
      out.write("        document.getElementById('storeWorkDaysHidden').value = result;\n");
      out.write("\n");
      out.write("        var firstStore = selectedStores[0];\n");
      out.write("        if (firstStore) {\n");
      out.write("            var firstChecked = Array.from(\n");
      out.write("                document.querySelectorAll('.store-day-check[data-store=\"' + firstStore.id + '\"]:checked')\n");
      out.write("            ).map(function(c) { return c.value; });\n");
      out.write("            document.getElementById('workDaysHidden').value = firstChecked.join(',');\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function removeStore(id) {\n");
      out.write("        selectedStores = selectedStores.filter(function(s) { return s.id !== id; });\n");
      out.write("        renderStoreTags();\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    document.getElementById('storeSearchModal').addEventListener('shown.bs.modal', function() {\n");
      out.write("        document.getElementById('modalStoreKeyword').focus();\n");
      out.write("    });\n");
      out.write("\n");
      out.write("    function checkPwMatch() {\n");
      out.write("        var pw = document.getElementById(\"pw\").value;\n");
      out.write("        var pwCheck = document.getElementById(\"pwCheck\").value;\n");
      out.write("        var msg = document.getElementById(\"pwMsg\");\n");
      out.write("        if (!pw || !pwCheck) { msg.innerText = \"\"; return; }\n");
      out.write("        if (pw === pwCheck) {\n");
      out.write("            msg.style.color = \"#1cc88a\";\n");
      out.write("            msg.innerText = \"✓ 비밀번호가 일치합니다.\";\n");
      out.write("        } else {\n");
      out.write("            msg.style.color = \"#e74a3b\";\n");
      out.write("            msg.innerText = \"✕ 비밀번호가 일치하지 않습니다.\";\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    document.getElementById('regForm').addEventListener('submit', function(e) {\n");
      out.write("        e.preventDefault();\n");
      out.write("\n");
      out.write("        if (!idChecked) {\n");
      out.write("            showToast('아이디 중복확인을 해주세요.', 'warning');\n");
      out.write("            document.getElementById('inputId').focus();\n");
      out.write("            return;\n");
      out.write("        }\n");
      out.write("        var pw = document.getElementById(\"pw\").value;\n");
      out.write("        var pwCheck = document.getElementById(\"pwCheck\").value;\n");
      out.write("        if (pw !== pwCheck) {\n");
      out.write("            showToast('비밀번호가 일치하지 않습니다.', 'danger');\n");
      out.write("            return;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        var formData = new URLSearchParams(new FormData(this));\n");
      out.write("\n");
      out.write("        var selectedRole = document.querySelector('input[name=\"role\"]:checked');\n");
      out.write("        if (selectedRole) {\n");
      out.write("            formData.set('role', selectedRole.value);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        fetch('Register', {\n");
      out.write("            method: 'POST',\n");
      out.write("            headers: { 'Content-Type': 'application/x-www-form-urlencoded' },\n");
      out.write("            body: formData\n");
      out.write("        })\n");
      out.write("        .then(function(res) { return res.json(); })\n");
      out.write("        .then(function(data) {\n");
      out.write("            if (data.status === 'success') {\n");
      out.write("                alert(data.message);\n");
      out.write("                location.href = 'login.jsp';\n");
      out.write("            } else {\n");
      out.write("                alert(data.message);\n");
      out.write("            }\n");
      out.write("        })\n");
      out.write("        .catch(function(err) { showToast('서버 통신 오류가 발생했습니다.', 'danger'); });\n");
      out.write("    });\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
