/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2026-05-30 01:45:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import work.dao.MemberDAO;
import java.util.ArrayList;

public final class role_005fmanage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/navbar.jsp", Long.valueOf(1780105504021L));
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1779373637201L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("work.dao.MemberDAO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

    String userRole = (String) session.getAttribute("userRole");
    String storeId  = (String) session.getAttribute("userStoreId");
    if (!"A".equals(userRole != null ? userRole.trim() : "")) {
        response.sendRedirect("login.jsp");
        return;
    }
    ArrayList<String[]> roleList = (ArrayList<String[]>) request.getAttribute("roleList");
    if (roleList == null) roleList = new ArrayList<>();

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>역할 관리 - AlbaPass</title>\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Pretendard:wght@400;600;700&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/style.css\">\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" href=\"");
      out.print(request.getContextPath());
      out.write("/jlogo.png\">\n");
      out.write("    <style>\n");
      out.write("        .wage-chip { display:inline-flex; flex-direction:column; align-items:center;\n");
      out.write("                     background:#f8f9fc; border-radius:10px; padding:6px 12px; min-width:80px; }\n");
      out.write("        .wage-chip .chip-label { font-size:10px; font-weight:700; margin-bottom:2px; }\n");
      out.write("        .wage-chip .chip-value { font-size:13px; font-weight:700; }\n");
      out.write("        .role-card { border:1px solid #e3e6f0; border-radius:12px; transition:box-shadow 0.2s; }\n");
      out.write("        .role-card:hover { box-shadow:0 4px 12px rgba(0,0,0,0.08); }\n");
      out.write("        .wage-input-clean { border:none; background:transparent; font-weight:700;\n");
      out.write("                            color:#4e73df; font-size:22px; width:130px; text-align:center; }\n");
      out.write("        .wage-input-clean:focus { outline:none; border-bottom:2px solid #4e73df; }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write('\n');
      out.write('\n');

    // 1. 세션 변수 안전하게 가져오기
    String navUserId = (String)session.getAttribute("userId");
    String navUserName = (String)session.getAttribute("userName");
    String navUserRole = (String)session.getAttribute("userRole"); 
    String navUserStoreId = (String)session.getAttribute("userStoreId"); 

    // 2. 매장 목록 가져오기 (에러 방지를 위해 초기화)
    ArrayList<String[]> myStoreList = new ArrayList<>();
    
    // 로그인 상태일 때만 DB 조회
    if (navUserId != null) {
        try {
            MemberDAO navDao = new MemberDAO();
            myStoreList = navDao.getMyStoreList(navUserId);
        } catch (Exception e) {
            System.err.println("Navbar Store List Error: " + e.getMessage());
        }
    }

      out.write("\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark shadow-sm fixed-top\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <a class=\"navbar-brand d-flex align-items-center\" href=\"");
      out.print(request.getContextPath());
      out.write("/default.jsp\">\n");
      out.write("            <img src=\"");
      out.print(request.getContextPath());
      out.write("/Emblem.png\" alt=\"AlbaPass 로고\" style=\"height: 36px; object-fit: contain;\">\n");
      out.write("        </a>\n");
      out.write("        \n");
      out.write("        <div class=\"d-flex align-items-center\">\n");
      out.write("            ");
 if(navUserId == null) { 
      out.write("\n");
      out.write("                <a href=\"login.jsp\" class=\"btn btn-outline-light btn-sm me-2\">로그인</a>\n");
      out.write("                <a href=\"register.jsp\" class=\"btn btn-primary btn-sm\">회원가입</a>\n");
      out.write("            ");
 } else { 
      out.write("\n");
      out.write("                <div class=\"text-white me-3 d-none d-md-block small\">\n");
      out.write("                    <span class=\"badge ");

                        if ("SA".equals(navUserRole)) { 
      out.write("bg-danger");

                        } else if ("A".equals(navUserRole)) { 
      out.write("bg-primary");

                        } else { 
      out.write("bg-warning text-dark");
 } 
      out.write(" me-1\">\n");
      out.write("                        ");
 if ("SA".equals(navUserRole)) { 
      out.write("전체관리자");

                        } else if ("A".equals(navUserRole)) { 
      out.write('점');
      out.write('장');

                        } else { 
      out.write('직');
      out.write('원');
 } 
      out.write("\n");
      out.write("                    </span>\n");
      out.write("                    <strong>");
      out.print(navUserName);
      out.write("</strong>님\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                ");
 if (!"SA".equals(navUserRole)) { 
      out.write("\n");
      out.write("                ");

                    // 현재 매장 이름 찾기
                    String navStoreName = navUserStoreId;
                    if (navUserStoreId != null && !navUserStoreId.isEmpty()) {
                        for (String[] s : myStoreList) {
                            if (s[0].equals(navUserStoreId)) { navStoreName = s[1]; break; }
                        }
                    }
                
      out.write("\n");
      out.write("                ");
 if (navUserStoreId != null && !navUserStoreId.isEmpty()) { 
      out.write("\n");
      out.write("                <button class=\"btn btn-sm me-2 d-none d-md-flex align-items-center gap-1 fw-bold\"\n");
      out.write("                    style=\"background:rgba(255,255,255,0.15); color:#fff; border:1.5px solid rgba(255,255,255,0.35); border-radius:20px; padding:4px 12px;\"\n");
      out.write("                    data-bs-toggle=\"modal\" data-bs-target=\"#changeStoreModal\">\n");
      out.write("                    <i class=\"fa-solid fa-store\" style=\"font-size:12px;\"></i>\n");
      out.write("                    <span style=\"font-size:13px;\">");
      out.print(navStoreName);
      out.write("</span>\n");
      out.write("                    <i class=\"fa-solid fa-chevron-down\" style=\"font-size:10px; opacity:0.7;\"></i>\n");
      out.write("                </button>\n");
      out.write("                ");
 } else { 
      out.write("\n");
      out.write("                <button class=\"btn btn-sm btn-outline-warning me-2 fw-bold d-none d-md-block\"\n");
      out.write("                    data-bs-toggle=\"modal\" data-bs-target=\"#changeStoreModal\">\n");
      out.write("                    <i class=\"fa-solid fa-store me-1\"></i>매장 선택\n");
      out.write("                </button>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("                ");
      out.write("\n");
      out.write("                <button class=\"btn btn-sm btn-outline-light me-2 d-md-none\"\n");
      out.write("                    data-bs-toggle=\"modal\" data-bs-target=\"#changeStoreModal\">\n");
      out.write("                    <i class=\"fa-solid fa-store\"></i>\n");
      out.write("                </button>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("                <form action=\"");
      out.print(request.getContextPath());
      out.write("/Logout\" method=\"post\" class=\"m-0\">\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-danger btn-sm\">로그아웃</button>\n");
      out.write("                </form>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("<div class=\"modal fade\" id=\"changeStoreModal\" tabindex=\"-1\" aria-hidden=\"true\">\n");
      out.write("    <div class=\"modal-dialog modal-sm modal-dialog-centered\">\n");
      out.write("        <div class=\"modal-content\">\n");
      out.write("            <div class=\"modal-header\">\n");
      out.write("                <h6 class=\"modal-title fw-bold\">접속 매장 선택</h6>\n");
      out.write("                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"></button>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"modal-body p-0\">\n");
      out.write("                <div class=\"list-group list-group-flush\">\n");
      out.write("                    ");
 if(myStoreList == null || myStoreList.isEmpty()) { 
      out.write("\n");
      out.write("                        <div class=\"p-4 text-center\">\n");
      out.write("                            <p class=\"text-muted small mb-2\">등록된 매장이 없습니다.</p>\n");
      out.write("                            <a href=\"MyPage\" class=\"btn btn-sm btn-primary\">매장 등록하기</a>\n");
      out.write("                        </div>\n");
      out.write("                    ");
 } else { 
                        for(String[] s : myStoreList) { 
                            boolean isCurrent = s[0].equals(navUserStoreId);
                    
      out.write("\n");
      out.write("                        <button type=\"button\" onclick=\"changeStore('");
      out.print(s[0]);
      out.write("')\" \n");
      out.write("                                class=\"list-group-item list-group-item-action d-flex justify-content-between align-items-center py-3 ");
      out.print( isCurrent ? "bg-light fw-bold" : "" );
      out.write("\">\n");
      out.write("                            <span>");
      out.print(s[1]);
      out.write(" <small class=\"text-muted\">(");
      out.print(s[0]);
      out.write(")</small></span>\n");
      out.write("                            ");
 if(isCurrent) { 
      out.write("<i class=\"fa-solid fa-check text-primary\"></i>");
 } 
      out.write("\n");
      out.write("                        </button>\n");
      out.write("                    ");
 } } 
      out.write("\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"modal-footer border-0\">\n");
      out.write("                <a href=\"MyPage\" class=\"btn btn-link btn-sm text-decoration-none text-muted mx-auto\">매장 추가/삭제 관리</a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("function changeStore(storeId) {\n");
      out.write("    if(!storeId) return;\n");
      out.write("    fetch('ChangeStore', {\n");
      out.write("        method: 'POST',\n");
      out.write("        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },\n");
      out.write("        body: 'storeId=' + encodeURIComponent(storeId)\n");
      out.write("    })\n");
      out.write("    .then(res => res.json())\n");
      out.write("    .then(data => {\n");
      out.write("        if(data.status === 'success') {\n");
      out.write("            showToast(data.message, data.status === 'success' ? 'success' : 'danger');\n");
      out.write("            location.reload(); \n");
      out.write("        } else {\n");
      out.write("            showToast(data.message, data.status === 'success' ? 'success' : 'danger');\n");
      out.write("        }\n");
      out.write("    })\n");
      out.write("    .catch(err => console.error('Error:', err));\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("    body { padding-top: 70px; }\n");
      out.write("    .list-group-item-action:active { background-color: #f8f9fc; color: inherit; }\n");
      out.write("</style>");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"container mt-5 mb-5\" style=\"max-width:760px;\">\n");
      out.write("    <div class=\"d-flex justify-content-between align-items-center mb-4\">\n");
      out.write("        <h3 class=\"fw-bold text-dark mb-0\">\n");
      out.write("            <i class=\"fa-solid fa-tags me-2 text-primary\"></i>역할 관리\n");
      out.write("        </h3>\n");
      out.write("        <a href=\"default.jsp\" class=\"btn btn-outline-secondary btn-sm fw-bold px-3\">\n");
      out.write("            <i class=\"fa-solid fa-arrow-left me-1\"></i> 대시보드로\n");
      out.write("        </a>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    ");
      out.write("\n");
      out.write("    <div class=\"card border-0 shadow-sm p-4 mb-4\" style=\"border-top:4px solid #4e73df !important;\">\n");
      out.write("        <h5 class=\"fw-bold mb-3\"><i class=\"fa-solid fa-plus-circle me-2 text-primary\"></i>새 역할 추가</h5>\n");
      out.write("        <div class=\"row g-3 align-items-end\">\n");
      out.write("            <div class=\"col-md-5\">\n");
      out.write("                <label class=\"form-label small fw-bold text-secondary\">역할 이름</label>\n");
      out.write("                <input type=\"text\" id=\"newRoleName\" class=\"form-control\" placeholder=\"예: 홀 직원\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-4\">\n");
      out.write("                <label class=\"form-label small fw-bold text-secondary\">기본 시급 (원/시)</label>\n");
      out.write("                <div class=\"input-group\">\n");
      out.write("                    <input type=\"number\" id=\"newWage\" class=\"form-control fw-bold\" placeholder=\"10030\" min=\"0\"\n");
      out.write("                        oninput=\"calcAutoWage()\">\n");
      out.write("                    <span class=\"input-group-text\">원</span>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-3 d-flex align-items-end\">\n");
      out.write("                <button type=\"button\" onclick=\"addRole()\" class=\"btn btn-primary fw-bold w-100 py-2\">\n");
      out.write("                    <i class=\"fa-solid fa-plus me-1\"></i>추가\n");
      out.write("                </button>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        ");
      out.write("\n");
      out.write("        <div class=\"d-flex gap-2 flex-wrap mt-3\" id=\"newWagePreview\" style=\"display:none!important;\">\n");
      out.write("        </div>\n");
      out.write("        <div class=\"d-flex gap-2 flex-wrap mt-3\" id=\"newWageChips\">\n");
      out.write("            <div class=\"wage-chip\">\n");
      out.write("                <span class=\"chip-label text-muted\">평일주간</span>\n");
      out.write("                <span class=\"chip-value text-dark\" id=\"prevBase\">-</span>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"wage-chip\">\n");
      out.write("                <span class=\"chip-label text-dark\">평일야간 ×1.5</span>\n");
      out.write("                <span class=\"chip-value text-dark\" id=\"prevNight\">-</span>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"wage-chip\">\n");
      out.write("                <span class=\"chip-label text-warning\">휴일주간 ×1.5</span>\n");
      out.write("                <span class=\"chip-value text-warning\" id=\"prevWeekend\">-</span>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"wage-chip\">\n");
      out.write("                <span class=\"chip-label text-danger\">휴일야간 ×2.0</span>\n");
      out.write("                <span class=\"chip-value text-danger\" id=\"prevWeekendNight\">-</span>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    ");
      out.write("\n");
      out.write("    <div class=\"card border-0 shadow-sm p-4\">\n");
      out.write("        <h5 class=\"fw-bold mb-3\"><i class=\"fa-solid fa-list me-2 text-muted\"></i>역할 목록</h5>\n");
      out.write("\n");
      out.write("        ");
 if (roleList.isEmpty()) { 
      out.write("\n");
      out.write("            <div class=\"text-center text-muted py-5\">\n");
      out.write("                <i class=\"fa-solid fa-tag fa-2x mb-2 d-block\"></i>\n");
      out.write("                <small>등록된 역할이 없습니다.</small>\n");
      out.write("            </div>\n");
      out.write("        ");
 } else { 
      out.write("\n");
      out.write("        <div class=\"d-flex flex-column gap-3\" id=\"roleListContainer\">\n");
      out.write("            ");
 for (String[] r : roleList) {
                int base  = Integer.parseInt(r[2]);
                int wwn   = r.length > 4 ? Integer.parseInt(r[4]) : (int)(base * 1.5);
                int wend  = r.length > 5 ? Integer.parseInt(r[5]) : (int)(base * 1.5);
                int wendn = r.length > 6 ? Integer.parseInt(r[6]) : (int)(base * 2.0);
            
      out.write("\n");
      out.write("            <div class=\"role-card p-3 px-4\" id=\"role-row-");
      out.print(r[0]);
      out.write("\">\n");
      out.write("                <div class=\"d-flex align-items-center justify-content-between flex-wrap gap-3\">\n");
      out.write("\n");
      out.write("                    ");
      out.write("\n");
      out.write("                    <div style=\"min-width:130px;\">\n");
      out.write("                        <div class=\"small text-muted fw-bold mb-1\">역할 이름</div>\n");
      out.write("                        <input type=\"text\" class=\"form-control form-control-sm fw-bold border-0 bg-light px-2\"\n");
      out.write("                            id=\"roleName-");
      out.print(r[0]);
      out.write("\" value=\"");
      out.print(r[1]);
      out.write("\" style=\"width:130px;\">\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    ");
      out.write("\n");
      out.write("                    <div class=\"text-center\">\n");
      out.write("                        <div class=\"small text-muted fw-bold mb-1\">기본 시급</div>\n");
      out.write("                        <div class=\"d-flex align-items-center gap-1\">\n");
      out.write("                            <input class=\"wage-input-clean\"\n");
      out.write("                                type=\"number\" id=\"roleWage-");
      out.print(r[0]);
      out.write("\" value=\"");
      out.print(r[2]);
      out.write("\"\n");
      out.write("                                oninput=\"updateAutoWage('");
      out.print(r[0]);
      out.write("', this.value)\">\n");
      out.write("                            <span class=\"text-muted small\">원</span>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"text-muted\" style=\"font-size:11px;\">월 160h: ");
      out.print(String.format("%,d", base*160));
      out.write("원</div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    ");
      out.write("\n");
      out.write("                    <div class=\"d-flex gap-2 flex-wrap\">\n");
      out.write("                        <div class=\"wage-chip\">\n");
      out.write("                            <span class=\"chip-label text-dark\">평일야간 ×1.5</span>\n");
      out.write("                            <span class=\"chip-value text-dark\" id=\"roleNightWage-");
      out.print(r[0]);
      out.write('"');
      out.write('>');
      out.print(String.format("%,d",wwn));
      out.write("원</span>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"wage-chip\">\n");
      out.write("                            <span class=\"chip-label text-warning\">휴일주간 ×1.5</span>\n");
      out.write("                            <span class=\"chip-value text-warning\" id=\"roleWeekendWage-");
      out.print(r[0]);
      out.write('"');
      out.write('>');
      out.print(String.format("%,d",wend));
      out.write("원</span>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"wage-chip\">\n");
      out.write("                            <span class=\"chip-label text-danger\">휴일야간 ×2.0</span>\n");
      out.write("                            <span class=\"chip-value text-danger\" id=\"roleWeekendNightWage-");
      out.print(r[0]);
      out.write('"');
      out.write('>');
      out.print(String.format("%,d",wendn));
      out.write("원</span>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    ");
      out.write("\n");
      out.write("                    <div class=\"d-flex gap-2\">\n");
      out.write("                        <button class=\"btn btn-sm btn-outline-primary fw-bold\"\n");
      out.write("                            onclick=\"editRole('");
      out.print(r[0]);
      out.write("')\">\n");
      out.write("                            <i class=\"fa-solid fa-check\"></i> 저장\n");
      out.write("                        </button>\n");
      out.write("                        <button class=\"btn btn-sm btn-outline-danger fw-bold\"\n");
      out.write("                            onclick=\"deleteRole('");
      out.print(r[0]);
      out.write("', '");
      out.print(r[1]);
      out.write("')\">\n");
      out.write("                            <i class=\"fa-solid fa-trash\"></i>\n");
      out.write("                        </button>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("        </div>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("<footer class=\"text-center py-5 text-muted bg-white mt-auto border-top no-print\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <p class=\"mb-1 fw-bold text-dark\">AlbaPass</p>\n");
      out.write("        <small>© 2026 AlbaPass Project. All rights reserved.</small>\n");
      out.write("    </div>\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"toast-container position-fixed bottom-0 end-0 p-3\" style=\"z-index: 9999;\">\n");
      out.write("    <div id=\"appToast\" class=\"toast align-items-center border-0 shadow\" role=\"alert\" aria-live=\"assertive\">\n");
      out.write("        <div class=\"d-flex\">\n");
      out.write("            <div class=\"toast-body fw-bold\" id=\"appToastMsg\">\n");
      out.write("                메시지\n");
      out.write("            </div>\n");
      out.write("            <button type=\"button\" class=\"btn-close btn-close-white me-2 m-auto\" data-bs-dismiss=\"toast\"></button>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("<script>\n");
      out.write("// 공통 토스트 함수\n");
      out.write("function showToast(message, type) {\n");
      out.write("    type = type || 'success'; // success, danger, warning, info\n");
      out.write("    const toast    = document.getElementById('appToast');\n");
      out.write("    const toastMsg = document.getElementById('appToastMsg');\n");
      out.write("\n");
      out.write("    // 색상 설정\n");
      out.write("    toast.className = 'toast align-items-center border-0 shadow text-white';\n");
      out.write("    if (type === 'success') toast.classList.add('bg-success');\n");
      out.write("    else if (type === 'danger')  toast.classList.add('bg-danger');\n");
      out.write("    else if (type === 'warning') toast.classList.add('bg-warning', 'text-dark');\n");
      out.write("    else if (type === 'info')    toast.classList.add('bg-primary');\n");
      out.write("\n");
      out.write("    toastMsg.innerText = message;\n");
      out.write("    const bsToast = new bootstrap.Toast(toast, { delay: 3000 });\n");
      out.write("    bsToast.show();\n");
      out.write("}\n");
      out.write("\n");
      out.write("// alert 대체 함수 (기존 코드와 호환)\n");
      out.write("function showAlert(message, type) {\n");
      out.write("    showToast(message, type || 'info');\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("<script>\n");
      out.write("function calcAutoWage() {\n");
      out.write("    var base = parseInt(document.getElementById('newWage').value) || 0;\n");
      out.write("    document.getElementById('prevBase').innerText         = base > 0 ? base.toLocaleString() + '원' : '-';\n");
      out.write("    document.getElementById('prevNight').innerText        = base > 0 ? Math.floor(base*1.5).toLocaleString() + '원' : '-';\n");
      out.write("    document.getElementById('prevWeekend').innerText      = base > 0 ? Math.floor(base*1.5).toLocaleString() + '원' : '-';\n");
      out.write("    document.getElementById('prevWeekendNight').innerText = base > 0 ? Math.floor(base*2.0).toLocaleString() + '원' : '-';\n");
      out.write("}\n");
      out.write("\n");
      out.write("function updateAutoWage(roleId, val) {\n");
      out.write("    var base = parseInt(val) || 0;\n");
      out.write("    var n  = document.getElementById('roleNightWage-'        + roleId);\n");
      out.write("    var w  = document.getElementById('roleWeekendWage-'      + roleId);\n");
      out.write("    var wn = document.getElementById('roleWeekendNightWage-' + roleId);\n");
      out.write("    if (n)  n.innerText  = base > 0 ? Math.floor(base*1.5).toLocaleString() + '원' : '-';\n");
      out.write("    if (w)  w.innerText  = base > 0 ? Math.floor(base*1.5).toLocaleString() + '원' : '-';\n");
      out.write("    if (wn) wn.innerText = base > 0 ? Math.floor(base*2.0).toLocaleString() + '원' : '-';\n");
      out.write("}\n");
      out.write("\n");
      out.write("async function addRole() {\n");
      out.write("    var roleName = document.getElementById('newRoleName').value.trim();\n");
      out.write("    var wage     = document.getElementById('newWage').value.trim();\n");
      out.write("    if (!roleName) { showToast('역할 이름을 입력해주세요.', 'warning'); return; }\n");
      out.write("    var params = new URLSearchParams();\n");
      out.write("    params.append('mode', 'add');\n");
      out.write("    params.append('roleName', roleName);\n");
      out.write("    params.append('wage', wage || '0');\n");
      out.write("    var res  = await fetch('RoleManage', { method:'POST', body:params });\n");
      out.write("    var data = await res.json();\n");
      out.write("    showToast(data.message, data.status === 'success' ? 'success' : 'danger');\n");
      out.write("    if (data.status === 'success') location.reload();\n");
      out.write("}\n");
      out.write("\n");
      out.write("async function editRole(roleId) {\n");
      out.write("    var roleName = document.getElementById('roleName-' + roleId).value.trim();\n");
      out.write("    var wage     = document.getElementById('roleWage-'  + roleId).value.trim();\n");
      out.write("    var params = new URLSearchParams();\n");
      out.write("    params.append('mode', 'edit');\n");
      out.write("    params.append('roleId', roleId);\n");
      out.write("    params.append('roleName', roleName);\n");
      out.write("    params.append('wage', wage || '0');\n");
      out.write("    var res  = await fetch('RoleManage', { method:'POST', body:params });\n");
      out.write("    var data = await res.json();\n");
      out.write("    showToast(data.message, data.status === 'success' ? 'success' : 'danger');\n");
      out.write("}\n");
      out.write("\n");
      out.write("async function deleteRole(roleId, roleName) {\n");
      out.write("    if (!confirm('[' + roleName + '] 역할을 삭제하시겠습니까?')) return;\n");
      out.write("    var params = new URLSearchParams();\n");
      out.write("    params.append('mode', 'delete');\n");
      out.write("    params.append('roleId', roleId);\n");
      out.write("    var res  = await fetch('RoleManage', { method:'POST', body:params });\n");
      out.write("    var data = await res.json();\n");
      out.write("    showToast(data.message, data.status === 'success' ? 'success' : 'danger');\n");
      out.write("    if (data.status === 'success') {\n");
      out.write("        var row = document.getElementById('role-row-' + roleId);\n");
      out.write("        if (row) row.remove();\n");
      out.write("    }\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
