/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2026-05-24 10:05:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import work.dao.MemberDAO;
import java.util.ArrayList;

public final class store_005fmanage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/navbar.jsp", Long.valueOf(1779373637269L));
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1779373637201L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("work.dao.MemberDAO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

    String userRole  = (String) session.getAttribute("userRole");
    String userId    = (String) session.getAttribute("userId");

    if (userId == null) {
        response.sendRedirect("login.jsp");
        return;
    }
    if (!"A".equals(userRole) && !"S".equals(userRole)) {
        response.sendRedirect("default.jsp");
        return;
    }

    ArrayList<String[]> myStores    = (ArrayList<String[]>) request.getAttribute("myStores");
    ArrayList<String[]> pendingJoins = (ArrayList<String[]>) request.getAttribute("pendingJoins");
    if (myStores     == null) myStores     = new ArrayList<>();
    if (pendingJoins == null) pendingJoins = new ArrayList<>();

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>매장 관리 - AlbaPass</title>\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Pretendard:wght@400;600;700&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/style.css\">\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" href=\"");
      out.print(request.getContextPath());
      out.write("/jlogo.png\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write('\n');
      out.write('\n');

    // 1. 세션 변수 안전하게 가져오기
    String navUserId = (String)session.getAttribute("userId");
    String navUserName = (String)session.getAttribute("userName");
    String navUserRole = (String)session.getAttribute("userRole"); 
    String navUserStoreId = (String)session.getAttribute("userStoreId"); 

    // 2. 매장 목록 가져오기 (에러 방지를 위해 초기화)
    ArrayList<String[]> myStoreList = new ArrayList<>();
    
    // 로그인 상태일 때만 DB 조회
    if (navUserId != null) {
        try {
            MemberDAO navDao = new MemberDAO();
            myStoreList = navDao.getMyStoreList(navUserId);
        } catch (Exception e) {
            System.err.println("Navbar Store List Error: " + e.getMessage());
        }
    }

      out.write("\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark shadow-sm fixed-top\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <a class=\"navbar-brand d-flex align-items-center\" href=\"");
      out.print(request.getContextPath());
      out.write("/default.jsp\">\n");
      out.write("            <img src=\"");
      out.print(request.getContextPath());
      out.write("/Emblem.png\" alt=\"AlbaPass 로고\" style=\"height: 36px; object-fit: contain;\">\n");
      out.write("        </a>\n");
      out.write("        \n");
      out.write("        <div class=\"d-flex align-items-center\">\n");
      out.write("            ");
 if(navUserId == null) { 
      out.write("\n");
      out.write("                <a href=\"login.jsp\" class=\"btn btn-outline-light btn-sm me-2\">로그인</a>\n");
      out.write("                <a href=\"register.jsp\" class=\"btn btn-primary btn-sm\">회원가입</a>\n");
      out.write("            ");
 } else { 
      out.write("\n");
      out.write("                <div class=\"text-white me-3 d-none d-md-block small\">\n");
      out.write("                    <span class=\"badge ");

                        if ("SA".equals(navUserRole)) { 
      out.write("bg-danger");

                        } else if ("A".equals(navUserRole)) { 
      out.write("bg-primary");

                        } else { 
      out.write("bg-warning text-dark");
 } 
      out.write(" me-1\">\n");
      out.write("                        ");
 if ("SA".equals(navUserRole)) { 
      out.write("전체관리자");

                        } else if ("A".equals(navUserRole)) { 
      out.write('점');
      out.write('장');

                        } else { 
      out.write('직');
      out.write('원');
 } 
      out.write("\n");
      out.write("                    </span>\n");
      out.write("                    <strong>");
      out.print(navUserName);
      out.write("</strong>님\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                ");
 if (!"SA".equals(navUserRole)) { 
      out.write("\n");
      out.write("                ");
 if (navUserStoreId != null && !navUserStoreId.isEmpty()) { 
      out.write("\n");
      out.write("                <span class=\"text-white-50 small me-2 d-none d-md-block\">\n");
      out.write("                    <i class=\"fa-solid fa-store me-1\"></i>");
      out.print(navUserStoreId);
      out.write("\n");
      out.write("                </span>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("                <button class=\"btn btn-sm btn-outline-light me-2\" data-bs-toggle=\"modal\" data-bs-target=\"#changeStoreModal\">\n");
      out.write("                    <i class=\"fa-solid fa-rotate\"></i> 매장변경\n");
      out.write("                </button>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("                <form action=\"");
      out.print(request.getContextPath());
      out.write("/Logout\" method=\"post\" class=\"m-0\">\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-danger btn-sm\">로그아웃</button>\n");
      out.write("                </form>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("<div class=\"modal fade\" id=\"changeStoreModal\" tabindex=\"-1\" aria-hidden=\"true\">\n");
      out.write("    <div class=\"modal-dialog modal-sm modal-dialog-centered\">\n");
      out.write("        <div class=\"modal-content\">\n");
      out.write("            <div class=\"modal-header\">\n");
      out.write("                <h6 class=\"modal-title fw-bold\">접속 매장 선택</h6>\n");
      out.write("                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"></button>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"modal-body p-0\">\n");
      out.write("                <div class=\"list-group list-group-flush\">\n");
      out.write("                    ");
 if(myStoreList == null || myStoreList.isEmpty()) { 
      out.write("\n");
      out.write("                        <div class=\"p-4 text-center\">\n");
      out.write("                            <p class=\"text-muted small mb-2\">등록된 매장이 없습니다.</p>\n");
      out.write("                            <a href=\"MyPage\" class=\"btn btn-sm btn-primary\">매장 등록하기</a>\n");
      out.write("                        </div>\n");
      out.write("                    ");
 } else { 
                        for(String[] s : myStoreList) { 
                            boolean isCurrent = s[0].equals(navUserStoreId);
                    
      out.write("\n");
      out.write("                        <button type=\"button\" onclick=\"changeStore('");
      out.print(s[0]);
      out.write("')\" \n");
      out.write("                                class=\"list-group-item list-group-item-action d-flex justify-content-between align-items-center py-3 ");
      out.print( isCurrent ? "bg-light fw-bold" : "" );
      out.write("\">\n");
      out.write("                            <span>");
      out.print(s[1]);
      out.write(" <small class=\"text-muted\">(");
      out.print(s[0]);
      out.write(")</small></span>\n");
      out.write("                            ");
 if(isCurrent) { 
      out.write("<i class=\"fa-solid fa-check text-primary\"></i>");
 } 
      out.write("\n");
      out.write("                        </button>\n");
      out.write("                    ");
 } } 
      out.write("\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"modal-footer border-0\">\n");
      out.write("                <a href=\"MyPage\" class=\"btn btn-link btn-sm text-decoration-none text-muted mx-auto\">매장 추가/삭제 관리</a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("function changeStore(storeId) {\n");
      out.write("    if(!storeId) return;\n");
      out.write("    fetch('ChangeStore', {\n");
      out.write("        method: 'POST',\n");
      out.write("        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },\n");
      out.write("        body: 'storeId=' + encodeURIComponent(storeId)\n");
      out.write("    })\n");
      out.write("    .then(res => res.json())\n");
      out.write("    .then(data => {\n");
      out.write("        if(data.status === 'success') {\n");
      out.write("            showToast(data.message, data.status === 'success' ? 'success' : 'danger');\n");
      out.write("            location.reload(); \n");
      out.write("        } else {\n");
      out.write("            showToast(data.message, data.status === 'success' ? 'success' : 'danger');\n");
      out.write("        }\n");
      out.write("    })\n");
      out.write("    .catch(err => console.error('Error:', err));\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("    body { padding-top: 70px; }\n");
      out.write("    .list-group-item-action:active { background-color: #f8f9fc; color: inherit; }\n");
      out.write("</style>");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"container mt-5 mb-5\" style=\"max-width: 700px;\">\n");
      out.write("    <div class=\"d-flex justify-content-between align-items-center mb-4\">\n");
      out.write("        <h3 class=\"fw-bold text-dark mb-0\">\n");
      out.write("            <i class=\"fa-solid fa-store me-2 text-primary\"></i>매장 관리\n");
      out.write("        </h3>\n");
      out.write("        <a href=\"default.jsp\" class=\"btn btn-outline-secondary btn-sm fw-bold px-3\">\n");
      out.write("            <i class=\"fa-solid fa-arrow-left me-1\"></i> 대시보드로\n");
      out.write("        </a>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    ");
      out.write("\n");
      out.write("    ");
 if ("A".equals(userRole)) { 
      out.write("\n");
      out.write("    <div class=\"card border-0 shadow-sm p-4 mb-4\" style=\"border-top: 4px solid #e74a3b !important;\">\n");
      out.write("        <h5 class=\"fw-bold mb-3\">\n");
      out.write("            <i class=\"fa-solid fa-user-clock me-2 text-danger\"></i>직원 소속 신청 승인 대기\n");
      out.write("            <span class=\"badge bg-danger ms-2\">");
      out.print(pendingJoins.size());
      out.write("</span>\n");
      out.write("        </h5>\n");
      out.write("        ");
 if (pendingJoins.isEmpty()) { 
      out.write("\n");
      out.write("            <div class=\"text-center text-muted py-4\">\n");
      out.write("                <i class=\"fa-solid fa-circle-check fa-3x mb-3 text-success\"></i>\n");
      out.write("                <p class=\"mb-0 fw-bold\">대기 중인 소속 신청이 없습니다.</p>\n");
      out.write("                <small>직원 소속 신청이 들어오면 여기에 표시됩니다.</small>\n");
      out.write("            </div>\n");
      out.write("        ");
 } else { 
      out.write("\n");
      out.write("        <div class=\"table-responsive\">\n");
      out.write("            <table class=\"table align-middle mb-0\">\n");
      out.write("                <thead class=\"table-light\">\n");
      out.write("                    <tr><th>아이디</th><th>이름</th><th>전화번호</th><th>신청 매장</th><th class=\"text-center\">처리</th></tr>\n");
      out.write("                </thead>\n");
      out.write("                <tbody>\n");
      out.write("                    ");
 for (String[] join : pendingJoins) { 
      out.write("\n");
      out.write("                    <tr id=\"join-row-");
      out.print(join[0]);
      out.write('-');
      out.print(join[3]);
      out.write("\">\n");
      out.write("                        <td class=\"fw-bold\">");
      out.print(join[0]);
      out.write("</td>\n");
      out.write("                        <td>");
      out.print(join[1]);
      out.write("</td>\n");
      out.write("                        <td class=\"text-muted\">");
      out.print(join[2]);
      out.write("</td>\n");
      out.write("                        <td><span class=\"badge bg-primary\">");
      out.print(join[4]);
      out.write("</span></td>\n");
      out.write("                        <td class=\"text-center\">\n");
      out.write("                            <button class=\"btn btn-sm btn-success fw-bold me-1\"\n");
      out.write("                                onclick=\"handleJoin('");
      out.print(join[0]);
      out.write("', '");
      out.print(join[3]);
      out.write("', 'approveJoin')\">\n");
      out.write("                                <i class=\"fa-solid fa-check me-1\"></i>승인\n");
      out.write("                            </button>\n");
      out.write("                            <button class=\"btn btn-sm btn-danger fw-bold\"\n");
      out.write("                                onclick=\"handleJoin('");
      out.print(join[0]);
      out.write("', '");
      out.print(join[3]);
      out.write("', 'rejectJoin')\">\n");
      out.write("                                <i class=\"fa-solid fa-xmark me-1\"></i>거절\n");
      out.write("                            </button>\n");
      out.write("                        </td>\n");
      out.write("                    </tr>\n");
      out.write("                    ");
 } 
      out.write("\n");
      out.write("                </tbody>\n");
      out.write("            </table>\n");
      out.write("        </div>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("    </div>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("    ");
      out.write("\n");
      out.write("    ");
 if ("A".equals(userRole)) { 
      out.write("\n");
      out.write("    <div class=\"card border-0 shadow-sm p-4 mb-4\" style=\"border-top: 4px solid #4e73df !important;\">\n");
      out.write("        <h5 class=\"fw-bold mb-1\">\n");
      out.write("            <i class=\"fa-solid fa-plus-circle me-2 text-primary\"></i>새 매장 생성 신청\n");
      out.write("            <span class=\"badge bg-primary ms-2 small\">점장 전용</span>\n");
      out.write("        </h5>\n");
      out.write("        <p class=\"text-muted small mb-4\">매장 생성 신청 후 전체관리자 승인이 완료되면 사용 가능합니다.</p>\n");
      out.write("        <div class=\"row g-3\">\n");
      out.write("            <div class=\"col-md-5\">\n");
      out.write("                <label class=\"form-label small fw-bold text-secondary\">매장 코드 (ID)</label>\n");
      out.write("                <input type=\"text\" id=\"storeId\" class=\"form-control fw-bold\" placeholder=\"예: store02\" maxlength=\"20\">\n");
      out.write("                <small class=\"text-muted\">영문/숫자 조합, 중복 불가</small>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-5\">\n");
      out.write("                <label class=\"form-label small fw-bold text-secondary\">매장 이름</label>\n");
      out.write("                <input type=\"text\" id=\"storeName\" class=\"form-control\" placeholder=\"예: 강남점\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-2 d-flex align-items-end\">\n");
      out.write("                <button type=\"button\" onclick=\"requestStore()\" class=\"btn btn-primary fw-bold w-100\">신청</button>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("    ");
      out.write("\n");
      out.write("    ");
 if ("S".equals(userRole)) { 
      out.write("\n");
      out.write("    <div class=\"card border-0 shadow-sm p-4 mb-4\" style=\"border-top: 4px solid #f6c23e !important;\">\n");
      out.write("        <h5 class=\"fw-bold mb-1\">\n");
      out.write("            <i class=\"fa-solid fa-magnifying-glass me-2 text-warning\"></i>매장 소속 신청\n");
      out.write("            <span class=\"badge bg-warning text-dark ms-2 small\">직원 전용</span>\n");
      out.write("        </h5>\n");
      out.write("        <p class=\"text-muted small mb-4\">근무할 매장을 검색하여 소속을 신청하세요. <strong>점장 승인 후 소속이 확정됩니다.</strong></p>\n");
      out.write("        <div class=\"row g-3\">\n");
      out.write("            <div class=\"col-md-8\">\n");
      out.write("                <label class=\"form-label small fw-bold text-secondary\">매장 선택</label>\n");
      out.write("                <div class=\"input-group\">\n");
      out.write("                    <input type=\"text\" id=\"storeSearchInput\" class=\"form-control bg-white\"\n");
      out.write("                        placeholder=\"매장을 검색해서 선택하세요\" readonly>\n");
      out.write("                    <button class=\"btn btn-outline-warning fw-bold text-dark\" type=\"button\"\n");
      out.write("                        data-bs-toggle=\"modal\" data-bs-target=\"#storeSearchModal\">\n");
      out.write("                        <i class=\"fa-solid fa-magnifying-glass me-1\"></i>검색\n");
      out.write("                    </button>\n");
      out.write("                </div>\n");
      out.write("                <input type=\"hidden\" id=\"selectedStoreId\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-4 d-flex align-items-end\">\n");
      out.write("                <button type=\"button\" onclick=\"joinStore()\" class=\"btn btn-warning fw-bold w-100 text-dark\">소속 신청</button>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("    ");
      out.write("\n");
      out.write("    <div class=\"card border-0 shadow-sm p-4\">\n");
      out.write("        <h5 class=\"fw-bold mb-3\">\n");
      out.write("            <i class=\"fa-solid fa-list me-2 text-muted\"></i>내 매장 목록\n");
      out.write("        </h5>\n");
      out.write("        ");
 if (myStores.isEmpty()) { 
      out.write("\n");
      out.write("            <div class=\"text-center text-muted py-4\">\n");
      out.write("                <i class=\"fa-solid fa-store-slash fa-3x mb-3\"></i>\n");
      out.write("                <p class=\"mb-0 fw-bold\">등록된 매장이 없습니다.</p>\n");
      out.write("                <small>위에서 매장을 검색하여 소속 신청해보세요.</small>\n");
      out.write("            </div>\n");
      out.write("        ");
 } else { 
      out.write("\n");
      out.write("        <div class=\"list-group list-group-flush border rounded-3 overflow-hidden\">\n");
      out.write("            ");
 for (String[] store : myStores) {
                String joinStatus  = store.length > 2 ? store[2] : "ACTIVE";
                String storeStatus = store.length > 3 ? store[3] : "ACTIVE";
            
      out.write("\n");
      out.write("            <div class=\"list-group-item d-flex justify-content-between align-items-center p-3\">\n");
      out.write("                <div>\n");
      out.write("                    <span class=\"fw-bold text-dark\">");
      out.print(store[1]);
      out.write("</span>\n");
      out.write("                    <small class=\"text-muted ms-2\">(");
      out.print(store[0]);
      out.write(")</small>\n");
      out.write("                    ");
 if ("PENDING".equals(joinStatus)) { 
      out.write("\n");
      out.write("                        <span class=\"badge bg-warning text-dark ms-1\">소속 승인 대기</span>\n");
      out.write("                    ");
 } else if ("PENDING".equals(storeStatus)) { 
      out.write("\n");
      out.write("                        <span class=\"badge bg-info text-dark ms-1\">매장 승인 대기</span>\n");
      out.write("                    ");
 } else { 
      out.write("\n");
      out.write("                        <span class=\"badge bg-success ms-1\">활성</span>\n");
      out.write("                    ");
 } 
      out.write("\n");
      out.write("                </div>\n");
      out.write("                <button type=\"button\" class=\"btn btn-sm btn-outline-danger border-0\"\n");
      out.write("                    onclick=\"deleteStore('");
      out.print(userId);
      out.write("', '");
      out.print(store[0]);
      out.write("')\">\n");
      out.write("                    <i class=\"fa-solid fa-trash-can\"></i>\n");
      out.write("                </button>\n");
      out.write("            </div>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("        </div>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"modal fade\" id=\"storeSearchModal\" tabindex=\"-1\" aria-hidden=\"true\">\n");
      out.write("    <div class=\"modal-dialog modal-dialog-centered modal-md\">\n");
      out.write("        <div class=\"modal-content border-0 shadow\">\n");
      out.write("            <div class=\"modal-header border-0 pb-0\">\n");
      out.write("                <h5 class=\"modal-title fw-bold\">\n");
      out.write("                    <i class=\"fa-solid fa-store me-2 text-warning\"></i>매장 검색\n");
      out.write("                </h5>\n");
      out.write("                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"></button>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"modal-body\">\n");
      out.write("                <div class=\"input-group mb-3\">\n");
      out.write("                    <input type=\"text\" id=\"modalStoreKeyword\" class=\"form-control\"\n");
      out.write("                        placeholder=\"매장 이름 또는 코드 입력\"\n");
      out.write("                        oninput=\"searchStoreModal(this.value)\">\n");
      out.write("                    <button class=\"btn btn-primary fw-bold\" type=\"button\"\n");
      out.write("                        onclick=\"searchStoreModal(document.getElementById('modalStoreKeyword').value)\">\n");
      out.write("                        <i class=\"fa-solid fa-magnifying-glass\"></i>\n");
      out.write("                    </button>\n");
      out.write("                </div>\n");
      out.write("                <div id=\"modalStoreResult\">\n");
      out.write("                    <div class=\"text-center text-muted py-4 small\">\n");
      out.write("                        <i class=\"fa-solid fa-magnifying-glass fa-2x mb-2 d-block\"></i>\n");
      out.write("                        매장 이름이나 코드를 입력해서 검색하세요.\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("<footer class=\"text-center py-5 text-muted bg-white mt-auto border-top no-print\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <p class=\"mb-1 fw-bold text-dark\">AlbaPass</p>\n");
      out.write("        <small>© 2026 AlbaPass Project. All rights reserved.</small>\n");
      out.write("    </div>\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"toast-container position-fixed bottom-0 end-0 p-3\" style=\"z-index: 9999;\">\n");
      out.write("    <div id=\"appToast\" class=\"toast align-items-center border-0 shadow\" role=\"alert\" aria-live=\"assertive\">\n");
      out.write("        <div class=\"d-flex\">\n");
      out.write("            <div class=\"toast-body fw-bold\" id=\"appToastMsg\">\n");
      out.write("                메시지\n");
      out.write("            </div>\n");
      out.write("            <button type=\"button\" class=\"btn-close btn-close-white me-2 m-auto\" data-bs-dismiss=\"toast\"></button>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("<script>\n");
      out.write("// 공통 토스트 함수\n");
      out.write("function showToast(message, type) {\n");
      out.write("    type = type || 'success'; // success, danger, warning, info\n");
      out.write("    const toast    = document.getElementById('appToast');\n");
      out.write("    const toastMsg = document.getElementById('appToastMsg');\n");
      out.write("\n");
      out.write("    // 색상 설정\n");
      out.write("    toast.className = 'toast align-items-center border-0 shadow text-white';\n");
      out.write("    if (type === 'success') toast.classList.add('bg-success');\n");
      out.write("    else if (type === 'danger')  toast.classList.add('bg-danger');\n");
      out.write("    else if (type === 'warning') toast.classList.add('bg-warning', 'text-dark');\n");
      out.write("    else if (type === 'info')    toast.classList.add('bg-primary');\n");
      out.write("\n");
      out.write("    toastMsg.innerText = message;\n");
      out.write("    const bsToast = new bootstrap.Toast(toast, { delay: 3000 });\n");
      out.write("    bsToast.show();\n");
      out.write("}\n");
      out.write("\n");
      out.write("// alert 대체 함수 (기존 코드와 호환)\n");
      out.write("function showAlert(message, type) {\n");
      out.write("    showToast(message, type || 'info');\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("<script>\n");
      out.write("let searchTimer = null;\n");
      out.write("\n");
      out.write("// 매장 검색 모달 (실시간 검색)\n");
      out.write("async function searchStoreModal(keyword) {\n");
      out.write("    clearTimeout(searchTimer);\n");
      out.write("    const resultBox = document.getElementById('modalStoreResult');\n");
      out.write("\n");
      out.write("    if (!keyword || keyword.trim().length < 1) {\n");
      out.write("        resultBox.innerHTML = '<div class=\"text-center text-muted py-4 small\"><i class=\"fa-solid fa-magnifying-glass fa-2x mb-2 d-block\"></i>매장 이름이나 코드를 입력해서 검색하세요.</div>';\n");
      out.write("        return;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    searchTimer = setTimeout(async () => {\n");
      out.write("        try {\n");
      out.write("            const res  = await fetch('SearchStore?keyword=' + encodeURIComponent(keyword.trim()));\n");
      out.write("            const data = await res.json();\n");
      out.write("            resultBox.innerHTML = '';\n");
      out.write("\n");
      out.write("            if (data.status === 'success' && data.list.length > 0) {\n");
      out.write("                const table = document.createElement('table');\n");
      out.write("                table.className = 'table table-hover align-middle mb-0';\n");
      out.write("                table.innerHTML = '<thead class=\"table-light\"><tr><th>매장 이름</th><th>매장 코드</th><th></th></tr></thead>';\n");
      out.write("                const tbody = document.createElement('tbody');\n");
      out.write("\n");
      out.write("                data.list.forEach(store => {\n");
      out.write("                    const tr = document.createElement('tr');\n");
      out.write("                    tr.style.cursor = 'pointer';\n");
      out.write("                    tr.innerHTML =\n");
      out.write("                        '<td class=\"fw-bold\">' + store.name + '</td>' +\n");
      out.write("                        '<td class=\"text-muted\">' + store.id + '</td>' +\n");
      out.write("                        '<td class=\"text-end\"><button type=\"button\" class=\"btn btn-sm btn-primary fw-bold\">선택</button></td>';\n");
      out.write("                    tr.onclick = () => selectStore(store.id, store.name);\n");
      out.write("                    tbody.appendChild(tr);\n");
      out.write("                });\n");
      out.write("\n");
      out.write("                table.appendChild(tbody);\n");
      out.write("                resultBox.appendChild(table);\n");
      out.write("            } else {\n");
      out.write("                resultBox.innerHTML = '<div class=\"text-center text-muted py-4 small\"><i class=\"fa-solid fa-circle-xmark fa-2x mb-2 d-block text-danger\"></i>검색 결과가 없습니다.</div>';\n");
      out.write("            }\n");
      out.write("        } catch (e) {\n");
      out.write("            resultBox.innerHTML = '<div class=\"text-center text-muted py-3 small\">검색 중 오류가 발생했습니다.</div>';\n");
      out.write("        }\n");
      out.write("    }, 300);\n");
      out.write("}\n");
      out.write("\n");
      out.write("// 매장 선택 후 모달 닫기\n");
      out.write("function selectStore(id, name) {\n");
      out.write("    document.getElementById('selectedStoreId').value   = id;\n");
      out.write("    document.getElementById('storeSearchInput').value  = name + ' (' + id + ')';\n");
      out.write("    const modal = bootstrap.Modal.getInstance(document.getElementById('storeSearchModal'));\n");
      out.write("    if (modal) modal.hide();\n");
      out.write("    document.getElementById('modalStoreKeyword').value = '';\n");
      out.write("    document.getElementById('modalStoreResult').innerHTML = '<div class=\"text-center text-muted py-4 small\"><i class=\"fa-solid fa-magnifying-glass fa-2x mb-2 d-block\"></i>매장 이름이나 코드를 입력해서 검색하세요.</div>';\n");
      out.write("}\n");
      out.write("\n");
      out.write("// 모달 열릴 때 검색창 포커스\n");
      out.write("document.getElementById('storeSearchModal').addEventListener('shown.bs.modal', function() {\n");
      out.write("    document.getElementById('modalStoreKeyword').focus();\n");
      out.write("});\n");
      out.write("\n");
      out.write("// // 직원: 매장 소속 신청\n");
      out.write("async function joinStore() {\n");
      out.write("    const storeId = document.getElementById('selectedStoreId').value.trim();\n");
      out.write("    if (!storeId) { showToast('매장을 검색하여 선택해주세요.', 'warning'); return; }\n");
      out.write("    if (!confirm('해당 매장에 소속 신청하시겠습니까?\\n점장 승인 후 소속이 확정됩니다.')) return;\n");
      out.write("\n");
      out.write("    const params = new URLSearchParams();\n");
      out.write("    params.append('add_store_id', storeId);\n");
      out.write("\n");
      out.write("    try {\n");
      out.write("        const res  = await fetch('MyStoreAdd', { method: 'POST', body: params });\n");
      out.write("        const data = await res.json();\n");
      out.write("        showToast(data.message, data.status === 'success' ? 'success' : 'danger');\n");
      out.write("        if (data.status === 'success') location.reload();\n");
      out.write("    } catch (e) { showToast('서버 통신 오류가 발생했습니다.', 'warning'); }\n");
      out.write("}\n");
      out.write("\n");
      out.write("// 점장: 직원 소속 신청 승인/거절\n");
      out.write("async function handleJoin(memId, storeId, mode) {\n");
      out.write("    const action = mode === 'approveJoin' ? '승인' : '거절';\n");
      out.write("    if (!confirm('\"' + memId + '\" 직원의 소속 신청을 ' + action + '하시겠습니까?')) return;\n");
      out.write("\n");
      out.write("    const params = new URLSearchParams();\n");
      out.write("    params.append('mode', mode);\n");
      out.write("    params.append('memId', memId);\n");
      out.write("    params.append('storeId', storeId);\n");
      out.write("\n");
      out.write("    try {\n");
      out.write("        const res  = await fetch('StoreManage', { method: 'POST', body: params });\n");
      out.write("        const data = await res.json();\n");
      out.write("        showToast(data.message, data.status === 'success' ? 'success' : 'danger');\n");
      out.write("        if (data.status === 'success') {\n");
      out.write("            const row = document.getElementById('join-row-' + memId + '-' + storeId);\n");
      out.write("            if (row) row.remove();\n");
      out.write("        }\n");
      out.write("    } catch (e) { showToast('서버 통신 오류가 발생했습니다.', 'warning'); }\n");
      out.write("}\n");
      out.write("\n");
      out.write("// 점장: 새 매장 생성 신청\n");
      out.write("async function requestStore() {\n");
      out.write("    const storeId   = document.getElementById('storeId').value.trim();\n");
      out.write("    const storeName = document.getElementById('storeName').value.trim();\n");
      out.write("    if (!storeId || !storeName) { showToast('매장 코드와 이름을 모두 입력해주세요.', 'warning'); return; }\n");
      out.write("    if (!confirm('[' + storeId + '] 매장 생성을 신청하시겠습니까?')) return;\n");
      out.write("\n");
      out.write("    const params = new URLSearchParams();\n");
      out.write("    params.append('storeId', storeId);\n");
      out.write("    params.append('storeName', storeName);\n");
      out.write("\n");
      out.write("    try {\n");
      out.write("        const res  = await fetch('StoreManage', { method: 'POST', body: params });\n");
      out.write("        const data = await res.json();\n");
      out.write("        showToast(data.message, data.status === 'success' ? 'success' : 'danger');\n");
      out.write("        if (data.status === 'success') location.reload();\n");
      out.write("    } catch (e) { showToast('서버 통신 오류가 발생했습니다.', 'warning'); }\n");
      out.write("}\n");
      out.write("\n");
      out.write("// 매장 삭제\n");
      out.write("async function deleteStore(userId, storeId) {\n");
      out.write("    if (!confirm('해당 매장을 목록에서 삭제하시겠습니까?')) return;\n");
      out.write("    try {\n");
      out.write("        const res  = await fetch('MyStoreDelete?id=' + userId + '&storeId=' + storeId);\n");
      out.write("        const data = await res.json();\n");
      out.write("        showToast(data.message, data.status === 'success' ? 'success' : 'danger');\n");
      out.write("        if (data.status === 'success') location.reload();\n");
      out.write("    } catch (e) { showToast('서버 통신 오류가 발생했습니다.', 'warning'); }\n");
      out.write("}\n");
      out.write("\n");
      out.write("// 검색창 외부 클릭 시 닫기\n");
      out.write("document.addEventListener('click', function(e) {\n");
      out.write("    const resultBox = document.getElementById('searchResult');\n");
      out.write("    if (resultBox && !resultBox.contains(e.target) && e.target.id !== 'searchKeyword') {\n");
      out.write("        resultBox.style.display = 'none';\n");
      out.write("    }\n");
      out.write("});\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
