/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2026-05-27 13:54:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import work.dto.MemberDTO;
import java.util.ArrayList;
import java.util.ArrayList;
import work.dao.MemberDAO;
import java.util.ArrayList;

public final class store_005fmember_005fmanage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/navbar.jsp", Long.valueOf(1779373637269L));
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1779373637201L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("work.dao.MemberDAO");
    _jspx_imports_classes.add("work.dto.MemberDTO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    String loggedInId   = (String)session.getAttribute("userId");
    String userRolesess = (String)session.getAttribute("userRole");
    String currentStoreId = (String)session.getAttribute("userStoreId");
    if (currentStoreId == null) currentStoreId = "";

    if (!"A".equals(userRolesess != null ? userRolesess.trim() : "")) {
        response.sendRedirect("login.jsp");
        return;
    }

    ArrayList<MemberDTO> memberList = (ArrayList<MemberDTO>)request.getAttribute("memberList");
    if (memberList == null) memberList = new ArrayList<>();

    ArrayList<String[]> myStores = (ArrayList<String[]>)request.getAttribute("myStores");
    if (myStores == null) myStores = new ArrayList<>();

    ArrayList<String[]> pendingList = (ArrayList<String[]>)request.getAttribute("pendingList");
    if (pendingList == null) pendingList = new ArrayList<>();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>매장 · 직원 관리 - AlbaPass</title>\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Pretendard:wght@400;600;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/style.css\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" href=\"");
      out.print(request.getContextPath());
      out.write("/jlogo.png\">\r\n");
      out.write("    <style>\r\n");
      out.write("        .store-item {\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            border-left: 4px solid transparent;\r\n");
      out.write("            transition: all 0.2s;\r\n");
      out.write("        }\r\n");
      out.write("        .store-item:hover { background-color: #f0f4ff; border-left-color: #4e73df; }\r\n");
      out.write("        .store-item.active { background-color: #e8edff; border-left-color: #4e73df; font-weight: 700; }\r\n");
      out.write("        .store-panel { min-height: 500px; }\r\n");
      out.write("        .member-card { transition: all 0.2s; }\r\n");
      out.write("        .member-card:hover { transform: translateY(-2px); box-shadow: 0 4px 12px rgba(0,0,0,0.1) !important; }\r\n");
      out.write("        .wage-badge { background: #f0f4ff; color: #4e73df; padding: 3px 10px; border-radius: 20px; font-size: 12px; font-weight: 700; }\r\n");
      out.write("        .empty-state { min-height: 300px; display: flex; flex-direction: column; align-items: center; justify-content: center; }\r\n");
      out.write("        .day-dot { width:26px; height:26px; border-radius:50%; display:inline-flex; align-items:center; justify-content:center;\r\n");
      out.write("                   font-size:11px; font-weight:700; border:1.5px solid #dee2e6; color:#adb5bd; background:#fff; }\r\n");
      out.write("        .day-dot.active { background:#4e73df; border-color:#4e73df; color:#fff; }\r\n");
      out.write("        .work-time-cell { line-height:1.4; }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write('\n');
      out.write('\n');

    // 1. 세션 변수 안전하게 가져오기
    String navUserId = (String)session.getAttribute("userId");
    String navUserName = (String)session.getAttribute("userName");
    String navUserRole = (String)session.getAttribute("userRole"); 
    String navUserStoreId = (String)session.getAttribute("userStoreId"); 

    // 2. 매장 목록 가져오기 (에러 방지를 위해 초기화)
    ArrayList<String[]> myStoreList = new ArrayList<>();
    
    // 로그인 상태일 때만 DB 조회
    if (navUserId != null) {
        try {
            MemberDAO navDao = new MemberDAO();
            myStoreList = navDao.getMyStoreList(navUserId);
        } catch (Exception e) {
            System.err.println("Navbar Store List Error: " + e.getMessage());
        }
    }

      out.write("\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark shadow-sm fixed-top\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <a class=\"navbar-brand d-flex align-items-center\" href=\"");
      out.print(request.getContextPath());
      out.write("/default.jsp\">\n");
      out.write("            <img src=\"");
      out.print(request.getContextPath());
      out.write("/Emblem.png\" alt=\"AlbaPass 로고\" style=\"height: 36px; object-fit: contain;\">\n");
      out.write("        </a>\n");
      out.write("        \n");
      out.write("        <div class=\"d-flex align-items-center\">\n");
      out.write("            ");
 if(navUserId == null) { 
      out.write("\n");
      out.write("                <a href=\"login.jsp\" class=\"btn btn-outline-light btn-sm me-2\">로그인</a>\n");
      out.write("                <a href=\"register.jsp\" class=\"btn btn-primary btn-sm\">회원가입</a>\n");
      out.write("            ");
 } else { 
      out.write("\n");
      out.write("                <div class=\"text-white me-3 d-none d-md-block small\">\n");
      out.write("                    <span class=\"badge ");

                        if ("SA".equals(navUserRole)) { 
      out.write("bg-danger");

                        } else if ("A".equals(navUserRole)) { 
      out.write("bg-primary");

                        } else { 
      out.write("bg-warning text-dark");
 } 
      out.write(" me-1\">\n");
      out.write("                        ");
 if ("SA".equals(navUserRole)) { 
      out.write("전체관리자");

                        } else if ("A".equals(navUserRole)) { 
      out.write('점');
      out.write('장');

                        } else { 
      out.write('직');
      out.write('원');
 } 
      out.write("\n");
      out.write("                    </span>\n");
      out.write("                    <strong>");
      out.print(navUserName);
      out.write("</strong>님\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                ");
 if (!"SA".equals(navUserRole)) { 
      out.write("\n");
      out.write("                ");
 if (navUserStoreId != null && !navUserStoreId.isEmpty()) { 
      out.write("\n");
      out.write("                <span class=\"text-white-50 small me-2 d-none d-md-block\">\n");
      out.write("                    <i class=\"fa-solid fa-store me-1\"></i>");
      out.print(navUserStoreId);
      out.write("\n");
      out.write("                </span>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("                <button class=\"btn btn-sm btn-outline-light me-2\" data-bs-toggle=\"modal\" data-bs-target=\"#changeStoreModal\">\n");
      out.write("                    <i class=\"fa-solid fa-rotate\"></i> 매장변경\n");
      out.write("                </button>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("                <form action=\"");
      out.print(request.getContextPath());
      out.write("/Logout\" method=\"post\" class=\"m-0\">\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-danger btn-sm\">로그아웃</button>\n");
      out.write("                </form>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("<div class=\"modal fade\" id=\"changeStoreModal\" tabindex=\"-1\" aria-hidden=\"true\">\n");
      out.write("    <div class=\"modal-dialog modal-sm modal-dialog-centered\">\n");
      out.write("        <div class=\"modal-content\">\n");
      out.write("            <div class=\"modal-header\">\n");
      out.write("                <h6 class=\"modal-title fw-bold\">접속 매장 선택</h6>\n");
      out.write("                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"></button>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"modal-body p-0\">\n");
      out.write("                <div class=\"list-group list-group-flush\">\n");
      out.write("                    ");
 if(myStoreList == null || myStoreList.isEmpty()) { 
      out.write("\n");
      out.write("                        <div class=\"p-4 text-center\">\n");
      out.write("                            <p class=\"text-muted small mb-2\">등록된 매장이 없습니다.</p>\n");
      out.write("                            <a href=\"MyPage\" class=\"btn btn-sm btn-primary\">매장 등록하기</a>\n");
      out.write("                        </div>\n");
      out.write("                    ");
 } else { 
                        for(String[] s : myStoreList) { 
                            boolean isCurrent = s[0].equals(navUserStoreId);
                    
      out.write("\n");
      out.write("                        <button type=\"button\" onclick=\"changeStore('");
      out.print(s[0]);
      out.write("')\" \n");
      out.write("                                class=\"list-group-item list-group-item-action d-flex justify-content-between align-items-center py-3 ");
      out.print( isCurrent ? "bg-light fw-bold" : "" );
      out.write("\">\n");
      out.write("                            <span>");
      out.print(s[1]);
      out.write(" <small class=\"text-muted\">(");
      out.print(s[0]);
      out.write(")</small></span>\n");
      out.write("                            ");
 if(isCurrent) { 
      out.write("<i class=\"fa-solid fa-check text-primary\"></i>");
 } 
      out.write("\n");
      out.write("                        </button>\n");
      out.write("                    ");
 } } 
      out.write("\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"modal-footer border-0\">\n");
      out.write("                <a href=\"MyPage\" class=\"btn btn-link btn-sm text-decoration-none text-muted mx-auto\">매장 추가/삭제 관리</a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("function changeStore(storeId) {\n");
      out.write("    if(!storeId) return;\n");
      out.write("    fetch('ChangeStore', {\n");
      out.write("        method: 'POST',\n");
      out.write("        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },\n");
      out.write("        body: 'storeId=' + encodeURIComponent(storeId)\n");
      out.write("    })\n");
      out.write("    .then(res => res.json())\n");
      out.write("    .then(data => {\n");
      out.write("        if(data.status === 'success') {\n");
      out.write("            showToast(data.message, data.status === 'success' ? 'success' : 'danger');\n");
      out.write("            location.reload(); \n");
      out.write("        } else {\n");
      out.write("            showToast(data.message, data.status === 'success' ? 'success' : 'danger');\n");
      out.write("        }\n");
      out.write("    })\n");
      out.write("    .catch(err => console.error('Error:', err));\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("    body { padding-top: 70px; }\n");
      out.write("    .list-group-item-action:active { background-color: #f8f9fc; color: inherit; }\n");
      out.write("</style>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container-fluid mt-4 mb-5 px-4\">\r\n");
      out.write("    <div class=\"d-flex justify-content-between align-items-center mb-4\">\r\n");
      out.write("        <h3 class=\"fw-bold text-dark mb-0\">\r\n");
      out.write("            <i class=\"fa-solid fa-store me-2 text-primary\"></i>매장 · 직원 관리\r\n");
      out.write("        </h3>\r\n");
      out.write("        <a href=\"default.jsp\" class=\"btn btn-outline-secondary btn-sm fw-bold px-3\">\r\n");
      out.write("            <i class=\"fa-solid fa-arrow-left me-1\"></i> 대시보드로\r\n");
      out.write("        </a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"row g-4\">\r\n");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        <div class=\"col-12 col-lg-3\">\r\n");
      out.write("            <div class=\"card border-0 shadow-sm h-100\">\r\n");
      out.write("                <div class=\"card-header bg-white border-0 pt-4 pb-2 px-4\">\r\n");
      out.write("                    <h6 class=\"fw-bold text-dark mb-0\">\r\n");
      out.write("                        <i class=\"fa-solid fa-store me-2 text-primary\"></i>내 매장\r\n");
      out.write("                        <span class=\"badge bg-primary ms-1\">");
      out.print(myStores.size());
      out.write("</span>\r\n");
      out.write("                    </h6>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card-body p-0\">\r\n");
      out.write("                    ");
 if (myStores.isEmpty()) { 
      out.write("\r\n");
      out.write("                    <div class=\"text-center text-muted py-5 px-3\">\r\n");
      out.write("                        <i class=\"fa-solid fa-store-slash fa-2x mb-2 d-block\"></i>\r\n");
      out.write("                        <small>등록된 매장이 없습니다.</small>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    ");
 } else {
                        for (int i = 0; i < myStores.size(); i++) {
                            String[] store = myStores.get(i);
                            boolean isActive = store[0].equals(currentStoreId);
                    
      out.write("\r\n");
      out.write("                    <div class=\"store-item p-3 px-4 ");
      out.print(isActive ? "active" : "");
      out.write("\"\r\n");
      out.write("                        onclick=\"selectStore('");
      out.print(store[0]);
      out.write("', '");
      out.print(store[1]);
      out.write("')\"\r\n");
      out.write("                        id=\"store-item-");
      out.print(store[0]);
      out.write("\">\r\n");
      out.write("                        <div class=\"d-flex align-items-center justify-content-between\">\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <div class=\"fw-bold text-dark\">");
      out.print(store[1]);
      out.write("</div>\r\n");
      out.write("                                <small class=\"text-muted\">");
      out.print(store[0]);
      out.write("</small>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <i class=\"fa-solid fa-chevron-right text-muted small\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    ");
  }
                    } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    ");
      out.write("\r\n");
      out.write("                    <div class=\"p-3 border-top\">\r\n");
      out.write("                        <button class=\"btn btn-outline-primary btn-sm w-100 fw-bold\"\r\n");
      out.write("                            data-bs-toggle=\"modal\" data-bs-target=\"#addStoreModal\">\r\n");
      out.write("                            <i class=\"fa-solid fa-plus me-1\"></i> 새 매장 생성 신청\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        <div class=\"col-12 col-lg-9\">\r\n");
      out.write("\r\n");
      out.write("            ");
      out.write("\r\n");
      out.write("            <div class=\"card border-0 shadow-sm mb-3\">\r\n");
      out.write("                <div class=\"card-body py-3 px-4\">\r\n");
      out.write("                    <div class=\"d-flex justify-content-between align-items-center flex-wrap gap-2\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <h5 class=\"fw-bold mb-0\" id=\"selectedStoreName\">\r\n");
      out.write("                                <i class=\"fa-solid fa-store me-2 text-primary\"></i>");
      out.print(currentStoreId.isEmpty() ? "매장을 선택하세요" : currentStoreId);
      out.write("\r\n");
      out.write("                            </h5>\r\n");
      out.write("                            <small class=\"text-muted\" id=\"memberCountText\">직원 ");
      out.print(memberList.size());
      out.write("명</small>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"d-flex gap-2\">\r\n");
      out.write("                            <button class=\"btn btn-sm btn-outline-warning fw-bold\"\r\n");
      out.write("                                data-bs-toggle=\"modal\" data-bs-target=\"#storeSettingModal\">\r\n");
      out.write("                                <i class=\"fa-solid fa-gear me-1\"></i> 매장 설정\r\n");
      out.write("                            </button>\r\n");
      out.write("                            <a href=\"RoleManage\" class=\"btn btn-sm btn-outline-primary fw-bold\">\r\n");
      out.write("                                <i class=\"fa-solid fa-tags me-1\"></i> 역할 관리\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            ");
      out.write("\r\n");
      out.write("            <div class=\"card border-0 shadow-sm mb-3\">\r\n");
      out.write("                <div class=\"card-body py-3 px-4\">\r\n");
      out.write("                    <div class=\"row g-2\">\r\n");
      out.write("                        <div class=\"col-md-5\">\r\n");
      out.write("                            <div class=\"input-group input-group-sm\">\r\n");
      out.write("                                <span class=\"input-group-text bg-white border-end-0\">\r\n");
      out.write("                                    <i class=\"fa-solid fa-magnifying-glass text-muted\"></i>\r\n");
      out.write("                                </span>\r\n");
      out.write("                                <input type=\"text\" id=\"searchInput\" class=\"form-control border-start-0\"\r\n");
      out.write("                                    placeholder=\"이름 또는 전화번호 검색\" oninput=\"filterMembers()\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-3\">\r\n");
      out.write("                            <select id=\"roleFilter\" class=\"form-select form-select-sm\" onchange=\"filterMembers()\">\r\n");
      out.write("                                <option value=\"\">전체 역할</option>\r\n");
      out.write("                                <option value=\"unassigned\">역할 미지정</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-3\">\r\n");
      out.write("                            <select id=\"typeFilter\" class=\"form-select form-select-sm\" onchange=\"filterMembers()\">\r\n");
      out.write("                                <option value=\"\">전체</option>\r\n");
      out.write("                                <option value=\"staff\">직원만</option>\r\n");
      out.write("                                <option value=\"admin\">점장만</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            ");
      out.write("\r\n");
      out.write("            <div class=\"card border-0 shadow-sm store-panel\">\r\n");
      out.write("                <div class=\"card-body p-0\">\r\n");
      out.write("                    ");
 if (memberList.isEmpty()) { 
      out.write("\r\n");
      out.write("                    <div class=\"empty-state text-muted\">\r\n");
      out.write("                        <i class=\"fa-solid fa-users fa-3x mb-3 text-light\"></i>\r\n");
      out.write("                        <p class=\"fw-bold mb-1\">등록된 직원이 없습니다.</p>\r\n");
      out.write("                        <small>직원이 소속 신청 후 승인하면 표시됩니다.</small>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    ");
 } else { 
      out.write("\r\n");
      out.write("                    <div class=\"table-responsive\">\r\n");
      out.write("                        <table class=\"table align-middle mb-0\" id=\"memberTable\">\r\n");
      out.write("                            <thead class=\"table-light\">\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th class=\"ps-4\">이름</th>\r\n");
      out.write("                                    <th>전화번호</th>\r\n");
      out.write("                                    <th>역할 / 시급</th>\r\n");
      out.write("                                    <th>근무 요일</th>\r\n");
      out.write("                                    <th>근무 시간 / 유형</th>\r\n");
      out.write("                                    <th class=\"text-center\">관리</th>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </thead>\r\n");
      out.write("                            <tbody>\r\n");

    for (MemberDTO m : memberList) {
        boolean isSelf  = m.getId().equals(loggedInId);
        boolean isAdmin = "A".equals(m.getRole() != null ? m.getRole().trim() : "");
        boolean noRole  = !isAdmin && m.getRoleId() == 0;
        String rowClass = isSelf ? "table-info-subtle" : (noRole ? "table-warning" : "");

      out.write("\r\n");
      out.write("                            <tr class=\"");
      out.print(rowClass);
      out.write("\">\r\n");
      out.write("                                <td class=\"ps-4\">\r\n");
      out.write("                                    <span class=\"fw-bold text-dark\">");
      out.print(m.getName());
      out.write("</span>\r\n");
      out.write("                                    ");
if (isAdmin) {
      out.write("<span class=\"badge bg-primary ms-1\" style=\"font-size:0.7rem;\">점장</span>");
}
      out.write("\r\n");
      out.write("                                    ");
if (!isAdmin) {
      out.write("<span class=\"badge bg-warning text-dark ms-1\" style=\"font-size:0.7rem;\">직원</span>");
}
      out.write("\r\n");
      out.write("                                    ");
if (noRole) {
      out.write("<span class=\"badge bg-danger ms-1\" style=\"font-size:0.7rem;\">역할 미지정</span>");
}
      out.write("\r\n");
      out.write("                                    ");
if (isSelf) {
      out.write("<span class=\"badge bg-dark ms-1\" style=\"font-size:0.7rem;\">나</span>");
}
      out.write("\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td class=\"text-muted\">");
      out.print(m.getPhone());
      out.write("</td>\r\n");
      out.write("                                <td style=\"min-width:200px;\">\r\n");
      out.write("                                    <div class=\"d-flex align-items-center gap-2\">\r\n");
      out.write("                                        <select class=\"form-select form-select-sm role-select\"\r\n");
      out.write("                                            id=\"roleSelect-");
      out.print(m.getId());
      out.write("\"\r\n");
      out.write("                                            onchange=\"assignRole('");
      out.print(m.getId());
      out.write("', this)\"\r\n");
      out.write("                                            data-current=\"");
      out.print(m.getRoleId());
      out.write("\"\r\n");
      out.write("                                            style=\"max-width:150px;\">\r\n");
      out.write("                                            <option value=\"0\">-- 미지정 --</option>\r\n");
      out.write("                                        </select>\r\n");
      out.write("                                        <small class=\"text-primary fw-bold text-nowrap\" id=\"wage-");
      out.print(m.getId());
      out.write("\">\r\n");
      out.write("                                            ");
      out.print(m.getHourlyWage() > 0 ? String.format("%,d", m.getHourlyWage()) + "원" : "-");
      out.write("\r\n");
      out.write("                                        </small>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    ");

                                        String[] allDots = {"월","화","수","목","금","토","일"};
                                        String wdStr = m.getWorkDays() != null ? m.getWorkDays() : "";
                                        java.util.List<String> wdList = java.util.Arrays.asList(wdStr.split(","));
                                    
      out.write("\r\n");
      out.write("                                    <div class=\"d-flex gap-1 flex-wrap\">\r\n");
      out.write("                                    ");
 for(String dot : allDots) {
                                        boolean active = wdList.contains(dot.trim());
                                    
      out.write("\r\n");
      out.write("                                        <span class=\"day-dot ");
      out.print(active ? "active" : "");
      out.write('"');
      out.write('>');
      out.print(dot);
      out.write("</span>\r\n");
      out.write("                                    ");
 } 
      out.write("\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td style=\"min-width:150px;\">\r\n");
      out.write("                                    ");

                                        String ws = m.getWorkStart() != null ? m.getWorkStart() : "";
                                        String we = m.getWorkEnd()   != null ? m.getWorkEnd()   : "";
                                        String wt = m.getWorkType()  != null ? m.getWorkType()  : "";
                                        boolean hasSchedule = !ws.isEmpty() && !we.isEmpty();
                                    
      out.write("\r\n");
      out.write("                                    <div class=\"d-flex align-items-center gap-1\">\r\n");
      out.write("                                        <div class=\"work-time-cell\">\r\n");
      out.write("                                        ");
if (hasSchedule) {
      out.write("\r\n");
      out.write("                                            <div class=\"d-flex align-items-center gap-1 flex-wrap\">\r\n");
      out.write("                                                <small class=\"fw-bold text-dark\">");
      out.print(ws);
      out.write('~');
      out.print(we);
      out.write("</small>\r\n");
      out.write("                                                ");
if (!wt.isEmpty()) {
      out.write("\r\n");
      out.write("                                                <span class=\"badge ");
      out.print("주말".equals(wt) ? "bg-warning text-dark" : "전체".equals(wt) ? "bg-success" : "bg-primary");
      out.write("\"\r\n");
      out.write("                                                    style=\"font-size:10px;\">");
      out.print(wt);
      out.write("</span>\r\n");
      out.write("                                                ");
}
      out.write("\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        ");
} else {
      out.write("\r\n");
      out.write("                                            <span class=\"text-muted\" style=\"font-size:12px;\">미설정</span>\r\n");
      out.write("                                        ");
}
      out.write("\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <button class=\"btn btn-xs btn-outline-secondary border py-0 px-1 ms-1\"\r\n");
      out.write("                                            style=\"font-size:11px; white-space:nowrap;\"\r\n");
      out.write("                                            onclick=\"openWorkSettingModal('");
      out.print(m.getId());
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(m.getName());
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(ws);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(we);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(wt);
      out.write("')\">\r\n");
      out.write("                                            <i class=\"fa-solid fa-pen-to-square\"></i>\r\n");
      out.write("                                        </button>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td class=\"text-center\">\r\n");
      out.write("                                    ");
if (!isSelf) {
      out.write("\r\n");
      out.write("                                        <a href=\"javascript:void(0);\"\r\n");
      out.write("                                            onclick=\"removeStaff('");
      out.print(m.getId());
      out.write("', '");
      out.print(m.getName());
      out.write("')\"\r\n");
      out.write("                                            class=\"btn btn-sm btn-danger fw-bold\">\r\n");
      out.write("                                            <i class=\"fa-solid fa-user-minus\"></i> 제외\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    ");
} else {
      out.write("\r\n");
      out.write("                                        <button class=\"btn btn-sm btn-secondary fw-bold\" disabled>\r\n");
      out.write("                                            <i class=\"fa-solid fa-lock\"></i> 고정\r\n");
      out.write("                                        </button>\r\n");
      out.write("                                    ");
}
      out.write("\r\n");
      out.write("                                </td>\r\n");
      out.write("                            </tr>\r\n");
  } 
      out.write("\r\n");
      out.write("                            </tbody>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    ");
      out.write("\r\n");
      out.write("                    <div class=\"border-top px-4 py-3\">\r\n");
      out.write("                        <h6 class=\"fw-bold text-muted small text-uppercase mb-2\">\r\n");
      out.write("                            <i class=\"fa-solid fa-clock me-1\"></i>소속 신청 대기\r\n");
      out.write("                            ");
if (!pendingList.isEmpty()) {
      out.write("\r\n");
      out.write("                            <span class=\"badge bg-danger ms-1\">");
      out.print(pendingList.size());
      out.write("</span>\r\n");
      out.write("                            ");
}
      out.write("\r\n");
      out.write("                        </h6>\r\n");
      out.write("                        ");
if (pendingList.isEmpty()) {
      out.write("\r\n");
      out.write("                        <small class=\"text-muted\">승인 대기 중인 직원이 없습니다.</small>\r\n");
      out.write("                        ");
} else {
                            for (String[] p : pendingList) {
      out.write("\r\n");
      out.write("                        <div class=\"d-flex align-items-center justify-content-between py-2 border-bottom\">\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <span class=\"fw-bold text-dark\">");
      out.print(p[1]);
      out.write("</span>\r\n");
      out.write("                                <small class=\"text-muted ms-2\">");
      out.print(p[0]);
      out.write("</small>\r\n");
      out.write("                                <small class=\"text-muted ms-1\">(");
      out.print(p[4]);
      out.write(")</small>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"d-flex gap-2\">\r\n");
      out.write("                                <button class=\"btn btn-sm btn-success fw-bold px-3\"\r\n");
      out.write("                                    onclick=\"handleJoin('");
      out.print(p[0]);
      out.write("', '");
      out.print(p[3]);
      out.write("', 'approve')\">\r\n");
      out.write("                                    승인\r\n");
      out.write("                                </button>\r\n");
      out.write("                                <button class=\"btn btn-sm btn-outline-danger fw-bold px-3\"\r\n");
      out.write("                                    onclick=\"handleJoin('");
      out.print(p[0]);
      out.write("', '");
      out.print(p[3]);
      out.write("', 'reject')\">\r\n");
      out.write("                                    거절\r\n");
      out.write("                                </button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        ");
  }
                        }
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"modal fade\" id=\"workSettingModal\" tabindex=\"-1\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog modal-dialog-centered\">\r\n");
      out.write("        <div class=\"modal-content border-0 shadow\">\r\n");
      out.write("            <div class=\"modal-header border-0\">\r\n");
      out.write("                <h5 class=\"modal-title fw-bold\">\r\n");
      out.write("                    <i class=\"fa-solid fa-clock me-2 text-primary\"></i>근무 설정\r\n");
      out.write("                    <small class=\"text-muted fw-normal ms-1\" id=\"workSettingName\"></small>\r\n");
      out.write("                </h5>\r\n");
      out.write("                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"></button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-body\">\r\n");
      out.write("                <input type=\"hidden\" id=\"wsMemId\">\r\n");
      out.write("                <input type=\"hidden\" id=\"wsStoreId\" value=\"");
      out.print(currentStoreId);
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("                ");
      out.write("\r\n");
      out.write("                <div class=\"mb-4\">\r\n");
      out.write("                    <label class=\"form-label fw-bold text-secondary small\">근무 시간</label>\r\n");
      out.write("                    <div class=\"d-flex align-items-center gap-2\">\r\n");
      out.write("                        <input type=\"time\" id=\"wsStart\" class=\"form-control\" style=\"max-width:140px;\">\r\n");
      out.write("                        <span class=\"text-muted fw-bold\">~</span>\r\n");
      out.write("                        <input type=\"time\" id=\"wsEnd\" class=\"form-control\" style=\"max-width:140px;\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <small class=\"text-muted mt-1 d-block\">\r\n");
      out.write("                        <i class=\"fa-solid fa-moon me-1 text-dark\"></i>22:00 이후는 야간수당(×1.5) 자동 적용\r\n");
      out.write("                    </small>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                ");
      out.write("\r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <label class=\"form-label fw-bold text-secondary small\">근무 유형</label>\r\n");
      out.write("                    <div class=\"d-flex gap-2\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <input type=\"radio\" class=\"btn-check\" name=\"wsType\" id=\"wsTypePW\" value=\"평일\">\r\n");
      out.write("                            <label class=\"btn btn-outline-primary fw-bold px-4\" for=\"wsTypePW\">\r\n");
      out.write("                                <i class=\"fa-solid fa-briefcase me-1\"></i>평일\r\n");
      out.write("                            </label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <input type=\"radio\" class=\"btn-check\" name=\"wsType\" id=\"wsTypeWE\" value=\"주말\">\r\n");
      out.write("                            <label class=\"btn btn-outline-warning fw-bold px-4\" for=\"wsTypeWE\">\r\n");
      out.write("                                <i class=\"fa-solid fa-sun me-1\"></i>주말\r\n");
      out.write("                            </label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <input type=\"radio\" class=\"btn-check\" name=\"wsType\" id=\"wsTypeAll\" value=\"전체\">\r\n");
      out.write("                            <label class=\"btn btn-outline-success fw-bold px-4\" for=\"wsTypeAll\">\r\n");
      out.write("                                <i class=\"fa-solid fa-calendar-days me-1\"></i>전체\r\n");
      out.write("                            </label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                ");
      out.write("\r\n");
      out.write("                <div class=\"p-3 bg-light rounded-3 mt-3\">\r\n");
      out.write("                    <small class=\"fw-bold text-muted d-block mb-2\">\r\n");
      out.write("                        <i class=\"fa-solid fa-calculator me-1\"></i>적용 시급 미리보기\r\n");
      out.write("                    </small>\r\n");
      out.write("                    <div class=\"d-flex flex-wrap gap-2\" id=\"wagePreview\">\r\n");
      out.write("                        <span class=\"text-muted small\">시간대·유형을 선택하면 표시됩니다.</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-footer border-0\">\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-light fw-bold px-4\" data-bs-dismiss=\"modal\">취소</button>\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-primary fw-bold px-4\" onclick=\"saveWorkSetting()\">\r\n");
      out.write("                    <i class=\"fa-solid fa-check me-1\"></i>저장\r\n");
      out.write("                </button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"modal fade\" id=\"storeSettingModal\" tabindex=\"-1\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog modal-dialog-centered\">\r\n");
      out.write("        <div class=\"modal-content border-0 shadow\">\r\n");
      out.write("            <div class=\"modal-header border-0\">\r\n");
      out.write("                <h5 class=\"modal-title fw-bold\">\r\n");
      out.write("                    <i class=\"fa-solid fa-gear me-2 text-warning\"></i>매장 급여 설정\r\n");
      out.write("                </h5>\r\n");
      out.write("                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"></button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-body\">\r\n");
      out.write("                <p class=\"text-muted small mb-4\">해당 매장에 적용할 수당 정책을 설정하세요.</p>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"d-flex justify-content-between align-items-center p-3 bg-light rounded-3 mb-3\">\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <div class=\"fw-bold text-dark\">야간 수당</div>\r\n");
      out.write("                        <small class=\"text-muted\">22:00 ~ 06:00 근무 시 기본 시급 × 1.5 적용</small>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-check form-switch mb-0\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" id=\"useNightPay\" style=\"width:48px; height:24px;\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"d-flex justify-content-between align-items-center p-3 bg-light rounded-3 mb-3\">\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <div class=\"fw-bold text-dark\">주말 수당</div>\r\n");
      out.write("                        <small class=\"text-muted\">토·일 근무 시 기본 시급 × 1.5 적용</small>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-check form-switch mb-0\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" id=\"useWeekendPay\" style=\"width:48px; height:24px;\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"d-flex justify-content-between align-items-center p-3 bg-light rounded-3 mb-3\">\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <div class=\"fw-bold text-dark\">주휴수당</div>\r\n");
      out.write("                        <small class=\"text-muted\">주 15시간 이상 근무 시 적용 (5인 이상 사업장 의무)</small>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-check form-switch mb-0\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" id=\"useHolidayPay\" style=\"width:48px; height:24px;\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"alert alert-info small py-2 mb-0\">\r\n");
      out.write("                    <i class=\"fa-solid fa-circle-info me-1\"></i>\r\n");
      out.write("                    5인 미만 사업장은 주휴수당 의무 적용 대상이 아닙니다.\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-footer border-0\">\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-light fw-bold px-4\" data-bs-dismiss=\"modal\">취소</button>\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-primary fw-bold px-4\" onclick=\"saveStoreSetting()\">\r\n");
      out.write("                    <i class=\"fa-solid fa-check me-1\"></i>저장\r\n");
      out.write("                </button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"modal fade\" id=\"addStoreModal\" tabindex=\"-1\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog modal-dialog-centered\">\r\n");
      out.write("        <div class=\"modal-content border-0 shadow\">\r\n");
      out.write("            <div class=\"modal-header border-0\">\r\n");
      out.write("                <h5 class=\"modal-title fw-bold\">\r\n");
      out.write("                    <i class=\"fa-solid fa-plus me-2 text-primary\"></i>새 매장 생성 신청\r\n");
      out.write("                </h5>\r\n");
      out.write("                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"></button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-body\">\r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <label class=\"form-label small fw-bold text-secondary\">매장 코드</label>\r\n");
      out.write("                    <input type=\"text\" id=\"newStoreId\" class=\"form-control\" placeholder=\"예: store01\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <label class=\"form-label small fw-bold text-secondary\">매장 이름</label>\r\n");
      out.write("                    <input type=\"text\" id=\"newStoreName\" class=\"form-control\" placeholder=\"예: 강남점\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"alert alert-warning small py-2 mb-0\">\r\n");
      out.write("                    <i class=\"fa-solid fa-triangle-exclamation me-1\"></i>\r\n");
      out.write("                    전체관리자 승인 후 매장이 활성화됩니다.\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-footer border-0\">\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-light fw-bold px-4\" data-bs-dismiss=\"modal\">취소</button>\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-primary fw-bold px-4\" onclick=\"requestCreateStore()\">\r\n");
      out.write("                    <i class=\"fa-solid fa-paper-plane me-1\"></i>신청하기\r\n");
      out.write("                </button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\n");
      out.write("<footer class=\"text-center py-5 text-muted bg-white mt-auto border-top no-print\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <p class=\"mb-1 fw-bold text-dark\">AlbaPass</p>\n");
      out.write("        <small>© 2026 AlbaPass Project. All rights reserved.</small>\n");
      out.write("    </div>\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"toast-container position-fixed bottom-0 end-0 p-3\" style=\"z-index: 9999;\">\n");
      out.write("    <div id=\"appToast\" class=\"toast align-items-center border-0 shadow\" role=\"alert\" aria-live=\"assertive\">\n");
      out.write("        <div class=\"d-flex\">\n");
      out.write("            <div class=\"toast-body fw-bold\" id=\"appToastMsg\">\n");
      out.write("                메시지\n");
      out.write("            </div>\n");
      out.write("            <button type=\"button\" class=\"btn-close btn-close-white me-2 m-auto\" data-bs-dismiss=\"toast\"></button>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("<script>\n");
      out.write("// 공통 토스트 함수\n");
      out.write("function showToast(message, type) {\n");
      out.write("    type = type || 'success'; // success, danger, warning, info\n");
      out.write("    const toast    = document.getElementById('appToast');\n");
      out.write("    const toastMsg = document.getElementById('appToastMsg');\n");
      out.write("\n");
      out.write("    // 색상 설정\n");
      out.write("    toast.className = 'toast align-items-center border-0 shadow text-white';\n");
      out.write("    if (type === 'success') toast.classList.add('bg-success');\n");
      out.write("    else if (type === 'danger')  toast.classList.add('bg-danger');\n");
      out.write("    else if (type === 'warning') toast.classList.add('bg-warning', 'text-dark');\n");
      out.write("    else if (type === 'info')    toast.classList.add('bg-primary');\n");
      out.write("\n");
      out.write("    toastMsg.innerText = message;\n");
      out.write("    const bsToast = new bootstrap.Toast(toast, { delay: 3000 });\n");
      out.write("    bsToast.show();\n");
      out.write("}\n");
      out.write("\n");
      out.write("// alert 대체 함수 (기존 코드와 호환)\n");
      out.write("function showAlert(message, type) {\n");
      out.write("    showToast(message, type || 'info');\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("// 매장 선택\r\n");
      out.write("function selectStore(storeId, storeName) {\r\n");
      out.write("    document.querySelectorAll('.store-item').forEach(el => el.classList.remove('active'));\r\n");
      out.write("    const item = document.getElementById('store-item-' + storeId);\r\n");
      out.write("    if (item) item.classList.add('active');\r\n");
      out.write("    document.getElementById('selectedStoreName').innerHTML =\r\n");
      out.write("        '<i class=\"fa-solid fa-store me-2 text-primary\"></i>' + storeName;\r\n");
      out.write("    // TODO: 해당 매장 직원 목록 AJAX 로드\r\n");
      out.write("    location.href = 'StoreMemberManage?storeId=' + storeId;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// 역할 로드\r\n");
      out.write("async function loadRoleOptions() {\r\n");
      out.write("    try {\r\n");
      out.write("        const storeId = '");
      out.print(currentStoreId);
      out.write("';\r\n");
      out.write("        if (!storeId) return;\r\n");
      out.write("        const res  = await fetch('GetRoles?storeId=' + encodeURIComponent(storeId));\r\n");
      out.write("        const data = await res.json();\r\n");
      out.write("        if (data.status === 'success') {\r\n");
      out.write("            const roleFilterEl = document.getElementById('roleFilter');\r\n");
      out.write("            document.querySelectorAll('.role-select').forEach(select => {\r\n");
      out.write("                const cur = select.dataset.current || '0';\r\n");
      out.write("                data.list.forEach(role => {\r\n");
      out.write("                    const opt = document.createElement('option');\r\n");
      out.write("                    opt.value = role.roleId;\r\n");
      out.write("                    opt.text  = role.roleName;\r\n");
      out.write("                    opt.dataset.wage = role.wage;\r\n");
      out.write("                    if (String(role.roleId) === String(cur)) opt.selected = true;\r\n");
      out.write("                    select.appendChild(opt);\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("            data.list.forEach(role => {\r\n");
      out.write("                const opt = document.createElement('option');\r\n");
      out.write("                opt.value = role.roleName;\r\n");
      out.write("                opt.text  = role.roleName;\r\n");
      out.write("                roleFilterEl.appendChild(opt);\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("    } catch (e) { console.error(e); }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// 역할 지정\r\n");
      out.write("async function assignRole(memId, select) {\r\n");
      out.write("    const roleId   = select.value;\r\n");
      out.write("    const roleName = select.options[select.selectedIndex].text;\r\n");
      out.write("    if (!confirm('\"' + roleName + '\" 역할을 지정하시겠습니까?')) {\r\n");
      out.write("        select.value = select.dataset.current || '0';\r\n");
      out.write("        return;\r\n");
      out.write("    }\r\n");
      out.write("    const params = new URLSearchParams();\r\n");
      out.write("    params.append('memId', memId);\r\n");
      out.write("    params.append('roleId', roleId);\r\n");
      out.write("    try {\r\n");
      out.write("        const res  = await fetch('RoleAssign', { method: 'POST', body: params });\r\n");
      out.write("        const data = await res.json();\r\n");
      out.write("        if (data.status === 'success') {\r\n");
      out.write("            select.dataset.current = roleId;\r\n");
      out.write("            const wageEl = document.getElementById('wage-' + memId);\r\n");
      out.write("            if (wageEl) {\r\n");
      out.write("                wageEl.innerText = data.wage > 0 ? Number(data.wage).toLocaleString() + '원' : '-';\r\n");
      out.write("                const badge = document.createElement('span');\r\n");
      out.write("                badge.className = 'badge bg-success ms-1';\r\n");
      out.write("                badge.innerText = '저장됨';\r\n");
      out.write("                wageEl.after(badge);\r\n");
      out.write("                setTimeout(() => badge.remove(), 2000);\r\n");
      out.write("            }\r\n");
      out.write("        } else {\r\n");
      out.write("            showToast(data.message, 'danger');\r\n");
      out.write("            select.value = select.dataset.current || '0';\r\n");
      out.write("        }\r\n");
      out.write("    } catch (e) {\r\n");
      out.write("        showToast('통신 오류가 발생했습니다.', 'danger');\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// 직원 제외\r\n");
      out.write("function removeStaff(id, name) {\r\n");
      out.write("    if (confirm(\"'\" + name + \"' 직원을 매장에서 제외하시겠습니까?\")) {\r\n");
      out.write("        location.href = 'AdminMemberDelete?id=' + id;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// 필터\r\n");
      out.write("function filterMembers() {\r\n");
      out.write("    const nameFilter = document.getElementById('searchInput').value.toUpperCase();\r\n");
      out.write("    const roleFilter = document.getElementById('roleFilter').value;\r\n");
      out.write("    const typeFilter = document.getElementById('typeFilter').value;\r\n");
      out.write("    document.querySelectorAll('#memberTable tbody tr').forEach(tr => {\r\n");
      out.write("        if (tr.cells.length < 2) return;\r\n");
      out.write("        const name    = tr.cells[0].innerText;\r\n");
      out.write("        const phone   = tr.cells[1].innerText;\r\n");
      out.write("        const roleSelect = tr.querySelector('.role-select');\r\n");
      out.write("        const isAdmin = name.includes('점장');\r\n");
      out.write("        const nameMatch = name.toUpperCase().includes(nameFilter) || phone.toUpperCase().includes(nameFilter);\r\n");
      out.write("        let roleMatch = true;\r\n");
      out.write("        if (roleFilter === 'unassigned') roleMatch = roleSelect && roleSelect.value === '0';\r\n");
      out.write("        else if (roleFilter !== '') roleMatch = roleSelect && roleSelect.options[roleSelect.selectedIndex].text === roleFilter;\r\n");
      out.write("        let typeMatch = true;\r\n");
      out.write("        if (typeFilter === 'staff') typeMatch = !isAdmin;\r\n");
      out.write("        if (typeFilter === 'admin') typeMatch = isAdmin;\r\n");
      out.write("        tr.style.display = (nameMatch && roleMatch && typeMatch) ? '' : 'none';\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// 소속 신청 승인/거절\r\n");
      out.write("async function handleJoin(memId, storeId, action) {\r\n");
      out.write("    const label = action === 'approve' ? '승인' : '거절';\r\n");
      out.write("    if (!confirm(memId + ' 직원을 ' + label + '하시겠습니까?')) return;\r\n");
      out.write("\r\n");
      out.write("    const params = new URLSearchParams();\r\n");
      out.write("    params.append('action',  action);\r\n");
      out.write("    params.append('memId',   memId);\r\n");
      out.write("    params.append('storeId', storeId);\r\n");
      out.write("\r\n");
      out.write("    try {\r\n");
      out.write("        const res  = await fetch('StoreMemberManage', { method: 'POST', body: params });\r\n");
      out.write("        const data = await res.json();\r\n");
      out.write("        showToast(data.message, data.status === 'success' ? 'success' : 'danger');\r\n");
      out.write("        if (data.status === 'success') location.reload();\r\n");
      out.write("    } catch (e) {\r\n");
      out.write("        showToast('통신 오류가 발생했습니다.', 'danger');\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// 새 매장 신청 (기능 연결)\r\n");
      out.write("async function requestCreateStore() {\r\n");
      out.write("    const storeId   = document.getElementById('newStoreId').value.trim();\r\n");
      out.write("    const storeName = document.getElementById('newStoreName').value.trim();\r\n");
      out.write("    if (!storeId || !storeName) {\r\n");
      out.write("        showToast('매장 코드와 이름을 입력해주세요.', 'warning');\r\n");
      out.write("        return;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    const params = new URLSearchParams();\r\n");
      out.write("    params.append('action',    'createStore');\r\n");
      out.write("    params.append('storeId',   storeId);\r\n");
      out.write("    params.append('storeName', storeName);\r\n");
      out.write("\r\n");
      out.write("    try {\r\n");
      out.write("        const res  = await fetch('StoreMemberManage', { method: 'POST', body: params });\r\n");
      out.write("        const data = await res.json();\r\n");
      out.write("        showToast(data.message, data.status === 'success' ? 'success' : 'danger');\r\n");
      out.write("        if (data.status === 'success') {\r\n");
      out.write("            bootstrap.Modal.getInstance(document.getElementById('addStoreModal')).hide();\r\n");
      out.write("            location.reload();\r\n");
      out.write("        }\r\n");
      out.write("    } catch (e) {\r\n");
      out.write("        showToast('통신 오류가 발생했습니다.', 'danger');\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// 매장 설정 저장 (UI only - 주휴수당 기능은 추후 연결)\r\n");
      out.write("function saveStoreSetting() {\r\n");
      out.write("    showToast('설정이 저장되었습니다. (주휴수당 기능은 추후 업데이트 예정)', 'info');\r\n");
      out.write("    bootstrap.Modal.getInstance(document.getElementById('storeSettingModal')).hide();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// 근무 설정 모달 열기\r\n");
      out.write("function openWorkSettingModal(memId, memName, workStart, workEnd, workType) {\r\n");
      out.write("    document.getElementById('wsMemId').value       = memId;\r\n");
      out.write("    document.getElementById('workSettingName').innerText = '- ' + memName;\r\n");
      out.write("    document.getElementById('wsStart').value = workStart || '';\r\n");
      out.write("    document.getElementById('wsEnd').value   = workEnd   || '';\r\n");
      out.write("\r\n");
      out.write("    // 라디오 선택\r\n");
      out.write("    document.querySelectorAll('input[name=\"wsType\"]').forEach(function(r) {\r\n");
      out.write("        r.checked = (r.value === workType);\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    updateWagePreview();\r\n");
      out.write("    var modal = new bootstrap.Modal(document.getElementById('workSettingModal'));\r\n");
      out.write("    modal.show();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// 시급 미리보기 업데이트\r\n");
      out.write("function updateWagePreview() {\r\n");
      out.write("    var startVal = document.getElementById('wsStart').value;\r\n");
      out.write("    var endVal   = document.getElementById('wsEnd').value;\r\n");
      out.write("    var typeEl   = document.querySelector('input[name=\"wsType\"]:checked');\r\n");
      out.write("    var preview  = document.getElementById('wagePreview');\r\n");
      out.write("\r\n");
      out.write("    if (!startVal || !endVal || !typeEl) {\r\n");
      out.write("        preview.innerHTML = '<span class=\"text-muted small\">시간대·유형을 선택하면 표시됩니다.</span>';\r\n");
      out.write("        return;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    var startH   = parseInt(startVal.split(':')[0]);\r\n");
      out.write("    var endH     = parseInt(endVal.split(':')[0]);\r\n");
      out.write("    var workType = typeEl.value;\r\n");
      out.write("    var html     = '';\r\n");
      out.write("\r\n");
      out.write("    var isNight  = endH >= 22 || endH < 6 || startH < 6;\r\n");
      out.write("    var hasDay   = startH < 22 && endH > 6;\r\n");
      out.write("\r\n");
      out.write("    if (workType === '평일' || workType === '전체') {\r\n");
      out.write("        if (hasDay)   html += '<span class=\"badge bg-primary\">평일주간 ×1.0</span> ';\r\n");
      out.write("        if (isNight)  html += '<span class=\"badge bg-dark\">평일야간 ×1.5</span> ';\r\n");
      out.write("    }\r\n");
      out.write("    if (workType === '주말' || workType === '전체') {\r\n");
      out.write("        if (hasDay)   html += '<span class=\"badge bg-warning text-dark\">주말주간 ×1.5</span> ';\r\n");
      out.write("        if (isNight)  html += '<span class=\"badge bg-danger\">주말야간 ×2.0</span> ';\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    preview.innerHTML = html || '<span class=\"text-muted small\">해당 없음</span>';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// 근무 설정 저장\r\n");
      out.write("async function saveWorkSetting() {\r\n");
      out.write("    var memId    = document.getElementById('wsMemId').value;\r\n");
      out.write("    var storeId  = document.getElementById('wsStoreId').value;\r\n");
      out.write("    var start    = document.getElementById('wsStart').value;\r\n");
      out.write("    var end      = document.getElementById('wsEnd').value;\r\n");
      out.write("    var typeEl   = document.querySelector('input[name=\"wsType\"]:checked');\r\n");
      out.write("\r\n");
      out.write("    if (!start || !end) { showToast('근무 시간을 입력해주세요.', 'warning'); return; }\r\n");
      out.write("    if (!typeEl)        { showToast('근무 유형을 선택해주세요.', 'warning'); return; }\r\n");
      out.write("\r\n");
      out.write("    var params = new URLSearchParams();\r\n");
      out.write("    params.append('action',     'saveWorkSetting');\r\n");
      out.write("    params.append('memId',      memId);\r\n");
      out.write("    params.append('storeId',    storeId);\r\n");
      out.write("    params.append('workStart',  start);\r\n");
      out.write("    params.append('workEnd',    end);\r\n");
      out.write("    params.append('workType',   typeEl.value);\r\n");
      out.write("\r\n");
      out.write("    try {\r\n");
      out.write("        var res  = await fetch('StoreMemberManage', { method: 'POST', body: params });\r\n");
      out.write("        var data = await res.json();\r\n");
      out.write("        showToast(data.message, data.status === 'success' ? 'success' : 'danger');\r\n");
      out.write("        if (data.status === 'success') {\r\n");
      out.write("            bootstrap.Modal.getInstance(document.getElementById('workSettingModal')).hide();\r\n");
      out.write("            location.reload();\r\n");
      out.write("        }\r\n");
      out.write("    } catch (e) {\r\n");
      out.write("        showToast('통신 오류가 발생했습니다.', 'danger');\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// 시간 변경 시 미리보기 업데이트\r\n");
      out.write("document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("    document.getElementById('wsStart').addEventListener('change', updateWagePreview);\r\n");
      out.write("    document.getElementById('wsEnd').addEventListener('change', updateWagePreview);\r\n");
      out.write("    document.querySelectorAll('input[name=\"wsType\"]').forEach(function(r) {\r\n");
      out.write("        r.addEventListener('change', updateWagePreview);\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("document.addEventListener('DOMContentLoaded', loadRoleOptions);\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
